{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-plugin-classloader",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-plugin-classloader-1.0.0-alpha2.jar",
          "url": "opensearch-plugin-classloader-1.0.0-alpha2.jar",
          "size": 6540,
          "sha512": "6c437d19aa6246518af6fbfe0064d01e83abd52d6e46be67141685d99829f6d473b3eccc5aa753d35a40d4bb89a6f3dc4e9cb935f5e94fd4f4192db40ff2d83e",
          "sha256": "4996dfd7df31430a728117ee34756a2a2a4a99491b60c97a15c54a37f5096971",
          "sha1": "23b56063baba21021343ec34fc00c72379981a7e",
          "md5": "ee6c0fcc8a19de49855429705dc57829"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-plugin-classloader-1.0.0-alpha2.jar",
          "url": "opensearch-plugin-classloader-1.0.0-alpha2.jar",
          "size": 6540,
          "sha512": "6c437d19aa6246518af6fbfe0064d01e83abd52d6e46be67141685d99829f6d473b3eccc5aa753d35a40d4bb89a6f3dc4e9cb935f5e94fd4f4192db40ff2d83e",
          "sha256": "4996dfd7df31430a728117ee34756a2a2a4a99491b60c97a15c54a37f5096971",
          "sha1": "23b56063baba21021343ec34fc00c72379981a7e",
          "md5": "ee6c0fcc8a19de49855429705dc57829"
        }
      ]
    }
  ]
}
