{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "script-expert-scoring",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "script-expert-scoring-1.0.0-alpha2.jar",
          "url": "script-expert-scoring-1.0.0-alpha2.jar",
          "size": 12657,
          "sha512": "cd6e00908197fba8cd0eea081ebc6c974522982e0d8994cdda2eba66aab2db832a7097a84cf46d33aab65c8a9c1d8cc63a6a31012ae9bb6b3e48f0d6ae2c19c7",
          "sha256": "b92adda90080a70a006c4916475c78e86c8a5292fd8e3e0d4777c89e760355a5",
          "sha1": "eb1f2be7b0ab9ebc3d392e34374567dad13fa67f",
          "md5": "b1bc87ccc66256e0825ad3e89e48b257"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "script-expert-scoring-1.0.0-alpha2.jar",
          "url": "script-expert-scoring-1.0.0-alpha2.jar",
          "size": 12657,
          "sha512": "cd6e00908197fba8cd0eea081ebc6c974522982e0d8994cdda2eba66aab2db832a7097a84cf46d33aab65c8a9c1d8cc63a6a31012ae9bb6b3e48f0d6ae2c19c7",
          "sha256": "b92adda90080a70a006c4916475c78e86c8a5292fd8e3e0d4777c89e760355a5",
          "sha1": "eb1f2be7b0ab9ebc3d392e34374567dad13fa67f",
          "md5": "b1bc87ccc66256e0825ad3e89e48b257"
        }
      ]
    }
  ]
}
