{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "lang-painless",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch.plugin",
          "module": "opensearch-scripting-painless-spi",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "lang-painless-1.0.0-alpha2.jar",
          "url": "lang-painless-1.0.0-alpha2.jar",
          "size": 710720,
          "sha512": "256e4783592f94ad3e10a8344ade0692d60b324741a82615b687d4c7d91782f7625d24966302c4729a5e9855065ea6052c9bb089f227f3519c62ae426de090d0",
          "sha256": "68ed7a48c5fa1c35ab35ee5fbac681fedf09f93a1f2a945cdd1df8ec2da33604",
          "sha1": "52a7903f03ec0828b296b7945e54c8f9dfe46570",
          "md5": "6a343469ac96ff1df451f8a5f4fe08fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch.plugin",
          "module": "opensearch-scripting-painless-spi",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "lang-painless-1.0.0-alpha2.jar",
          "url": "lang-painless-1.0.0-alpha2.jar",
          "size": 710720,
          "sha512": "256e4783592f94ad3e10a8344ade0692d60b324741a82615b687d4c7d91782f7625d24966302c4729a5e9855065ea6052c9bb089f227f3519c62ae426de090d0",
          "sha256": "68ed7a48c5fa1c35ab35ee5fbac681fedf09f93a1f2a945cdd1df8ec2da33604",
          "sha1": "52a7903f03ec0828b296b7945e54c8f9dfe46570",
          "md5": "6a343469ac96ff1df451f8a5f4fe08fc"
        }
      ]
    }
  ]
}
