{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "wildfly",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "master",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wildfly-1.0.0-alpha2.war",
          "url": "wildfly-1.0.0-alpha2.war",
          "size": 28984384,
          "sha512": "4b77566807529b5d07878ff400e456e5397a9a0fde9efd74f26092c63149e9fa2005c0d7de98171c6050fdb2685b2236f6f8b88bb9f7a0b675ff1e7d93cb40c2",
          "sha256": "6469ddcde130a41bfe924206b791d943f43a6f85a8835d78cba6e51f676306c0",
          "sha1": "177e9cb0b7cc91e23005a421a48a3e6c921fb615",
          "md5": "765a06e6bbb4fd1ac95b84b80361a985"
        }
      ]
    }
  ]
}
