{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "repository-url",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "repository-url-1.0.0-beta1.jar",
          "url": "repository-url-1.0.0-beta1.jar",
          "size": 15009,
          "sha512": "75defa694ef6fab5de11eb3386bf335106e1d8752de2341ed077746124f9662d289475fe3eed01f440ffb1be85c0a8278c668c036d0036ec574d01b1f20629dc",
          "sha256": "e8d2b31aa1c24af0dfe4eef212ae72005b2aeaf0e4bd515b879d22fc58c08c48",
          "sha1": "a6d2f8b643dbc41431bb9fab9456044af40cf9f6",
          "md5": "8730ccf674467514b59b9fc9bc6d818f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "repository-url-1.0.0-beta1.jar",
          "url": "repository-url-1.0.0-beta1.jar",
          "size": 15009,
          "sha512": "75defa694ef6fab5de11eb3386bf335106e1d8752de2341ed077746124f9662d289475fe3eed01f440ffb1be85c0a8278c668c036d0036ec574d01b1f20629dc",
          "sha256": "e8d2b31aa1c24af0dfe4eef212ae72005b2aeaf0e4bd515b879d22fc58c08c48",
          "sha1": "a6d2f8b643dbc41431bb9fab9456044af40cf9f6",
          "md5": "8730ccf674467514b59b9fc9bc6d818f"
        }
      ]
    }
  ]
}
