{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "wildfly",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "master",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wildfly-1.0.0-beta1.war",
          "url": "wildfly-1.0.0-beta1.war",
          "size": 28984426,
          "sha512": "b8cc60509ad5d5e3f33ab5bb7d8988d7fa79f898067142efc56e92e6fdf97f89448507f7f7e39c40fe1b56009b206e6efcb26a35be261fd1de39a39656d7e6b1",
          "sha256": "a672b5e684307e42015a4e8d8b266cce03a80357dd45ae725b40f7d108f7e6a8",
          "sha1": "28982653b66b6e8824bda95bdea267daa015c982",
          "md5": "9209e6fd72b273c3de7afb40a47b9bf4"
        }
      ]
    }
  ]
}
