{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-plugin-classloader",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-plugin-classloader-1.0.0-beta1.jar",
          "url": "opensearch-plugin-classloader-1.0.0-beta1.jar",
          "size": 6538,
          "sha512": "1b1b13d5946d1528f4cb9304490c24478c4a92006189009f5a57555cad2fc3e7ff7d369f91600f825f2dab06ebcb06f1791ad64292d0c1907a9e46db144a0dd3",
          "sha256": "04a2aad5c9346fa5936e74caecbe4fab91a56c725221bf1aac2bd9b92320a620",
          "sha1": "8bdb13c96d6b52f5ebb76cd1aa31ddc6fbf3d9f5",
          "md5": "55be2ae21beaef46852ca6547b615b0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-plugin-classloader-1.0.0-beta1.jar",
          "url": "opensearch-plugin-classloader-1.0.0-beta1.jar",
          "size": 6538,
          "sha512": "1b1b13d5946d1528f4cb9304490c24478c4a92006189009f5a57555cad2fc3e7ff7d369f91600f825f2dab06ebcb06f1791ad64292d0c1907a9e46db144a0dd3",
          "sha256": "04a2aad5c9346fa5936e74caecbe4fab91a56c725221bf1aac2bd9b92320a620",
          "sha1": "8bdb13c96d6b52f5ebb76cd1aa31ddc6fbf3d9f5",
          "md5": "55be2ae21beaef46852ca6547b615b0e"
        }
      ]
    }
  ]
}
