{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-ukrainian",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-morfologik",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-stemming",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-fsa",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "ua.net.nlp",
          "module": "morfologik-ukrainian-search",
          "version": {
            "requires": "3.7.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-ukrainian-1.0.0-beta1.jar",
          "url": "analysis-ukrainian-1.0.0-beta1.jar",
          "size": 7754,
          "sha512": "32b6eb10ab733b6b0343d79751bca7ccfe674d127342ee248d88972b77aa26a1db056fe2a58240a4dcb5dfaad7c962083afdcec82b226861bcff2dd5b534b4fb",
          "sha256": "518a8be7eea615b7188a652cafff4efbae150b67e4c0aa02fb1195cb6552182f",
          "sha1": "99428a592a64519181ee06672a523226516cc6da",
          "md5": "aba9221db18c395ce39e8ffcc0fa8d78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-morfologik",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-stemming",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-fsa",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "ua.net.nlp",
          "module": "morfologik-ukrainian-search",
          "version": {
            "requires": "3.7.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-ukrainian-1.0.0-beta1.jar",
          "url": "analysis-ukrainian-1.0.0-beta1.jar",
          "size": 7754,
          "sha512": "32b6eb10ab733b6b0343d79751bca7ccfe674d127342ee248d88972b77aa26a1db056fe2a58240a4dcb5dfaad7c962083afdcec82b226861bcff2dd5b534b4fb",
          "sha256": "518a8be7eea615b7188a652cafff4efbae150b67e4c0aa02fb1195cb6552182f",
          "sha1": "99428a592a64519181ee06672a523226516cc6da",
          "md5": "aba9221db18c395ce39e8ffcc0fa8d78"
        }
      ]
    }
  ]
}
