{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-extras-client",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-extras-client-1.0.0-alpha1.jar",
          "url": "mapper-extras-client-1.0.0-alpha1.jar",
          "size": 84246,
          "sha512": "3cc1c6a16d5dc3ad7d2a0be2d304b1e3bea9e4f0c262f82b452ad6f892464d8d515f86945876c9afbfd24628f359b19aefb9986d817761d840a45bdbd537098a",
          "sha256": "318fe0aeede2d21ecf155b16a240a4092c361dd684c174ce567a97affdf09999",
          "sha1": "646fda51d710281d380fb2fe518700e323958327",
          "md5": "33cf9289fa12e589b537652b3e499fae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-extras-client-1.0.0-alpha1.jar",
          "url": "mapper-extras-client-1.0.0-alpha1.jar",
          "size": 84246,
          "sha512": "3cc1c6a16d5dc3ad7d2a0be2d304b1e3bea9e4f0c262f82b452ad6f892464d8d515f86945876c9afbfd24628f359b19aefb9986d817761d840a45bdbd537098a",
          "sha256": "318fe0aeede2d21ecf155b16a240a4092c361dd684c174ce567a97affdf09999",
          "sha1": "646fda51d710281d380fb2fe518700e323958327",
          "md5": "33cf9289fa12e589b537652b3e499fae"
        }
      ]
    }
  ]
}
