{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "lang-mustache-client",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lang-mustache-client-1.0.0-alpha1.jar",
          "url": "lang-mustache-client-1.0.0-alpha1.jar",
          "size": 63411,
          "sha512": "85fd63a0c2e10996a8df51486141be0724396361c4ae9abb2d1797b6f4fe7d65a387f83415c931a61501554bea084f543ee09c501d69d50c0820ad1fa4f96e57",
          "sha256": "d8773706aae39d48500bd1290ace3fc4f218c5d6e12eba511c42df2d863a8d0c",
          "sha1": "e45e97741dabd1bf7e736aa77b9f99dc39477bc6",
          "md5": "ac2e2f963956b456837200f03cc0216c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lang-mustache-client-1.0.0-alpha1.jar",
          "url": "lang-mustache-client-1.0.0-alpha1.jar",
          "size": 63411,
          "sha512": "85fd63a0c2e10996a8df51486141be0724396361c4ae9abb2d1797b6f4fe7d65a387f83415c931a61501554bea084f543ee09c501d69d50c0820ad1fa4f96e57",
          "sha256": "d8773706aae39d48500bd1290ace3fc4f218c5d6e12eba511c42df2d863a8d0c",
          "sha1": "e45e97741dabd1bf7e736aa77b9f99dc39477bc6",
          "md5": "ac2e2f963956b456837200f03cc0216c"
        }
      ]
    }
  ]
}
