{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-plugin-cli",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-fips",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bc-fips",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-plugin-cli-1.0.0-alpha1.jar",
          "url": "opensearch-plugin-cli-1.0.0-alpha1.jar",
          "size": 34682,
          "sha512": "e1298f8b0dfe02dae11b4d60e6e221499dd0fa2be7bbccb032213917c99e9f8b8ba86b0010ca08e42e00886553cd86331d07b25afc23bcbea6273b525f3b033d",
          "sha256": "aa41901359b3cf5e25c17196b88fc8f747cda6ff3450e19e17c6b3ba3d06415e",
          "sha1": "bc82e06e4211b7b93137b7f9f77cde7d16579818",
          "md5": "31bd7cc1b079ded57cb972880e53a8f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-fips",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bc-fips",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-plugin-cli-1.0.0-alpha1.jar",
          "url": "opensearch-plugin-cli-1.0.0-alpha1.jar",
          "size": 34682,
          "sha512": "e1298f8b0dfe02dae11b4d60e6e221499dd0fa2be7bbccb032213917c99e9f8b8ba86b0010ca08e42e00886553cd86331d07b25afc23bcbea6273b525f3b033d",
          "sha256": "aa41901359b3cf5e25c17196b88fc8f747cda6ff3450e19e17c6b3ba3d06415e",
          "sha1": "bc82e06e4211b7b93137b7f9f77cde7d16579818",
          "md5": "31bd7cc1b079ded57cb972880e53a8f1"
        }
      ]
    }
  ]
}
