{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "opensearch-scripting-painless-spi",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-scripting-painless-spi-1.0.0-alpha1.jar",
          "url": "opensearch-scripting-painless-spi-1.0.0-alpha1.jar",
          "size": 29663,
          "sha512": "24693b6a82aa4fa9715976af5b24b23727ef0746a4a0a4dedc43ed62e0d4272c72370df34fb61c9343ccf73ad10c0533793ce78939b32ebb87ab5a33f7713931",
          "sha256": "a0285509b2121aa831ce48551409794f0a5d4ed4482eaf45278a7738d1c33785",
          "sha1": "5bea9f41003cf9bf98099ed7e25f441696613b17",
          "md5": "e511e0db0f9f17db264e282794fdb4ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-scripting-painless-spi-1.0.0-alpha1.jar",
          "url": "opensearch-scripting-painless-spi-1.0.0-alpha1.jar",
          "size": 29663,
          "sha512": "24693b6a82aa4fa9715976af5b24b23727ef0746a4a0a4dedc43ed62e0d4272c72370df34fb61c9343ccf73ad10c0533793ce78939b32ebb87ab5a33f7713931",
          "sha256": "a0285509b2121aa831ce48551409794f0a5d4ed4482eaf45278a7738d1c33785",
          "sha1": "5bea9f41003cf9bf98099ed7e25f441696613b17",
          "md5": "e511e0db0f9f17db264e282794fdb4ad"
        }
      ]
    }
  ]
}
