{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "custom-significance-heuristic",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "custom-significance-heuristic-1.0.0-beta1.jar",
          "url": "custom-significance-heuristic-1.0.0-beta1.jar",
          "size": 7937,
          "sha512": "e763c993e099f244adef8dc63c1fff986fa05e96e3df7394982d1f157a5fb2a3ffbc28c9819c81c7aeb6ce7b666bdeecc98e44d46cc0803e3177dcda30ef0c15",
          "sha256": "445dd1257f566c80a0e98ed255f87350cccbacaeda1faa8e2d2a9ad5817b7f16",
          "sha1": "ccc6719a61f80731d1772c808a556468dc1b50d1",
          "md5": "8504f20ba7d906d346c4f3ec21602f1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-significance-heuristic-1.0.0-beta1.jar",
          "url": "custom-significance-heuristic-1.0.0-beta1.jar",
          "size": 7937,
          "sha512": "e763c993e099f244adef8dc63c1fff986fa05e96e3df7394982d1f157a5fb2a3ffbc28c9819c81c7aeb6ce7b666bdeecc98e44d46cc0803e3177dcda30ef0c15",
          "sha256": "445dd1257f566c80a0e98ed255f87350cccbacaeda1faa8e2d2a9ad5817b7f16",
          "sha1": "ccc6719a61f80731d1772c808a556468dc1b50d1",
          "md5": "8504f20ba7d906d346c4f3ec21602f1c"
        }
      ]
    }
  ]
}
