{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-stempel",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-stempel",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-stempel-1.0.0-alpha2.jar",
          "url": "analysis-stempel-1.0.0-alpha2.jar",
          "size": 10130,
          "sha512": "440db346a5db39716742677cbb07e8e4266f9fc48c66c1f003f3eec7c317484a033de2acacc935a550c7e517c13232bee27b6ba32f25c19eaf4b7b3a89679f25",
          "sha256": "e03b2a423ecb8e625ab56729bb936e1af14faec23616dd655d0cad46490d9136",
          "sha1": "db281129f8e785edf494a4f73a65a29d50787814",
          "md5": "63f448c4fc3850ef587187d3044902b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-stempel",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-stempel-1.0.0-alpha2.jar",
          "url": "analysis-stempel-1.0.0-alpha2.jar",
          "size": 10130,
          "sha512": "440db346a5db39716742677cbb07e8e4266f9fc48c66c1f003f3eec7c317484a033de2acacc935a550c7e517c13232bee27b6ba32f25c19eaf4b7b3a89679f25",
          "sha256": "e03b2a423ecb8e625ab56729bb936e1af14faec23616dd655d0cad46490d9136",
          "sha1": "db281129f8e785edf494a4f73a65a29d50787814",
          "md5": "63f448c4fc3850ef587187d3044902b4"
        }
      ]
    }
  ]
}
