{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "systemd",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "systemd-1.0.0-alpha2.jar",
          "url": "systemd-1.0.0-alpha2.jar",
          "size": 9265,
          "sha512": "681f3ed5aabde3269c038d135ad43e85c5a809c6e3d33059f8a2375a29e9583abccfcbf0d2f441638abb6b2eb0a90d611827867ab0fc01fddfd98f1a1a1a03da",
          "sha256": "465e9da5fa2546a68676df1d7c4a09b8d6aa63bd940be678875f04001337aa75",
          "sha1": "b1f4c06776f524c60df58cd86cc93e87020bf776",
          "md5": "5ca158221ac2fcf06a15994e85521b9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "systemd-1.0.0-alpha2.jar",
          "url": "systemd-1.0.0-alpha2.jar",
          "size": 9265,
          "sha512": "681f3ed5aabde3269c038d135ad43e85c5a809c6e3d33059f8a2375a29e9583abccfcbf0d2f441638abb6b2eb0a90d611827867ab0fc01fddfd98f1a1a1a03da",
          "sha256": "465e9da5fa2546a68676df1d7c4a09b8d6aa63bd940be678875f04001337aa75",
          "sha1": "b1f4c06776f524c60df58cd86cc93e87020bf776",
          "md5": "5ca158221ac2fcf06a15994e85521b9f"
        }
      ]
    }
  ]
}
