{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "painless-whitelist",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "painless-whitelist-1.0.0-beta1.jar",
          "url": "painless-whitelist-1.0.0-beta1.jar",
          "size": 12479,
          "sha512": "bbca2fecec1c767452bb41ef5f1c2e38bbefdc4b252e474c54450dbd9cf763d12c123b1e6f63ae1e3657db5372007b2b390cd1bc9165c023613aaeecd7543797",
          "sha256": "12895a2728caf68f330a020310426749928fa189b3797f051e72769c201d217f",
          "sha1": "b0151aa4646d5b2f7ef7f7edb82dbf7d8bd8c367",
          "md5": "d48fc1df014ea8df9153ad89e1558b98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "painless-whitelist-1.0.0-beta1.jar",
          "url": "painless-whitelist-1.0.0-beta1.jar",
          "size": 12479,
          "sha512": "bbca2fecec1c767452bb41ef5f1c2e38bbefdc4b252e474c54450dbd9cf763d12c123b1e6f63ae1e3657db5372007b2b390cd1bc9165c023613aaeecd7543797",
          "sha256": "12895a2728caf68f330a020310426749928fa189b3797f051e72769c201d217f",
          "sha1": "b0151aa4646d5b2f7ef7f7edb82dbf7d8bd8c367",
          "md5": "d48fc1df014ea8df9153ad89e1558b98"
        }
      ]
    }
  ]
}
