{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.client.test",
    "module": "test",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-1.0.0-alpha2.jar",
          "url": "test-1.0.0-alpha2.jar",
          "size": 9535,
          "sha512": "de6eaf0bb6d859f836ddf8f7cf5dd7da098984da06babe5763622d9a82f5746763a126103d114be176558d6c3a4220a63495c4ee2ca623976f4b9d1c61068e40",
          "sha256": "f3d4d7d1c30a124f5cb72754f70f5259adf47aeaf50c2534af4abf5a5aa47de9",
          "sha1": "a96edc41f5ddd265a2f9529f5f8b83d8ebd9cf93",
          "md5": "01d9fb1e7027368cd04e4350ae27b530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-1.0.0-alpha2.jar",
          "url": "test-1.0.0-alpha2.jar",
          "size": 9535,
          "sha512": "de6eaf0bb6d859f836ddf8f7cf5dd7da098984da06babe5763622d9a82f5746763a126103d114be176558d6c3a4220a63495c4ee2ca623976f4b9d1c61068e40",
          "sha256": "f3d4d7d1c30a124f5cb72754f70f5259adf47aeaf50c2534af4abf5a5aa47de9",
          "sha1": "a96edc41f5ddd265a2f9529f5f8b83d8ebd9cf93",
          "md5": "01d9fb1e7027368cd04e4350ae27b530"
        }
      ]
    }
  ]
}
