{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.gradle",
    "module": "build-tools",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "nebula-publishing-plugin",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-info-plugin",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.apache.rat",
          "module": "apache-rat",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "de.thetaphi",
          "module": "forbiddenapis",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.avast.gradle",
          "module": "gradle-docker-compose-plugin",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha2.jar",
          "url": "build-tools-1.0.0-alpha2.jar",
          "size": 1056341,
          "sha512": "9553b9d33570e2cad6075bcf1f22a119358365661b2b9f8ae7059579371e0072a36e449a31781eef110ac51832432263988d6342fee6ee3fbcd20a594ee0c0c2",
          "sha256": "138e4c2689575b130437ada70957d2cf8d0bf888b95ba13364931a16733c9780",
          "sha1": "4492fc1b562bc85a9b4aeafa8ac9e19b7a64a715",
          "md5": "2df977e6b0c44f7c8798a5f85ffa4239"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "nebula-publishing-plugin",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-info-plugin",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.apache.rat",
          "module": "apache-rat",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "de.thetaphi",
          "module": "forbiddenapis",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.avast.gradle",
          "module": "gradle-docker-compose-plugin",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha2.jar",
          "url": "build-tools-1.0.0-alpha2.jar",
          "size": 1056341,
          "sha512": "9553b9d33570e2cad6075bcf1f22a119358365661b2b9f8ae7059579371e0072a36e449a31781eef110ac51832432263988d6342fee6ee3fbcd20a594ee0c0c2",
          "sha256": "138e4c2689575b130437ada70957d2cf8d0bf888b95ba13364931a16733c9780",
          "sha1": "4492fc1b562bc85a9b4aeafa8ac9e19b7a64a715",
          "md5": "2df977e6b0c44f7c8798a5f85ffa4239"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.gradle",
          "module": "build-tools",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha2-test-fixtures.jar",
          "url": "build-tools-1.0.0-alpha2-test-fixtures.jar",
          "size": 15953,
          "sha512": "588d074b935568ae8761a23e76e3cc03bed647ef34571039f29a56596a94c0167824d497286ff44061d671ad2998cbe49d2d221b927bbdf20ab8677b1f92dde4",
          "sha256": "4e4db45a7a18574cbe65e3cbd4918a69ea0a0addaf08cf9e1adf5d5bb672f097",
          "sha1": "023827cfcfcdf55d8fbb6686ad01cb4e3586bfde",
          "md5": "e723daa7deaaee889b4053614c9c44be"
        }
      ],
      "capabilities": [
        {
          "group": "org.opensearch.gradle",
          "name": "build-tools-test-fixtures",
          "version": "1.0.0-alpha2"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.gradle",
          "module": "build-tools",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha2-test-fixtures.jar",
          "url": "build-tools-1.0.0-alpha2-test-fixtures.jar",
          "size": 15953,
          "sha512": "588d074b935568ae8761a23e76e3cc03bed647ef34571039f29a56596a94c0167824d497286ff44061d671ad2998cbe49d2d221b927bbdf20ab8677b1f92dde4",
          "sha256": "4e4db45a7a18574cbe65e3cbd4918a69ea0a0addaf08cf9e1adf5d5bb672f097",
          "sha1": "023827cfcfcdf55d8fbb6686ad01cb4e3586bfde",
          "md5": "e723daa7deaaee889b4053614c9c44be"
        }
      ],
      "capabilities": [
        {
          "group": "org.opensearch.gradle",
          "name": "build-tools-test-fixtures",
          "version": "1.0.0-alpha2"
        }
      ]
    }
  ]
}
