{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "aggs-matrix-stats-client",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aggs-matrix-stats-client-1.0.0-beta1.jar",
          "url": "aggs-matrix-stats-client-1.0.0-beta1.jar",
          "size": 57844,
          "sha512": "e95cc6a05fb1ebcc189126d95653f27259faf8bbc617f509ac4ba04128891f5cc781efdaa94f66afbf00c425a643a2ce962cadc5b998ac92954116c69982c296",
          "sha256": "4e1e3d06584a95cf16cde5ae799618917b5cd757c3dbef7efbe9847049645619",
          "sha1": "4ecd42d1ca763c71d2e6563c6eba5c23b4e0ded2",
          "md5": "68b4d0edff49dd7e82746f5cf946b736"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aggs-matrix-stats-client-1.0.0-beta1.jar",
          "url": "aggs-matrix-stats-client-1.0.0-beta1.jar",
          "size": 57844,
          "sha512": "e95cc6a05fb1ebcc189126d95653f27259faf8bbc617f509ac4ba04128891f5cc781efdaa94f66afbf00c425a643a2ce962cadc5b998ac92954116c69982c296",
          "sha256": "4e1e3d06584a95cf16cde5ae799618917b5cd757c3dbef7efbe9847049645619",
          "sha1": "4ecd42d1ca763c71d2e6563c6eba5c23b4e0ded2",
          "md5": "68b4d0edff49dd7e82746f5cf946b736"
        }
      ]
    }
  ]
}
