{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "reindex-client",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-ssl-config",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "reindex-client-1.0.0-beta1.jar",
          "url": "reindex-client-1.0.0-beta1.jar",
          "size": 116076,
          "sha512": "51eb39c4b9b4cbffb4616cd39ce431c0b725032c10455af87d26b7182e4b95cb1712097a4c0475dcd71198a04b2a5e0419b03eabb7ab1c8863f83ef7c4972c92",
          "sha256": "a3ecfe7431fb4d831189973a3a98bb2a1f44e0a1a9cc82aa293ecb7d14dcac69",
          "sha1": "cd79b692d273b76c0269a3040d9f830715118abe",
          "md5": "de238a4db791bc329a64f8be5e8420c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-ssl-config",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "reindex-client-1.0.0-beta1.jar",
          "url": "reindex-client-1.0.0-beta1.jar",
          "size": 116076,
          "sha512": "51eb39c4b9b4cbffb4616cd39ce431c0b725032c10455af87d26b7182e4b95cb1712097a4c0475dcd71198a04b2a5e0419b03eabb7ab1c8863f83ef7c4972c92",
          "sha256": "a3ecfe7431fb4d831189973a3a98bb2a1f44e0a1a9cc82aa293ecb7d14dcac69",
          "sha1": "cd79b692d273b76c0269a3040d9f830715118abe",
          "md5": "de238a4db791bc329a64f8be5e8420c5"
        }
      ]
    }
  ]
}
