{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-annotated-text",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-annotated-text-1.0.0-alpha2.jar",
          "url": "mapper-annotated-text-1.0.0-alpha2.jar",
          "size": 32815,
          "sha512": "054f224c7e30236764eb780ad8b760820b1a2d6142ebc05aa2297574a0a993cc1f32ffaa92f318204682daad959cb8899720ea2fb9b8d76d21befffd3bf7387c",
          "sha256": "f984a16d6127d0dd82779c1a88cded94ab550fa644a7a889d80c96e31ce78fda",
          "sha1": "178f10bd9ec3c1d2a97dfb7840b7652bd4b27bde",
          "md5": "c5147f2ffbc1bcb04e598d505917f107"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-annotated-text-1.0.0-alpha2.jar",
          "url": "mapper-annotated-text-1.0.0-alpha2.jar",
          "size": 32815,
          "sha512": "054f224c7e30236764eb780ad8b760820b1a2d6142ebc05aa2297574a0a993cc1f32ffaa92f318204682daad959cb8899720ea2fb9b8d76d21befffd3bf7387c",
          "sha256": "f984a16d6127d0dd82779c1a88cded94ab550fa644a7a889d80c96e31ce78fda",
          "sha1": "178f10bd9ec3c1d2a97dfb7840b7652bd4b27bde",
          "md5": "c5147f2ffbc1bcb04e598d505917f107"
        }
      ]
    }
  ]
}
