{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-core",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-core-1.0.0-alpha1.jar",
          "url": "opensearch-core-1.0.0-alpha1.jar",
          "size": 59739,
          "sha512": "509606c7e289cb5aff01ddb968e2f0c70165dace41e0fe1b8c583896183a084aa088a0ce7590735b120264a02407511e6a8097fc5d9382ef33ce583fe10e7bd5",
          "sha256": "1d54e2acd5ab016018ace253ca1cd1639e12471a99c69dd4100a67235f8bedea",
          "sha1": "0130643e5a40802b3462073999bab4359e396093",
          "md5": "c824d5120df9a8f82510a67d6df31458"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-core-1.0.0-alpha1.jar",
          "url": "opensearch-core-1.0.0-alpha1.jar",
          "size": 59739,
          "sha512": "509606c7e289cb5aff01ddb968e2f0c70165dace41e0fe1b8c583896183a084aa088a0ce7590735b120264a02407511e6a8097fc5d9382ef33ce583fe10e7bd5",
          "sha256": "1d54e2acd5ab016018ace253ca1cd1639e12471a99c69dd4100a67235f8bedea",
          "sha1": "0130643e5a40802b3462073999bab4359e396093",
          "md5": "c824d5120df9a8f82510a67d6df31458"
        }
      ]
    }
  ]
}
