{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "opensearch-scripting-painless-spi",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-scripting-painless-spi-1.0.0-alpha2.jar",
          "url": "opensearch-scripting-painless-spi-1.0.0-alpha2.jar",
          "size": 29659,
          "sha512": "1f33f50cc249cc3af27c024110595f63196b495daf7ba33fa0d1612027e1b9bd1d130f0719db6064224efdc86cde5c6e45ababc7fa9fb4b7c2ee35f04a140580",
          "sha256": "bd3fb045115dc89fd720acdc8c953880cdc9008ecafc8cb2e0eb28c5095764b7",
          "sha1": "28cb79543a78a784dda4ea66dab709a1e825d843",
          "md5": "1166cb7c0b748fe5ecb8fc732093bf50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-scripting-painless-spi-1.0.0-alpha2.jar",
          "url": "opensearch-scripting-painless-spi-1.0.0-alpha2.jar",
          "size": 29659,
          "sha512": "1f33f50cc249cc3af27c024110595f63196b495daf7ba33fa0d1612027e1b9bd1d130f0719db6064224efdc86cde5c6e45ababc7fa9fb4b7c2ee35f04a140580",
          "sha256": "bd3fb045115dc89fd720acdc8c953880cdc9008ecafc8cb2e0eb28c5095764b7",
          "sha1": "28cb79543a78a784dda4ea66dab709a1e825d843",
          "md5": "1166cb7c0b748fe5ecb8fc732093bf50"
        }
      ]
    }
  ]
}
