{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "rest-api-spec",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rest-api-spec-1.0.0-alpha2.jar",
          "url": "rest-api-spec-1.0.0-alpha2.jar",
          "size": 404964,
          "sha512": "f398fc26f9f8122603d7a70465ee650bd8b6cb467013384bdcdbe423a4beb0f4adeddced61a27c605ba5fa5763dc3acbd39d42b6e302ac25562e8237c3ed1314",
          "sha256": "a2daae5c000f96a1ded6254695104f4acf0a0db14ecbe925937551454a461ca2",
          "sha1": "eeb510c79f2885a5c8a2b05f3f37e59da1d7165a",
          "md5": "085cd41ca419053f920bbeb49447d14e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rest-api-spec-1.0.0-alpha2.jar",
          "url": "rest-api-spec-1.0.0-alpha2.jar",
          "size": 404964,
          "sha512": "f398fc26f9f8122603d7a70465ee650bd8b6cb467013384bdcdbe423a4beb0f4adeddced61a27c605ba5fa5763dc3acbd39d42b6e302ac25562e8237c3ed1314",
          "sha256": "a2daae5c000f96a1ded6254695104f4acf0a0db14ecbe925937551454a461ca2",
          "sha1": "eeb510c79f2885a5c8a2b05f3f37e59da1d7165a",
          "md5": "085cd41ca419053f920bbeb49447d14e"
        }
      ]
    }
  ]
}
