# frozen_string_literal: true
ruby '3.1.0', :engine => 'jruby', :engine_version => '9.4.2.0'
source "https://rubygems.org"

gem "jmespath"
gem "diff-lcs"
gem "i18n"
gem "tzinfo"
gem "json"
gem "mime-types"
gem 'concurrent-ruby', require: 'concurrent'
