{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "opensearch-scripting-painless-spi",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-scripting-painless-spi-1.0.0-alpha2.jar",
          "url": "opensearch-scripting-painless-spi-1.0.0-alpha2.jar",
          "size": 29660,
          "sha512": "582f1075250f0e2047d7875dc63c955eea1e9491fd45bd808cc6e3e604ca1bcb1c03172de394015335be1eeb86e8adf16230c46a251a879b7ffe7949ac092213",
          "sha256": "d80c20bca719762b80763d4416dfbf53f04dbcb1aacf66676314fc85bb84d388",
          "sha1": "4708653302438a3c2e5b999f2b38b69a3bfa0a13",
          "md5": "0bb03f5d5b7e86108a639370462446f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-scripting-painless-spi-1.0.0-alpha2.jar",
          "url": "opensearch-scripting-painless-spi-1.0.0-alpha2.jar",
          "size": 29660,
          "sha512": "582f1075250f0e2047d7875dc63c955eea1e9491fd45bd808cc6e3e604ca1bcb1c03172de394015335be1eeb86e8adf16230c46a251a879b7ffe7949ac092213",
          "sha256": "d80c20bca719762b80763d4416dfbf53f04dbcb1aacf66676314fc85bb84d388",
          "sha1": "4708653302438a3c2e5b999f2b38b69a3bfa0a13",
          "md5": "0bb03f5d5b7e86108a639370462446f8"
        }
      ]
    }
  ]
}
