{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "parent-join-client",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parent-join-client-1.0.0-beta1.jar",
          "url": "parent-join-client-1.0.0-beta1.jar",
          "size": 87348,
          "sha512": "8646f4b810961e642e671c52f599b348e3f5d8f6d5af8331c75218897e51145a1ea8c05e32f18061ca6635b18f17645416f97340b813809c88a9bf5de5013e73",
          "sha256": "1f8a5249d961ea67b7cbb6b04302e0bf21ce02db9e1852c2c08099811e204bec",
          "sha1": "14a8f832fb2d5b12d8142bb4aa49c18548b2d56e",
          "md5": "6b3cb040fa734b15871b32a101915ceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-join-client-1.0.0-beta1.jar",
          "url": "parent-join-client-1.0.0-beta1.jar",
          "size": 87348,
          "sha512": "8646f4b810961e642e671c52f599b348e3f5d8f6d5af8331c75218897e51145a1ea8c05e32f18061ca6635b18f17645416f97340b813809c88a9bf5de5013e73",
          "sha256": "1f8a5249d961ea67b7cbb6b04302e0bf21ce02db9e1852c2c08099811e204bec",
          "sha1": "14a8f832fb2d5b12d8142bb4aa49c18548b2d56e",
          "md5": "6b3cb040fa734b15871b32a101915ceb"
        }
      ]
    }
  ]
}
