{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "reindex-client",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-ssl-config",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "reindex-client-1.0.0-alpha2.jar",
          "url": "reindex-client-1.0.0-alpha2.jar",
          "size": 116073,
          "sha512": "32f913451744b6999c8d17a0535bfe2e19404b6ec20d6a7323f3b7f7b92db8437f360487be1446d70dcf9ab03e6e0fc3c7a15954fd08854faf8b613fdfa92c8c",
          "sha256": "d728dc91fe86c654560dc3b10b4fc978ff8cfcc94ab15470635d9b74639de262",
          "sha1": "ee999cda9f7b56fb85323edba623d0c87020d522",
          "md5": "5586d419ebb4b0cd484afec9c1ad8088"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-ssl-config",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "reindex-client-1.0.0-alpha2.jar",
          "url": "reindex-client-1.0.0-alpha2.jar",
          "size": 116073,
          "sha512": "32f913451744b6999c8d17a0535bfe2e19404b6ec20d6a7323f3b7f7b92db8437f360487be1446d70dcf9ab03e6e0fc3c7a15954fd08854faf8b613fdfa92c8c",
          "sha256": "d728dc91fe86c654560dc3b10b4fc978ff8cfcc94ab15470635d9b74639de262",
          "sha1": "ee999cda9f7b56fb85323edba623d0c87020d522",
          "md5": "5586d419ebb4b0cd484afec9c1ad8088"
        }
      ]
    }
  ]
}
