{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.client",
    "module": "transport",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "lang-mustache-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "percolator-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "parent-join-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "rank-eval-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "transport-1.0.0-alpha2.jar",
          "url": "transport-1.0.0-alpha2.jar",
          "size": 7601,
          "sha512": "eb429ebdc6e2c42b9b414b3c0b18fcc88e00567fe0896227b817f68a935dd1db35f60a1c13d3807fb259a1bb82fa79bc30ff187ebf7800bdd2bdf9ef78e183a9",
          "sha256": "18ae3506bf4e9b2d119768c13a15d3f37af3ddfc2b9d3bc96ecdfc13b98183db",
          "sha1": "44ffc6a47ff0c240339d43b6ab896394e34bb276",
          "md5": "a611ba8fa03872c8b6adfad50a760dc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "lang-mustache-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "percolator-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "parent-join-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "rank-eval-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "transport-1.0.0-alpha2.jar",
          "url": "transport-1.0.0-alpha2.jar",
          "size": 7601,
          "sha512": "eb429ebdc6e2c42b9b414b3c0b18fcc88e00567fe0896227b817f68a935dd1db35f60a1c13d3807fb259a1bb82fa79bc30ff187ebf7800bdd2bdf9ef78e183a9",
          "sha256": "18ae3506bf4e9b2d119768c13a15d3f37af3ddfc2b9d3bc96ecdfc13b98183db",
          "sha1": "44ffc6a47ff0c240339d43b6ab896394e34bb276",
          "md5": "a611ba8fa03872c8b6adfad50a760dc6"
        }
      ]
    }
  ]
}
