{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.test",
    "module": "test-delayed-aggs",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-delayed-aggs-1.0.0-alpha1.jar",
          "url": "test-delayed-aggs-1.0.0-alpha1.jar",
          "size": 10692,
          "sha512": "2a5b361fbc1f73d291a395bda8657a75c48b1a5e5c54734c1bc46882ea4dab9faafbd5fa7711197a30b49c3ea19963afa4e2b1059c6274d0ba08b06b9b592815",
          "sha256": "67a78fccd9a11b4f61d2fa4b818bfdd7479aca2a8f95418767ca2f078c992380",
          "sha1": "91490cc20c6303a8d7abd72f3803c10cfb9e396b",
          "md5": "9f6a439ae10aa86c8c102d84b17e0108"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-delayed-aggs-1.0.0-alpha1.jar",
          "url": "test-delayed-aggs-1.0.0-alpha1.jar",
          "size": 10692,
          "sha512": "2a5b361fbc1f73d291a395bda8657a75c48b1a5e5c54734c1bc46882ea4dab9faafbd5fa7711197a30b49c3ea19963afa4e2b1059c6274d0ba08b06b9b592815",
          "sha256": "67a78fccd9a11b4f61d2fa4b818bfdd7479aca2a8f95418767ca2f078c992380",
          "sha1": "91490cc20c6303a8d7abd72f3803c10cfb9e396b",
          "md5": "9f6a439ae10aa86c8c102d84b17e0108"
        }
      ]
    }
  ]
}
