{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-launchers",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-launchers-1.0.0-alpha2.jar",
          "url": "opensearch-launchers-1.0.0-alpha2.jar",
          "size": 21111,
          "sha512": "9a216698841985ddd469362b0035799e65f0776f988918d7ce78aaa433ceb81760acb90e3c6fac79e4a0cf8edd5685806c787890fcf9a096056ec3f67081b3c1",
          "sha256": "362f4c7667bd47fb011fc1969c4de4f6a91cb939dcfe6d0f22719e739e61f6f3",
          "sha1": "806452a4ac14d5d48f86c441984a4e18b9ffdd1c",
          "md5": "a8fcf6103593da2fc9a0dfb69c6c31a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-launchers-1.0.0-alpha2.jar",
          "url": "opensearch-launchers-1.0.0-alpha2.jar",
          "size": 21111,
          "sha512": "9a216698841985ddd469362b0035799e65f0776f988918d7ce78aaa433ceb81760acb90e3c6fac79e4a0cf8edd5685806c787890fcf9a096056ec3f67081b3c1",
          "sha256": "362f4c7667bd47fb011fc1969c4de4f6a91cb939dcfe6d0f22719e739e61f6f3",
          "sha1": "806452a4ac14d5d48f86c441984a4e18b9ffdd1c",
          "md5": "a8fcf6103593da2fc9a0dfb69c6c31a6"
        }
      ]
    }
  ]
}
