{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-grok",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jruby.joni",
          "module": "joni",
          "version": {
            "requires": "2.1.29"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jruby.jcodings",
          "module": "jcodings",
          "version": {
            "requires": "1.0.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-grok-1.0.0-alpha2.jar",
          "url": "opensearch-grok-1.0.0-alpha2.jar",
          "size": 48253,
          "sha512": "1f532a6f6b4b31e976924ba24b7ca5bc680a46c9660bf079a4a762466e1a8bd2546f297b6a3ed825b32b7692fef6da029068a5c719967f95ef2b06c5260f2d5c",
          "sha256": "3684f670292f8ead8825f36f57a9c920aaf831be533e8595a659a40344c1c018",
          "sha1": "cde2b60b6cdce22f60d4d01ad0fed9625f3d5aa9",
          "md5": "28d7463984676788f7384f0329aafefe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jruby.joni",
          "module": "joni",
          "version": {
            "requires": "2.1.29"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jruby.jcodings",
          "module": "jcodings",
          "version": {
            "requires": "1.0.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-grok-1.0.0-alpha2.jar",
          "url": "opensearch-grok-1.0.0-alpha2.jar",
          "size": 48253,
          "sha512": "1f532a6f6b4b31e976924ba24b7ca5bc680a46c9660bf079a4a762466e1a8bd2546f297b6a3ed825b32b7692fef6da029068a5c719967f95ef2b06c5260f2d5c",
          "sha256": "3684f670292f8ead8825f36f57a9c920aaf831be533e8595a659a40344c1c018",
          "sha1": "cde2b60b6cdce22f60d4d01ad0fed9625f3d5aa9",
          "md5": "28d7463984676788f7384f0329aafefe"
        }
      ]
    }
  ]
}
