{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-cli",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-cli-1.0.0-alpha2.jar",
          "url": "opensearch-cli-1.0.0-alpha2.jar",
          "size": 17955,
          "sha512": "dd21f2272a00f32be7fbeca416f0df3e100925bf08c3ac73566976334dab453e39254e54c6a95057f2f854bc9863568cf98ab981dee118dfa58dac3ca681ba20",
          "sha256": "f6967762c27a7385e420f828e53fabadcb15230ce0dfb981fb0659ecb1aeb554",
          "sha1": "ec0e126671afee156f49f7317f12b998819e2dd0",
          "md5": "2fe5a4cc4c701c14ab6a90f0863eb1bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-cli-1.0.0-alpha2.jar",
          "url": "opensearch-cli-1.0.0-alpha2.jar",
          "size": 17955,
          "sha512": "dd21f2272a00f32be7fbeca416f0df3e100925bf08c3ac73566976334dab453e39254e54c6a95057f2f854bc9863568cf98ab981dee118dfa58dac3ca681ba20",
          "sha256": "f6967762c27a7385e420f828e53fabadcb15230ce0dfb981fb0659ecb1aeb554",
          "sha1": "ec0e126671afee156f49f7317f12b998819e2dd0",
          "md5": "2fe5a4cc4c701c14ab6a90f0863eb1bb"
        }
      ]
    }
  ]
}
