{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "rest-api-spec",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rest-api-spec-1.0.0-alpha1.jar",
          "url": "rest-api-spec-1.0.0-alpha1.jar",
          "size": 404965,
          "sha512": "9d788d18c1b70c67d66eebc4429fb5dc1ad956b1087d80bb635296dd7e846f4015e2b6a29abf04f6baa89bffc29caa8bd19c07952dfe31c43b3df05d2eb933f6",
          "sha256": "708188048f41c856eb84ae538ea93b55f20a8a4300a0e226c11521e51405907f",
          "sha1": "446b550cf28cea54e28c327a32f43fa411a4333b",
          "md5": "9e4f216d74a4168270d015322eb3ba05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rest-api-spec-1.0.0-alpha1.jar",
          "url": "rest-api-spec-1.0.0-alpha1.jar",
          "size": 404965,
          "sha512": "9d788d18c1b70c67d66eebc4429fb5dc1ad956b1087d80bb635296dd7e846f4015e2b6a29abf04f6baa89bffc29caa8bd19c07952dfe31c43b3df05d2eb933f6",
          "sha256": "708188048f41c856eb84ae538ea93b55f20a8a4300a0e226c11521e51405907f",
          "sha1": "446b550cf28cea54e28c327a32f43fa411a4333b",
          "md5": "9e4f216d74a4168270d015322eb3ba05"
        }
      ]
    }
  ]
}
