{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "custom-settings",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "custom-settings-1.0.0-beta1.jar",
          "url": "custom-settings-1.0.0-beta1.jar",
          "size": 9890,
          "sha512": "1a6e0fdb92cfe493547601f2121bee2f5c16a598f53af81e8e83322f140e092ad2176629bb6f16cc6c38ba960fb0532a931ecba919ea8d8d94908606c1232ab1",
          "sha256": "e0b9e8b10456d7bc9405e0dac37cf8135a49e35dc563b06407e5c8f41a1e075a",
          "sha1": "0638fffcb84b0299771391c4cec248b4885728f1",
          "md5": "f6caec36c8ae5523ba6b69942b82d1a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-settings-1.0.0-beta1.jar",
          "url": "custom-settings-1.0.0-beta1.jar",
          "size": 9890,
          "sha512": "1a6e0fdb92cfe493547601f2121bee2f5c16a598f53af81e8e83322f140e092ad2176629bb6f16cc6c38ba960fb0532a931ecba919ea8d8d94908606c1232ab1",
          "sha256": "e0b9e8b10456d7bc9405e0dac37cf8135a49e35dc563b06407e5c8f41a1e075a",
          "sha1": "0638fffcb84b0299771391c4cec248b4885728f1",
          "md5": "f6caec36c8ae5523ba6b69942b82d1a1"
        }
      ]
    }
  ]
}
