{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "painless-whitelist",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "painless-whitelist-1.0.0-alpha2.jar",
          "url": "painless-whitelist-1.0.0-alpha2.jar",
          "size": 12477,
          "sha512": "ac4cc71d4e2be204db56230689b36e234e5a69c29995fab473c2bb0c439804060ceef8ddd8e0eda961a6ec95ba12ee9f3f3c857f90df5243509e93d89b968297",
          "sha256": "f2837e029aef8b358c18ca76c122299902e12360993f7acee189933d6f48b78d",
          "sha1": "977fab6414d009b84a0b0e56c1e2afa0d8c62b7d",
          "md5": "753eba2710ba0ed8cf9aed5cc075992e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "painless-whitelist-1.0.0-alpha2.jar",
          "url": "painless-whitelist-1.0.0-alpha2.jar",
          "size": 12477,
          "sha512": "ac4cc71d4e2be204db56230689b36e234e5a69c29995fab473c2bb0c439804060ceef8ddd8e0eda961a6ec95ba12ee9f3f3c857f90df5243509e93d89b968297",
          "sha256": "f2837e029aef8b358c18ca76c122299902e12360993f7acee189933d6f48b78d",
          "sha1": "977fab6414d009b84a0b0e56c1e2afa0d8c62b7d",
          "md5": "753eba2710ba0ed8cf9aed5cc075992e"
        }
      ]
    }
  ]
}
