{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "keystore-cli",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "keystore-cli-1.0.0-alpha2.jar",
          "url": "keystore-cli-1.0.0-alpha2.jar",
          "size": 16228,
          "sha512": "860438b7601ae89305c80964cebf19d093951e9f995f0c00e312e188afc3280326c5931ee9fe802c0eefaf12d0169b7b1f7dfcbe092d7ac1ec2d70b74abe1e70",
          "sha256": "b652950323a6c698f814dc9e66dde08954a7c0ad957b115a503a8a7687347e7b",
          "sha1": "804f8017103b9c83d60635bb64a60b9f2c2f9c01",
          "md5": "3d0a87dcaca4511628ff40a38125fdce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "keystore-cli-1.0.0-alpha2.jar",
          "url": "keystore-cli-1.0.0-alpha2.jar",
          "size": 16228,
          "sha512": "860438b7601ae89305c80964cebf19d093951e9f995f0c00e312e188afc3280326c5931ee9fe802c0eefaf12d0169b7b1f7dfcbe092d7ac1ec2d70b74abe1e70",
          "sha256": "b652950323a6c698f814dc9e66dde08954a7c0ad957b115a503a8a7687347e7b",
          "sha1": "804f8017103b9c83d60635bb64a60b9f2c2f9c01",
          "md5": "3d0a87dcaca4511628ff40a38125fdce"
        }
      ]
    }
  ]
}
