{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "percolator-client",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "percolator-client-1.0.0-alpha1.jar",
          "url": "percolator-client-1.0.0-alpha1.jar",
          "size": 77580,
          "sha512": "ba8504fe6a53e09256f68afbc0564f897946d7cda54fd118c881903c3b5742ac083de03a7e002e49e9c5f0f4524e4d120dce8790d25e840c13e9e2b61eb02255",
          "sha256": "525ae3f6cef33f1447dcbd9dccbc92d354666c1663ad9992cf5d8139960eb0e1",
          "sha1": "092468257b55fbf129480ea884a85a28b4391d6d",
          "md5": "c2b9efd00dc5209265ec06daac293a64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "percolator-client-1.0.0-alpha1.jar",
          "url": "percolator-client-1.0.0-alpha1.jar",
          "size": 77580,
          "sha512": "ba8504fe6a53e09256f68afbc0564f897946d7cda54fd118c881903c3b5742ac083de03a7e002e49e9c5f0f4524e4d120dce8790d25e840c13e9e2b61eb02255",
          "sha256": "525ae3f6cef33f1447dcbd9dccbc92d354666c1663ad9992cf5d8139960eb0e1",
          "sha1": "092468257b55fbf129480ea884a85a28b4391d6d",
          "md5": "c2b9efd00dc5209265ec06daac293a64"
        }
      ]
    }
  ]
}
