{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.test",
    "module": "test-delayed-aggs",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-delayed-aggs-1.0.0-alpha2.jar",
          "url": "test-delayed-aggs-1.0.0-alpha2.jar",
          "size": 10691,
          "sha512": "7526efbca6bb86a75a4a45732a03e37fa30c63cc886d2a5c0f9da5c69ad2a977d9510a7ccce7c272c82b1c750e970840feca74b49f8503279c52654b37e62942",
          "sha256": "5cdb58b72e201e5e9d3af9f676703d23e7ee9b365fd500e4c81c6313bf055299",
          "sha1": "16fbe57cfb853f735e696634b57632463266068e",
          "md5": "28cd5f1454a0ca05ae400f32a55a4baa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-delayed-aggs-1.0.0-alpha2.jar",
          "url": "test-delayed-aggs-1.0.0-alpha2.jar",
          "size": 10691,
          "sha512": "7526efbca6bb86a75a4a45732a03e37fa30c63cc886d2a5c0f9da5c69ad2a977d9510a7ccce7c272c82b1c750e970840feca74b49f8503279c52654b37e62942",
          "sha256": "5cdb58b72e201e5e9d3af9f676703d23e7ee9b365fd500e4c81c6313bf055299",
          "sha1": "16fbe57cfb853f735e696634b57632463266068e",
          "md5": "28cd5f1454a0ca05ae400f32a55a4baa"
        }
      ]
    }
  ]
}
