pipeline:
source:
  file:
    path: "/full/path/to/logs_json.log"
    record_type: "event"
    format: "json"
processor:
  - split_string:
      entries:
        - source: "message"
          delimiter: ","
sink:
  - stdout: