services:
  data-prepper:
    restart: unless-stopped
    image: docker.io/opensearchproject/data-prepper:2.16.0
    volumes:
      - ./pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ../data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
      - opensearch-config:/usr/share/opensearch-test/:ro
    ports:
      - "21890:21890"
    networks:
      - my_network
    depends_on:
      - opensearch

  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.158.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    working_dir: "/project"
    volumes:
      - ${PWD}/:/project
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "14250:14250"
    depends_on:
      - data-prepper
    networks:
      - my_network

  jaeger-hot-rod:
    image: docker.io/jaegertracing/example-hotrod:2.20.0
    command: [ "all" ]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    ports:
      - "8080-8083:8080-8083"
    depends_on:
      - otel-collector
    networks:
      - my_network

  opensearch:
    container_name: node-0.example.com
    image: docker.io/opensearchproject/opensearch:3.8.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=yourStrongPassword123!
    volumes:
      - opensearch-config:/usr/share/opensearch/config/
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    networks:
      - my_network
  dashboards:
    image: docker.io/opensearchproject/opensearch-dashboards:3.8.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://node-0.example.com:9200"]'
    depends_on:
      - opensearch
    networks:
      - my_network
networks:
  my_network:
volumes:
  opensearch-config:
