receivers:
  otlp:
    protocols:
      http:
        endpoint: otel-collector:4318

exporters:
  otlp_grpc/data-prepper:
    endpoint: data-prepper:21890
    tls:
      insecure: true
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp_grpc/data-prepper]
