{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "parent-join-client",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parent-join-client-1.0.0-alpha2.jar",
          "url": "parent-join-client-1.0.0-alpha2.jar",
          "size": 87348,
          "sha512": "b27e9bec7f44be31af83434b3ae9235b2389801bc5c36eec70357542bdba006139e5da60728e725272d16a367c30ba08966823eeef8e409266a1c4095b5451ec",
          "sha256": "93e6c24dc6eaabad8fd9511d6776a9ec4633aa5f499887440a0a57ec5683dbda",
          "sha1": "ab3364d822f0e8365b0bcb60109e055e1c2bc25b",
          "md5": "4dc8438e90982c14b058a7a974104cdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-join-client-1.0.0-alpha2.jar",
          "url": "parent-join-client-1.0.0-alpha2.jar",
          "size": 87348,
          "sha512": "b27e9bec7f44be31af83434b3ae9235b2389801bc5c36eec70357542bdba006139e5da60728e725272d16a367c30ba08966823eeef8e409266a1c4095b5451ec",
          "sha256": "93e6c24dc6eaabad8fd9511d6776a9ec4633aa5f499887440a0a57ec5683dbda",
          "sha1": "ab3364d822f0e8365b0bcb60109e055e1c2bc25b",
          "md5": "4dc8438e90982c14b058a7a974104cdf"
        }
      ]
    }
  ]
}
