{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-ssl-config",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-ssl-config-1.0.0-alpha2.jar",
          "url": "opensearch-ssl-config-1.0.0-alpha2.jar",
          "size": 67008,
          "sha512": "4f2795ef4b26342014825c0fa05e7aa023d281236278752deb179fce54bf8f2edf01d3afc11201a7cddd4ff58c8e2b5f44064a52cce65e469d8f0cd4f0803cd1",
          "sha256": "913ae19b049d07fe3ecc13447e3a67d32d7201ef3a675bc064be190452215145",
          "sha1": "88f366fbbf4e0a44e01c7fd86b52ae72b203c7b0",
          "md5": "81aba6721d5e6518d03794af0eef92f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-ssl-config-1.0.0-alpha2.jar",
          "url": "opensearch-ssl-config-1.0.0-alpha2.jar",
          "size": 67008,
          "sha512": "4f2795ef4b26342014825c0fa05e7aa023d281236278752deb179fce54bf8f2edf01d3afc11201a7cddd4ff58c8e2b5f44064a52cce65e469d8f0cd4f0803cd1",
          "sha256": "913ae19b049d07fe3ecc13447e3a67d32d7201ef3a675bc064be190452215145",
          "sha1": "88f366fbbf4e0a44e01c7fd86b52ae72b203c7b0",
          "md5": "81aba6721d5e6518d03794af0eef92f9"
        }
      ]
    }
  ]
}
