{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "lang-expression",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-expressions",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.1-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lang-expression-1.0.0-alpha1.jar",
          "url": "lang-expression-1.0.0-alpha1.jar",
          "size": 65140,
          "sha512": "bce69edd025a8c76fb4240cb673c66f64ef29966ec868253676f1e18c0ae7bba7cf2e75d80b883072e59425e509c98b26c22126720e2b13f932847b3ee8817e5",
          "sha256": "b3a4fe9d53249dc195446e2ec43b60c8b577b2e0c89009d509d8dd3bcb0fe2e8",
          "sha1": "9def4ff785ca9bbaadbf111807bc61e2c1e66c0f",
          "md5": "147d5881a6b1129b20c9088c4bb0a485"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-expressions",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.1-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lang-expression-1.0.0-alpha1.jar",
          "url": "lang-expression-1.0.0-alpha1.jar",
          "size": 65140,
          "sha512": "bce69edd025a8c76fb4240cb673c66f64ef29966ec868253676f1e18c0ae7bba7cf2e75d80b883072e59425e509c98b26c22126720e2b13f932847b3ee8817e5",
          "sha256": "b3a4fe9d53249dc195446e2ec43b60c8b577b2e0c89009d509d8dd3bcb0fe2e8",
          "sha1": "9def4ff785ca9bbaadbf111807bc61e2c1e66c0f",
          "md5": "147d5881a6b1129b20c9088c4bb0a485"
        }
      ]
    }
  ]
}
