{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "example-rescore",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "example-rescore-1.0.0-beta1.jar",
          "url": "example-rescore-1.0.0-beta1.jar",
          "size": 12819,
          "sha512": "29848145614e713efca73a8c68c7b7601396c369e76bb0f722dae8e77badca308a2aff8b69158d30683b91222cc70b37858aeebdb60ad166bc57382afce32e77",
          "sha256": "1ad2ee219d02f7b985711ebb8f156812c17bbddbb7842e627eaedf324bd9d538",
          "sha1": "b5e5b13b28c6c099deb9d7cc616aa1821f7a21ed",
          "md5": "4c940e30b93b92cec51d6c05150358a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "example-rescore-1.0.0-beta1.jar",
          "url": "example-rescore-1.0.0-beta1.jar",
          "size": 12819,
          "sha512": "29848145614e713efca73a8c68c7b7601396c369e76bb0f722dae8e77badca308a2aff8b69158d30683b91222cc70b37858aeebdb60ad166bc57382afce32e77",
          "sha256": "1ad2ee219d02f7b985711ebb8f156812c17bbddbb7842e627eaedf324bd9d538",
          "sha1": "b5e5b13b28c6c099deb9d7cc616aa1821f7a21ed",
          "md5": "4c940e30b93b92cec51d6c05150358a1"
        }
      ]
    }
  ]
}
