FROM amazon/opendistro-for-elasticsearch-kibana:1.10.1
RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/joshuali925/trace_analytics/releases/download/test-test/trace_analytics-0.0.6.zip
