FROM amazon/opendistro-for-elasticsearch-kibana:1.10.1
RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/joshuali925/trace_analytics/releases/download/test-test/opendistro-trace-analytics-0.0.5.zip
