{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "example-rescore",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "example-rescore-1.0.0-alpha1.jar",
          "url": "example-rescore-1.0.0-alpha1.jar",
          "size": 12821,
          "sha512": "4869960540646561f2d80e3b2df7da05fbf92927959fe14b19c32988ab5b62b4071e8b10cccea3366363eafc8a6975ce926f920fbb9caa7919b1744100fcc819",
          "sha256": "cc388cd0ea2878fa5f5a1c62e54369e014758437cd9d0880a3f5b0afb04961ea",
          "sha1": "2d2c928bf1ae764e6841f4e885940650f16c669d",
          "md5": "5b40b1b6b472bb9fab47b8f5670e4214"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "example-rescore-1.0.0-alpha1.jar",
          "url": "example-rescore-1.0.0-alpha1.jar",
          "size": 12821,
          "sha512": "4869960540646561f2d80e3b2df7da05fbf92927959fe14b19c32988ab5b62b4071e8b10cccea3366363eafc8a6975ce926f920fbb9caa7919b1744100fcc819",
          "sha256": "cc388cd0ea2878fa5f5a1c62e54369e014758437cd9d0880a3f5b0afb04961ea",
          "sha1": "2d2c928bf1ae764e6841f4e885940650f16c669d",
          "md5": "5b40b1b6b472bb9fab47b8f5670e4214"
        }
      ]
    }
  ]
}
