{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "opensearch-dashboards",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-dashboards-1.0.0-alpha2.jar",
          "url": "opensearch-dashboards-1.0.0-alpha2.jar",
          "size": 9176,
          "sha512": "914fec266512aa176e2ba98c04320aa4a79cf762d9291a0e3e6b1c93606fe6b98570f44be87d3dc259294ecb12cd732a2869720ba5d6e78ab5ea94c8962d8308",
          "sha256": "fc037b70636e128ae7ca2a5e2db3986c26a501b63d5a321f2bc32cdfd563095f",
          "sha1": "fd1803081ba706ebb3cd28211d1c008a97807c09",
          "md5": "14fd2138ffc52a01bcd4b5dd52bc7144"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-dashboards-1.0.0-alpha2.jar",
          "url": "opensearch-dashboards-1.0.0-alpha2.jar",
          "size": 9176,
          "sha512": "914fec266512aa176e2ba98c04320aa4a79cf762d9291a0e3e6b1c93606fe6b98570f44be87d3dc259294ecb12cd732a2869720ba5d6e78ab5ea94c8962d8308",
          "sha256": "fc037b70636e128ae7ca2a5e2db3986c26a501b63d5a321f2bc32cdfd563095f",
          "sha1": "fd1803081ba706ebb3cd28211d1c008a97807c09",
          "md5": "14fd2138ffc52a01bcd4b5dd52bc7144"
        }
      ]
    }
  ]
}
