{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-annotated-text",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-annotated-text-1.0.0-beta1.jar",
          "url": "mapper-annotated-text-1.0.0-beta1.jar",
          "size": 32815,
          "sha512": "5b5bdb641b8a66b852a6771b474839df259f307676dc3b2f23540c2622fa951a9e1a86296b2ffbd3109d241f5c1be3b021cb0689336330e072cb786eaff083f9",
          "sha256": "9c252b3cc482aff5056e450b43f3cdb8388830821414e5066661f00140f090d3",
          "sha1": "6be03f2e1a957597493749bcbac68de04181478a",
          "md5": "65dec99a27abd20423a29fdfd1c81eaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-annotated-text-1.0.0-beta1.jar",
          "url": "mapper-annotated-text-1.0.0-beta1.jar",
          "size": 32815,
          "sha512": "5b5bdb641b8a66b852a6771b474839df259f307676dc3b2f23540c2622fa951a9e1a86296b2ffbd3109d241f5c1be3b021cb0689336330e072cb786eaff083f9",
          "sha256": "9c252b3cc482aff5056e450b43f3cdb8388830821414e5066661f00140f090d3",
          "sha1": "6be03f2e1a957597493749bcbac68de04181478a",
          "md5": "65dec99a27abd20423a29fdfd1c81eaf"
        }
      ]
    }
  ]
}
