{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-geoip",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.maxmind.geoip2",
          "module": "geoip2",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.maxmind.db",
          "module": "maxmind-db",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ingest-geoip-1.0.0-beta1.jar",
          "url": "ingest-geoip-1.0.0-beta1.jar",
          "size": 27519,
          "sha512": "c141e968fb1ee862d8f5eda6ad898c73e86600baeae61bf0124db41d4a5176c53cb38e425ff88a46a46705ac7f79991a15ac32b774bf572a1735c9034fcbd995",
          "sha256": "854910658fa48fbe487225cb60f81853ac17f94c2c318b8de5a7f81c735257d3",
          "sha1": "8756292f7309f3111c44596917843649595d56af",
          "md5": "274ab114cfc4a479e9c77ec6d894ac03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.maxmind.geoip2",
          "module": "geoip2",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.maxmind.db",
          "module": "maxmind-db",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ingest-geoip-1.0.0-beta1.jar",
          "url": "ingest-geoip-1.0.0-beta1.jar",
          "size": 27519,
          "sha512": "c141e968fb1ee862d8f5eda6ad898c73e86600baeae61bf0124db41d4a5176c53cb38e425ff88a46a46705ac7f79991a15ac32b774bf572a1735c9034fcbd995",
          "sha256": "854910658fa48fbe487225cb60f81853ac17f94c2c318b8de5a7f81c735257d3",
          "sha1": "8756292f7309f3111c44596917843649595d56af",
          "md5": "274ab114cfc4a479e9c77ec6d894ac03"
        }
      ]
    }
  ]
}
