{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.client",
    "module": "opensearch-rest-client",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpasyncclient",
          "version": {
            "requires": "4.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore-nio",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-rest-client-1.0.0-beta1.jar",
          "url": "opensearch-rest-client-1.0.0-beta1.jar",
          "size": 65888,
          "sha512": "e17fd4aa9bc9b65c310841c83730bdc554b6eac27a5818af05a197716ed2047f06ed97230311aa802abe4adc716668406849ab4715e2a9a9baeec74f3f1cf7d9",
          "sha256": "ed9acbdd84c5e872b21b62fc10c0b1f335fcbd9bf203906074f1c5634fcc1678",
          "sha1": "e3e54c5f555120dc185ebfc04c297ccd5fa89573",
          "md5": "39c9cb471e106536c96217432e853fe0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpasyncclient",
          "version": {
            "requires": "4.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore-nio",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-rest-client-1.0.0-beta1.jar",
          "url": "opensearch-rest-client-1.0.0-beta1.jar",
          "size": 65888,
          "sha512": "e17fd4aa9bc9b65c310841c83730bdc554b6eac27a5818af05a197716ed2047f06ed97230311aa802abe4adc716668406849ab4715e2a9a9baeec74f3f1cf7d9",
          "sha256": "ed9acbdd84c5e872b21b62fc10c0b1f335fcbd9bf203906074f1c5634fcc1678",
          "sha1": "e3e54c5f555120dc185ebfc04c297ccd5fa89573",
          "md5": "39c9cb471e106536c96217432e853fe0"
        }
      ]
    }
  ]
}
