{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "custom-significance-heuristic",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "custom-significance-heuristic-1.0.0-alpha2.jar",
          "url": "custom-significance-heuristic-1.0.0-alpha2.jar",
          "size": 7936,
          "sha512": "9ab4a69996beb2699ee6cb8a9191aacae128ca5dcd8eed5f7c62c2f185b6e4a4ae63197482b7b58d403b5b62ae124a5db184be61b3024bdd597fbf87b323115d",
          "sha256": "3f6d88c398a043281d4780ab244552a234ed248bc00185604cc02b43c70299b4",
          "sha1": "0b8ad1ad7bababc4068e7897bb7ac2734714245c",
          "md5": "172fc70635ad8e87c420407c1c0942fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-significance-heuristic-1.0.0-alpha2.jar",
          "url": "custom-significance-heuristic-1.0.0-alpha2.jar",
          "size": 7936,
          "sha512": "9ab4a69996beb2699ee6cb8a9191aacae128ca5dcd8eed5f7c62c2f185b6e4a4ae63197482b7b58d403b5b62ae124a5db184be61b3024bdd597fbf87b323115d",
          "sha256": "3f6d88c398a043281d4780ab244552a234ed248bc00185604cc02b43c70299b4",
          "sha1": "0b8ad1ad7bababc4068e7897bb7ac2734714245c",
          "md5": "172fc70635ad8e87c420407c1c0942fa"
        }
      ]
    }
  ]
}
