{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-secure-sm",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-secure-sm-1.0.0-alpha1.jar",
          "url": "opensearch-secure-sm-1.0.0-alpha1.jar",
          "size": 10944,
          "sha512": "82be945e7febf7caae61684187e1856122f04f415f69de47f52cbc698e52654c636122dc5bbc4f13fc1a8b242a8022708244dd4f5af8744e19e46671ec497417",
          "sha256": "1d07556f462f7995d9962830b69bbeaa9a9767fee245198ddac9edc048a9380e",
          "sha1": "6786ba89e9edb08e50380aa1065d62b71763ed8d",
          "md5": "81b3feffddce142f40fb445b1058b05d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-secure-sm-1.0.0-alpha1.jar",
          "url": "opensearch-secure-sm-1.0.0-alpha1.jar",
          "size": 10944,
          "sha512": "82be945e7febf7caae61684187e1856122f04f415f69de47f52cbc698e52654c636122dc5bbc4f13fc1a8b242a8022708244dd4f5af8744e19e46671ec497417",
          "sha256": "1d07556f462f7995d9962830b69bbeaa9a9767fee245198ddac9edc048a9380e",
          "sha1": "6786ba89e9edb08e50380aa1065d62b71763ed8d",
          "md5": "81b3feffddce142f40fb445b1058b05d"
        }
      ]
    }
  ]
}
