{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "repository-url",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "repository-url-1.0.0-alpha1.jar",
          "url": "repository-url-1.0.0-alpha1.jar",
          "size": 15013,
          "sha512": "f61d722898d8b6cb1ba2f239548f22090cc6374514fe2b5ec42bb9d59d42701bb8af86ddfa881f82df790f05e5ba20080fbd82ebfc22e69345f02f2e81254695",
          "sha256": "aecac4cf8e056f529b66cbb00ae4ff350b65abcd3008fc2e6a9ea62e5729c601",
          "sha1": "e7b57880052e9f7a207652167ac9375995ca09bb",
          "md5": "7d5c2d2fa22b4d2c72ff32dd2f3c2fa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "repository-url-1.0.0-alpha1.jar",
          "url": "repository-url-1.0.0-alpha1.jar",
          "size": 15013,
          "sha512": "f61d722898d8b6cb1ba2f239548f22090cc6374514fe2b5ec42bb9d59d42701bb8af86ddfa881f82df790f05e5ba20080fbd82ebfc22e69345f02f2e81254695",
          "sha256": "aecac4cf8e056f529b66cbb00ae4ff350b65abcd3008fc2e6a9ea62e5729c601",
          "sha1": "e7b57880052e9f7a207652167ac9375995ca09bb",
          "md5": "7d5c2d2fa22b4d2c72ff32dd2f3c2fa4"
        }
      ]
    }
  ]
}
