{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-smartcn",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-smartcn",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-smartcn-1.0.0-alpha2.jar",
          "url": "analysis-smartcn-1.0.0-alpha2.jar",
          "size": 10598,
          "sha512": "afee193153e2ed33ed3a0e0b733737322750de4fd668430b3afd752218d1125882287eee0f78ac81d62722d635b3777969b76a9c9feb700fedc7b1abe4fff449",
          "sha256": "1f8678cb25ffdcf6071fb19bad972d9a2ad3545acccfea4e6b0104c6731c88ef",
          "sha1": "72431892cb2a8013c336accda3ad5dc4e3d65df8",
          "md5": "ff52342561d93c73397529ebec729cfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-smartcn",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-smartcn-1.0.0-alpha2.jar",
          "url": "analysis-smartcn-1.0.0-alpha2.jar",
          "size": 10598,
          "sha512": "afee193153e2ed33ed3a0e0b733737322750de4fd668430b3afd752218d1125882287eee0f78ac81d62722d635b3777969b76a9c9feb700fedc7b1abe4fff449",
          "sha256": "1f8678cb25ffdcf6071fb19bad972d9a2ad3545acccfea4e6b0104c6731c88ef",
          "sha1": "72431892cb2a8013c336accda3ad5dc4e3d65df8",
          "md5": "ff52342561d93c73397529ebec729cfa"
        }
      ]
    }
  ]
}
