{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-geoip",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.maxmind.geoip2",
          "module": "geoip2",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.maxmind.db",
          "module": "maxmind-db",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ingest-geoip-1.0.0-alpha2.jar",
          "url": "ingest-geoip-1.0.0-alpha2.jar",
          "size": 27520,
          "sha512": "bdf4392ab727f61d7e976d94ebe3323981cfd0f4c7a59c372a7df075129baab7624cc08ef80963d40ab6d829672badb2aa55d8b2fd23a09f57d26bf9117aca19",
          "sha256": "5bde70d8798ddca9b83f1d718839106f5eb5e189a82ce5368a4f478fe8b9c1d8",
          "sha1": "d8744419e1e0fedac320027d920a93e182db4fba",
          "md5": "0621865f9937a4379e5297f309587b51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.maxmind.geoip2",
          "module": "geoip2",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.maxmind.db",
          "module": "maxmind-db",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ingest-geoip-1.0.0-alpha2.jar",
          "url": "ingest-geoip-1.0.0-alpha2.jar",
          "size": 27520,
          "sha512": "bdf4392ab727f61d7e976d94ebe3323981cfd0f4c7a59c372a7df075129baab7624cc08ef80963d40ab6d829672badb2aa55d8b2fd23a09f57d26bf9117aca19",
          "sha256": "5bde70d8798ddca9b83f1d718839106f5eb5e189a82ce5368a4f478fe8b9c1d8",
          "sha1": "d8744419e1e0fedac320027d920a93e182db4fba",
          "md5": "0621865f9937a4379e5297f309587b51"
        }
      ]
    }
  ]
}
