{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "discovery-azure-classic",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-svc-mgmt-compute",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-core",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-1.2-api",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.mail",
          "module": "mail",
          "version": {
            "requires": "1.4.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-client",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-core",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-json",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jettison",
          "module": "jettison",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.2.3-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-core-asl",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-mapper-asl",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-jaxrs",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-xc",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "discovery-azure-classic-1.0.0-alpha1.jar",
          "url": "discovery-azure-classic-1.0.0-alpha1.jar",
          "size": 23604,
          "sha512": "fc8399f822f15004df55e4354da3cec31a435dc2fb90b2e7d9cc0ccf39a3ac97ef6a4ee4805de62648de8af9f67c601ae7569e3b446a29dcd1d1856151d3b08f",
          "sha256": "330174cd56470eddbdcc7fb6cfdaf25463c38d3dd9e9cd9d6c69f223a154e721",
          "sha1": "56e7377f076d05f256458f236d0cfcb6b7867681",
          "md5": "f325b857959a41bd5777c99172299c63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-svc-mgmt-compute",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-core",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-1.2-api",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.mail",
          "module": "mail",
          "version": {
            "requires": "1.4.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-client",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-core",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-json",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jettison",
          "module": "jettison",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.2.3-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-core-asl",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-mapper-asl",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-jaxrs",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-xc",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "discovery-azure-classic-1.0.0-alpha1.jar",
          "url": "discovery-azure-classic-1.0.0-alpha1.jar",
          "size": 23604,
          "sha512": "fc8399f822f15004df55e4354da3cec31a435dc2fb90b2e7d9cc0ccf39a3ac97ef6a4ee4805de62648de8af9f67c601ae7569e3b446a29dcd1d1856151d3b08f",
          "sha256": "330174cd56470eddbdcc7fb6cfdaf25463c38d3dd9e9cd9d6c69f223a154e721",
          "sha1": "56e7377f076d05f256458f236d0cfcb6b7867681",
          "md5": "f325b857959a41bd5777c99172299c63"
        }
      ]
    }
  ]
}
