{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-kuromoji",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-kuromoji",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-kuromoji-1.0.0-alpha1.jar",
          "url": "analysis-kuromoji-1.0.0-alpha1.jar",
          "size": 17874,
          "sha512": "3a113178fd06ca01fc5bd8e43050d0791e5d4dc9368f93105b8369a89ae29b16ef686d4eab4d7a64dd5dd56563a70148b594957540b559acc4e456d6e7bd579b",
          "sha256": "2a4947307a8ec25a6a8c4a172772a4790b2541941aed6d5217d199726bbfb2b6",
          "sha1": "42f991bbaadb0a3912085e25cce77c18d55c789d",
          "md5": "38db3412d74a009268513a6ba3b3af41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-kuromoji",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-kuromoji-1.0.0-alpha1.jar",
          "url": "analysis-kuromoji-1.0.0-alpha1.jar",
          "size": 17874,
          "sha512": "3a113178fd06ca01fc5bd8e43050d0791e5d4dc9368f93105b8369a89ae29b16ef686d4eab4d7a64dd5dd56563a70148b594957540b559acc4e456d6e7bd579b",
          "sha256": "2a4947307a8ec25a6a8c4a172772a4790b2541941aed6d5217d199726bbfb2b6",
          "sha1": "42f991bbaadb0a3912085e25cce77c18d55c789d",
          "md5": "38db3412d74a009268513a6ba3b3af41"
        }
      ]
    }
  ]
}
