{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-plugin-classloader",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-plugin-classloader-1.0.0-alpha2.jar",
          "url": "opensearch-plugin-classloader-1.0.0-alpha2.jar",
          "size": 6539,
          "sha512": "ee996a7115cab16adfd5ccedcee92bb2c37d1a3073e0d7bb1bd27da75d32cada09007260efb91e881c0dcfff82a78dbb909d4bf7d457a38d9904e8b6667f4c0a",
          "sha256": "8b2a88b1d6393f66aae2e38506d574d1db37efd1c2b81075a938ef62469602ef",
          "sha1": "ddc27333a43abea948040ce36019c200925ca902",
          "md5": "4dbd6c0488f6f135cd42ca08880360de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-plugin-classloader-1.0.0-alpha2.jar",
          "url": "opensearch-plugin-classloader-1.0.0-alpha2.jar",
          "size": 6539,
          "sha512": "ee996a7115cab16adfd5ccedcee92bb2c37d1a3073e0d7bb1bd27da75d32cada09007260efb91e881c0dcfff82a78dbb909d4bf7d457a38d9904e8b6667f4c0a",
          "sha256": "8b2a88b1d6393f66aae2e38506d574d1db37efd1c2b81075a938ef62469602ef",
          "sha1": "ddc27333a43abea948040ce36019c200925ca902",
          "md5": "4dbd6c0488f6f135cd42ca08880360de"
        }
      ]
    }
  ]
}
