{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "reindex-client",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-ssl-config",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "reindex-client-1.0.0-alpha1.jar",
          "url": "reindex-client-1.0.0-alpha1.jar",
          "size": 115994,
          "sha512": "aed75916a683e37b6226c195a892f5c9de792bf2ea831d775224341d7829614b7f5be8f75ec4ac01aa50ee42b6dbb0ce8614db0217a4cdfc1324063cafbce0d3",
          "sha256": "bfd19a78b169f94a8d5e714071d108ec56326120f4ba36d2cb58f66175b10482",
          "sha1": "5eec21c7aaa3a95a0343b6c2a4db828b0511b3ef",
          "md5": "514a4bded0702548ffacea97e76fa48c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-ssl-config",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "reindex-client-1.0.0-alpha1.jar",
          "url": "reindex-client-1.0.0-alpha1.jar",
          "size": 115994,
          "sha512": "aed75916a683e37b6226c195a892f5c9de792bf2ea831d775224341d7829614b7f5be8f75ec4ac01aa50ee42b6dbb0ce8614db0217a4cdfc1324063cafbce0d3",
          "sha256": "bfd19a78b169f94a8d5e714071d108ec56326120f4ba36d2cb58f66175b10482",
          "sha1": "5eec21c7aaa3a95a0343b6c2a4db828b0511b3ef",
          "md5": "514a4bded0702548ffacea97e76fa48c"
        }
      ]
    }
  ]
}
