{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "keystore-cli",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "keystore-cli-1.0.0-alpha2.jar",
          "url": "keystore-cli-1.0.0-alpha2.jar",
          "size": 16229,
          "sha512": "715b6d18ef7ff4afb0de03c5459e34423bdf4be5aa08f8e4ba1f52a028ea6f964f3eaad5fe05c79efac5bfeae626b006213a000524f81780c232de9ecede8f96",
          "sha256": "f3112855320656789677bfa6a7a52cf3fb3189af0ca87bd1ece63e03d43e7474",
          "sha1": "248a20b4f30c71dc409122fd6b09c7280746e7e1",
          "md5": "b41088dc64344d5a6ac8e7cc3051ced1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "keystore-cli-1.0.0-alpha2.jar",
          "url": "keystore-cli-1.0.0-alpha2.jar",
          "size": 16229,
          "sha512": "715b6d18ef7ff4afb0de03c5459e34423bdf4be5aa08f8e4ba1f52a028ea6f964f3eaad5fe05c79efac5bfeae626b006213a000524f81780c232de9ecede8f96",
          "sha256": "f3112855320656789677bfa6a7a52cf3fb3189af0ca87bd1ece63e03d43e7474",
          "sha1": "248a20b4f30c71dc409122fd6b09c7280746e7e1",
          "md5": "b41088dc64344d5a6ac8e7cc3051ced1"
        }
      ]
    }
  ]
}
