{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-common",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-grok",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-dissect",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "ingest-common-1.0.0-alpha1.jar",
          "url": "ingest-common-1.0.0-alpha1.jar",
          "size": 118977,
          "sha512": "486f41b240b23ad88d6242c1465f98694fb1194a1575ee99f3e2a6ff6b0df8531e3dbafafe828f34d0989ca0a6a9bd37a29024d73dc8b8ee876f0b09bd3b2c50",
          "sha256": "e7b81c0f47c114df2ffdc1aebaed46110a8b2fdd1bff6386a332e5ecb884edf8",
          "sha1": "2763d998fe88d9154079f718803077d9a6e00a2e",
          "md5": "eceb93d2f3a536087575c70391dd6175"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-grok",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-dissect",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "ingest-common-1.0.0-alpha1.jar",
          "url": "ingest-common-1.0.0-alpha1.jar",
          "size": 118977,
          "sha512": "486f41b240b23ad88d6242c1465f98694fb1194a1575ee99f3e2a6ff6b0df8531e3dbafafe828f34d0989ca0a6a9bd37a29024d73dc8b8ee876f0b09bd3b2c50",
          "sha256": "e7b81c0f47c114df2ffdc1aebaed46110a8b2fdd1bff6386a332e5ecb884edf8",
          "sha1": "2763d998fe88d9154079f718803077d9a6e00a2e",
          "md5": "eceb93d2f3a536087575c70391dd6175"
        }
      ]
    }
  ]
}
