{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-plugin-cli",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-fips",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bc-fips",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-plugin-cli-1.0.0-alpha2.jar",
          "url": "opensearch-plugin-cli-1.0.0-alpha2.jar",
          "size": 34681,
          "sha512": "26a96a338e7f1aead8ebe48f679a5d39bdd1d6b63f5d187d7364b8bc4a80374d3695cee3a03c281c833e2fff82ade102ec4a8aa2ce6e5ae02696e29330548758",
          "sha256": "f90173b3c34fa07463db79f86e3309b511b2729d9a2510f234621775946bdbb7",
          "sha1": "e4efc406baae991cd1203f940c6ef936b8f5d24b",
          "md5": "f074a9fa58ab79212b2e40a9bf14a46e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-fips",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bc-fips",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-plugin-cli-1.0.0-alpha2.jar",
          "url": "opensearch-plugin-cli-1.0.0-alpha2.jar",
          "size": 34681,
          "sha512": "26a96a338e7f1aead8ebe48f679a5d39bdd1d6b63f5d187d7364b8bc4a80374d3695cee3a03c281c833e2fff82ade102ec4a8aa2ce6e5ae02696e29330548758",
          "sha256": "f90173b3c34fa07463db79f86e3309b511b2729d9a2510f234621775946bdbb7",
          "sha1": "e4efc406baae991cd1203f940c6ef936b8f5d24b",
          "md5": "f074a9fa58ab79212b2e40a9bf14a46e"
        }
      ]
    }
  ]
}
