{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.gradle",
    "module": "build-tools",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "nebula-publishing-plugin",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-info-plugin",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.apache.rat",
          "module": "apache-rat",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "de.thetaphi",
          "module": "forbiddenapis",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.avast.gradle",
          "module": "gradle-docker-compose-plugin",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha1.jar",
          "url": "build-tools-1.0.0-alpha1.jar",
          "size": 1056236,
          "sha512": "8598869f6bf632c1083e64da1e5784e1340433bc1b5bc9539bdb2a2d919b7c526d557abfebbdf9600df211b3664950c47fb5ec3f91306255f617f84bb7719487",
          "sha256": "9dcdc0b68e6f39dab4072b96abc20baabf61cf8cf8ae1c4ef61516e8f6db9236",
          "sha1": "dee483706f7fa4bc1ec0ed2b37767233d0ab47e7",
          "md5": "f735f25fc025a17f8cc61c6fd1d4045d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "nebula-publishing-plugin",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-info-plugin",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.apache.rat",
          "module": "apache-rat",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "de.thetaphi",
          "module": "forbiddenapis",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.avast.gradle",
          "module": "gradle-docker-compose-plugin",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha1.jar",
          "url": "build-tools-1.0.0-alpha1.jar",
          "size": 1056236,
          "sha512": "8598869f6bf632c1083e64da1e5784e1340433bc1b5bc9539bdb2a2d919b7c526d557abfebbdf9600df211b3664950c47fb5ec3f91306255f617f84bb7719487",
          "sha256": "9dcdc0b68e6f39dab4072b96abc20baabf61cf8cf8ae1c4ef61516e8f6db9236",
          "sha1": "dee483706f7fa4bc1ec0ed2b37767233d0ab47e7",
          "md5": "f735f25fc025a17f8cc61c6fd1d4045d"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.gradle",
          "module": "build-tools",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha1-test-fixtures.jar",
          "url": "build-tools-1.0.0-alpha1-test-fixtures.jar",
          "size": 15956,
          "sha512": "d290e784ec4f3019c3bcb0f1fbd8d9c619b796d6d27aaee5f7101e2538f29684619aaab62c051e612a1001761631f2bfcf764d658cc28b8f0c4d29eec00b23c9",
          "sha256": "db7e5c8090f6c786df3d51dc967f3e046f62ca5d761bd68ee5188b3d2350ae60",
          "sha1": "f77230aa32742e1beaaff92ca844946fe6124dd4",
          "md5": "675b98c851bd27be0e76cae8a876d3ad"
        }
      ],
      "capabilities": [
        {
          "group": "org.opensearch.gradle",
          "name": "build-tools-test-fixtures",
          "version": "1.0.0-alpha1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.gradle",
          "module": "build-tools",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha1-test-fixtures.jar",
          "url": "build-tools-1.0.0-alpha1-test-fixtures.jar",
          "size": 15956,
          "sha512": "d290e784ec4f3019c3bcb0f1fbd8d9c619b796d6d27aaee5f7101e2538f29684619aaab62c051e612a1001761631f2bfcf764d658cc28b8f0c4d29eec00b23c9",
          "sha256": "db7e5c8090f6c786df3d51dc967f3e046f62ca5d761bd68ee5188b3d2350ae60",
          "sha1": "f77230aa32742e1beaaff92ca844946fe6124dd4",
          "md5": "675b98c851bd27be0e76cae8a876d3ad"
        }
      ],
      "capabilities": [
        {
          "group": "org.opensearch.gradle",
          "name": "build-tools-test-fixtures",
          "version": "1.0.0-alpha1"
        }
      ]
    }
  ]
}
