/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.opensearch.dataprepper.plugins.source.jira.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;

import java.util.List;

/**
 * The result of a JQL search.
 */
@Getter
public class SearchResults {
    @JsonProperty("expand")
    private String expand = null;

    @JsonProperty("startAt")
    private Integer startAt = null;

    @JsonProperty("maxResults")
    private Integer maxResults = null;

    @JsonProperty("total")
    private Integer total = null;

    @JsonProperty("issues")
    private List<IssueBean> issues = null;

}
