{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "transport-netty4-client",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-resolver",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "transport-netty4-client-1.0.0-alpha1.jar",
          "url": "transport-netty4-client-1.0.0-alpha1.jar",
          "size": 75611,
          "sha512": "5cbced601dee308ea1f2538c853e4ea2489800239e308086f3aaffb58e7fc645a207c1cc915dd445e5f44b889142c39438ceda69e7177527b299ef81655dbf57",
          "sha256": "1807c9eada5a170a007fb54e4abd078e333df1132f10656334a0429a6d6e189d",
          "sha1": "6e3ca2125fbd0e78f4898c7f9c8fdb176a667045",
          "md5": "023bca941faeec48a5c0c1bb1c9e4cd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-resolver",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "transport-netty4-client-1.0.0-alpha1.jar",
          "url": "transport-netty4-client-1.0.0-alpha1.jar",
          "size": 75611,
          "sha512": "5cbced601dee308ea1f2538c853e4ea2489800239e308086f3aaffb58e7fc645a207c1cc915dd445e5f44b889142c39438ceda69e7177527b299ef81655dbf57",
          "sha256": "1807c9eada5a170a007fb54e4abd078e333df1132f10656334a0429a6d6e189d",
          "sha1": "6e3ca2125fbd0e78f4898c7f9c8fdb176a667045",
          "md5": "023bca941faeec48a5c0c1bb1c9e4cd8"
        }
      ]
    }
  ]
}
