{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "percolator-client",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "percolator-client-1.0.0-beta1.jar",
          "url": "percolator-client-1.0.0-beta1.jar",
          "size": 77576,
          "sha512": "02908ee941d27171142bf11645bf1f897841ce6c2e6da6e12f7e10d2ba170a50ba554d61aedf1bb5b47023bc5006ba7a856b8b04e4289d821717fd8f9049dc23",
          "sha256": "b6a0dc248aa97e2a3b29df39b219657c9791d5bbc76ea6e2e8dc8cf63bc9daa1",
          "sha1": "0385fcb3f88af5aa08b8c36e0ae2f2ce5ba388e6",
          "md5": "32a75eba97eb40acb365899e9171b4dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "percolator-client-1.0.0-beta1.jar",
          "url": "percolator-client-1.0.0-beta1.jar",
          "size": 77576,
          "sha512": "02908ee941d27171142bf11645bf1f897841ce6c2e6da6e12f7e10d2ba170a50ba554d61aedf1bb5b47023bc5006ba7a856b8b04e4289d821717fd8f9049dc23",
          "sha256": "b6a0dc248aa97e2a3b29df39b219657c9791d5bbc76ea6e2e8dc8cf63bc9daa1",
          "sha1": "0385fcb3f88af5aa08b8c36e0ae2f2ce5ba388e6",
          "md5": "32a75eba97eb40acb365899e9171b4dd"
        }
      ]
    }
  ]
}
