{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-geo",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-geo-1.0.0-alpha2.jar",
          "url": "opensearch-geo-1.0.0-alpha2.jar",
          "size": 45298,
          "sha512": "048d41635fbe4508337cf29e8e20167859f9e6617af0b2a8f994c860b5320bd0a2ba9f94a7c2bdf885ce816ecb2876043cc2fdb1eddbd2e8bac8ce6623b5f4da",
          "sha256": "322aa9eb032f88597926786a48a8fd8c7ae10da8d5db04ac17156d629140c59f",
          "sha1": "1d2bff4e3aa5c92b3b68972dd5fac4303d063c71",
          "md5": "72c3f252b9484e6833b9a2a5a7f63487"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-geo-1.0.0-alpha2.jar",
          "url": "opensearch-geo-1.0.0-alpha2.jar",
          "size": 45298,
          "sha512": "048d41635fbe4508337cf29e8e20167859f9e6617af0b2a8f994c860b5320bd0a2ba9f94a7c2bdf885ce816ecb2876043cc2fdb1eddbd2e8bac8ce6623b5f4da",
          "sha256": "322aa9eb032f88597926786a48a8fd8c7ae10da8d5db04ac17156d629140c59f",
          "sha1": "1d2bff4e3aa5c92b3b68972dd5fac4303d063c71",
          "md5": "72c3f252b9484e6833b9a2a5a7f63487"
        }
      ]
    }
  ]
}
