{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.client",
    "module": "transport",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "lang-mustache-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "percolator-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "parent-join-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "rank-eval-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "transport-1.0.0-alpha1.jar",
          "url": "transport-1.0.0-alpha1.jar",
          "size": 7605,
          "sha512": "ac4d6fc4018604c625567eaac32949dfe1805be78f744f6b991be5388b997092c00d74b4aa0727192cebd2a30b4234299cdb08396a5f245685c7efe4a9948952",
          "sha256": "8fa0d694a782f1358f10dab118a5dbe39b1dbd28e1a4471e423f4b8c68f82ee0",
          "sha1": "bac2d1a3a7d36d1354a536518f5f9867726b1ea0",
          "md5": "040abbce2e9fc9c332414ece82afe0ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "lang-mustache-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "percolator-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "parent-join-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "rank-eval-client",
          "version": {
            "requires": "1.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "transport-1.0.0-alpha1.jar",
          "url": "transport-1.0.0-alpha1.jar",
          "size": 7605,
          "sha512": "ac4d6fc4018604c625567eaac32949dfe1805be78f744f6b991be5388b997092c00d74b4aa0727192cebd2a30b4234299cdb08396a5f245685c7efe4a9948952",
          "sha256": "8fa0d694a782f1358f10dab118a5dbe39b1dbd28e1a4471e423f4b8c68f82ee0",
          "sha1": "bac2d1a3a7d36d1354a536518f5f9867726b1ea0",
          "md5": "040abbce2e9fc9c332414ece82afe0ca"
        }
      ]
    }
  ]
}
