{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-geoip",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.maxmind.geoip2",
          "module": "geoip2",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.maxmind.db",
          "module": "maxmind-db",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ingest-geoip-1.0.0-alpha1.jar",
          "url": "ingest-geoip-1.0.0-alpha1.jar",
          "size": 27523,
          "sha512": "2983cfe4a06e3eee84cb6d76534604e01996acfa59dc70307795f9719b527f73e239087d6386a3fdc549f9222ce5abd8b74f78ab91772b53428f1526d4fd836a",
          "sha256": "235520785c0d0e4fd3c1ea41d51ecfbb45ce19d621e36753933e03e44f83ec5d",
          "sha1": "dbaabd6047f1c852f2783f3a75430514db64d952",
          "md5": "86540a8ec95bbf635cb90dafb2a85430"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.maxmind.geoip2",
          "module": "geoip2",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.maxmind.db",
          "module": "maxmind-db",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ingest-geoip-1.0.0-alpha1.jar",
          "url": "ingest-geoip-1.0.0-alpha1.jar",
          "size": 27523,
          "sha512": "2983cfe4a06e3eee84cb6d76534604e01996acfa59dc70307795f9719b527f73e239087d6386a3fdc549f9222ce5abd8b74f78ab91772b53428f1526d4fd836a",
          "sha256": "235520785c0d0e4fd3c1ea41d51ecfbb45ce19d621e36753933e03e44f83ec5d",
          "sha1": "dbaabd6047f1c852f2783f3a75430514db64d952",
          "md5": "86540a8ec95bbf635cb90dafb2a85430"
        }
      ]
    }
  ]
}
