{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-phonetic",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-phonetic",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-phonetic-1.0.0-alpha1.jar",
          "url": "analysis-phonetic-1.0.0-alpha1.jar",
          "size": 18416,
          "sha512": "8ae5c98835d623b42095397e763db07f09178d0c9ffcc6ca16635407148649c9ad4dfc8abad3c23f82a6465f4408c022f8d09518fafa86fefbc6e44c6a9e51c6",
          "sha256": "a85b3707eb9c69ec35c40ef86bfaf209b233952251c8732f808b4dea413fbf2f",
          "sha1": "9e96f0836909cef1aefca602b80298ae8700e2f2",
          "md5": "da90c1fe92be17634f128cbfbd47ee66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-phonetic",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-phonetic-1.0.0-alpha1.jar",
          "url": "analysis-phonetic-1.0.0-alpha1.jar",
          "size": 18416,
          "sha512": "8ae5c98835d623b42095397e763db07f09178d0c9ffcc6ca16635407148649c9ad4dfc8abad3c23f82a6465f4408c022f8d09518fafa86fefbc6e44c6a9e51c6",
          "sha256": "a85b3707eb9c69ec35c40ef86bfaf209b233952251c8732f808b4dea413fbf2f",
          "sha1": "9e96f0836909cef1aefca602b80298ae8700e2f2",
          "md5": "da90c1fe92be17634f128cbfbd47ee66"
        }
      ]
    }
  ]
}
