{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.client",
    "module": "transport",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "lang-mustache-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "percolator-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "parent-join-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "rank-eval-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "transport-1.0.0-beta1.jar",
          "url": "transport-1.0.0-beta1.jar",
          "size": 7601,
          "sha512": "74570bc4d78883e5449b2e4acbc8c03bb25aa9547903285e9bf955322562a2ceeb0a20867a283276219204d275f3d6c2278a7db53158ca3de0e29d9d8b23a601",
          "sha256": "8ad62b1f41ec6a8b027793967d73dbf48a2b6fea3cdef3acf571dee8f4ef77f0",
          "sha1": "2e0b2a7186b5370c2332d9a71bd1de0e731867ff",
          "md5": "22c93128a5d7677cad32961cd139a43e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "lang-mustache-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "percolator-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "parent-join-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch.plugin",
          "module": "rank-eval-client",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "transport-1.0.0-beta1.jar",
          "url": "transport-1.0.0-beta1.jar",
          "size": 7601,
          "sha512": "74570bc4d78883e5449b2e4acbc8c03bb25aa9547903285e9bf955322562a2ceeb0a20867a283276219204d275f3d6c2278a7db53158ca3de0e29d9d8b23a601",
          "sha256": "8ad62b1f41ec6a8b027793967d73dbf48a2b6fea3cdef3acf571dee8f4ef77f0",
          "sha1": "2e0b2a7186b5370c2332d9a71bd1de0e731867ff",
          "md5": "22c93128a5d7677cad32961cd139a43e"
        }
      ]
    }
  ]
}
