{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-phonetic",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-phonetic",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-phonetic-1.0.0-beta1.jar",
          "url": "analysis-phonetic-1.0.0-beta1.jar",
          "size": 18413,
          "sha512": "25069a0c3ffc797388018c79b823ede0def9581c98f9aed50c855e1d26a5c41acbcd780377d54e306fa1ae046262c5724d5cd557cacad4c6fe6cca755cbc1d5d",
          "sha256": "a9184be2fdfc6d934470424b59b9b8c2f8805e2eadab147c5e5bca4557488b6b",
          "sha1": "ba2754f2d49182d97e3c8f87d40790bf1b0cc5f2",
          "md5": "8bbc20c955da9a29a45bbda3418940c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-phonetic",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-phonetic-1.0.0-beta1.jar",
          "url": "analysis-phonetic-1.0.0-beta1.jar",
          "size": 18413,
          "sha512": "25069a0c3ffc797388018c79b823ede0def9581c98f9aed50c855e1d26a5c41acbcd780377d54e306fa1ae046262c5724d5cd557cacad4c6fe6cca755cbc1d5d",
          "sha256": "a9184be2fdfc6d934470424b59b9b8c2f8805e2eadab147c5e5bca4557488b6b",
          "sha1": "ba2754f2d49182d97e3c8f87d40790bf1b0cc5f2",
          "md5": "8bbc20c955da9a29a45bbda3418940c4"
        }
      ]
    }
  ]
}
