{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.gradle",
    "module": "build-tools",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "nebula-publishing-plugin",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-info-plugin",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.apache.rat",
          "module": "apache-rat",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "de.thetaphi",
          "module": "forbiddenapis",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.avast.gradle",
          "module": "gradle-docker-compose-plugin",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha2.jar",
          "url": "build-tools-1.0.0-alpha2.jar",
          "size": 1056342,
          "sha512": "4c4acc7ba0000733ad5ae5e4192a92ab76f7b6ec5616ad7eb4a972a3f77a76dbe5717b7c3d4ae97663aff30181b999435d865c92041bac08e60cb64dccc3c896",
          "sha256": "f087d553f908e5617971c2e50d642ee6503578891560602202bede3ea5632f62",
          "sha1": "12ca6f396e2edb65ce0aa8414287fe8b3db90151",
          "md5": "d71f1353ceb2ea96c44c7c5f086879f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "nebula-publishing-plugin",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-info-plugin",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.apache.rat",
          "module": "apache-rat",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "de.thetaphi",
          "module": "forbiddenapis",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.avast.gradle",
          "module": "gradle-docker-compose-plugin",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha2.jar",
          "url": "build-tools-1.0.0-alpha2.jar",
          "size": 1056342,
          "sha512": "4c4acc7ba0000733ad5ae5e4192a92ab76f7b6ec5616ad7eb4a972a3f77a76dbe5717b7c3d4ae97663aff30181b999435d865c92041bac08e60cb64dccc3c896",
          "sha256": "f087d553f908e5617971c2e50d642ee6503578891560602202bede3ea5632f62",
          "sha1": "12ca6f396e2edb65ce0aa8414287fe8b3db90151",
          "md5": "d71f1353ceb2ea96c44c7c5f086879f0"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.gradle",
          "module": "build-tools",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha2-test-fixtures.jar",
          "url": "build-tools-1.0.0-alpha2-test-fixtures.jar",
          "size": 15954,
          "sha512": "0b0545750f61d160bdac3c577e54ce4739d9642d6a76d950e968e3d1d5ca7b2c7b978f0fb3726b7e8072bef37e57bd09be4b179316df9d01b3deebd0b9bffce0",
          "sha256": "05da8d4174c024e5ee351c4f9a901bfad563b111a2fae6dacab9f76cab9e02fe",
          "sha1": "f74d1586b224c26d6e55a689142b810f631d047a",
          "md5": "e95829ebc3d82f9d228b4939cf9a34d8"
        }
      ],
      "capabilities": [
        {
          "group": "org.opensearch.gradle",
          "name": "build-tools-test-fixtures",
          "version": "1.0.0-alpha2"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.gradle",
          "module": "build-tools",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-alpha2-test-fixtures.jar",
          "url": "build-tools-1.0.0-alpha2-test-fixtures.jar",
          "size": 15954,
          "sha512": "0b0545750f61d160bdac3c577e54ce4739d9642d6a76d950e968e3d1d5ca7b2c7b978f0fb3726b7e8072bef37e57bd09be4b179316df9d01b3deebd0b9bffce0",
          "sha256": "05da8d4174c024e5ee351c4f9a901bfad563b111a2fae6dacab9f76cab9e02fe",
          "sha1": "f74d1586b224c26d6e55a689142b810f631d047a",
          "md5": "e95829ebc3d82f9d228b4939cf9a34d8"
        }
      ],
      "capabilities": [
        {
          "group": "org.opensearch.gradle",
          "name": "build-tools-test-fixtures",
          "version": "1.0.0-alpha2"
        }
      ]
    }
  ]
}
