{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-smartcn",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-smartcn",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-smartcn-1.0.0-beta1.jar",
          "url": "analysis-smartcn-1.0.0-beta1.jar",
          "size": 10594,
          "sha512": "ed56664abc35786311dc2b323387891cf41d201c7e6678bf1b27b7d9ca4f7a6f39bc6da2523680e3ef4bf672cf0b27eeb89f88a66570bb9694a0c25566275219",
          "sha256": "be158deedc25214f41ed645d727b24aca98a92d3f0a4899611117faa9d7afebb",
          "sha1": "b05cc701cd563e93ba950792585765ed61273224",
          "md5": "212478a0d22fae407cd31ebfd5f47267"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-smartcn",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-smartcn-1.0.0-beta1.jar",
          "url": "analysis-smartcn-1.0.0-beta1.jar",
          "size": 10594,
          "sha512": "ed56664abc35786311dc2b323387891cf41d201c7e6678bf1b27b7d9ca4f7a6f39bc6da2523680e3ef4bf672cf0b27eeb89f88a66570bb9694a0c25566275219",
          "sha256": "be158deedc25214f41ed645d727b24aca98a92d3f0a4899611117faa9d7afebb",
          "sha1": "b05cc701cd563e93ba950792585765ed61273224",
          "md5": "212478a0d22fae407cd31ebfd5f47267"
        }
      ]
    }
  ]
}
