{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-ssl-config",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-ssl-config-1.0.0-beta1.jar",
          "url": "opensearch-ssl-config-1.0.0-beta1.jar",
          "size": 67007,
          "sha512": "6dc2d8152dd77429fd8714bdd1d2a83154c04577a518f280009e50aea05bdc662ae0eb778cb3630032e08b52f7a2c71d7f4ee7d6ac42016d39cf1df8363c6e5a",
          "sha256": "83428b3414eab8ec086d0e0efc67d997ae2c00ac4c611a13350a0d04c7f134ca",
          "sha1": "107e5b87b7fe9f3b6e47dfdf15f49feba06c26b9",
          "md5": "b9c23546ef32e4f57f7a24038cea0d76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-ssl-config-1.0.0-beta1.jar",
          "url": "opensearch-ssl-config-1.0.0-beta1.jar",
          "size": 67007,
          "sha512": "6dc2d8152dd77429fd8714bdd1d2a83154c04577a518f280009e50aea05bdc662ae0eb778cb3630032e08b52f7a2c71d7f4ee7d6ac42016d39cf1df8363c6e5a",
          "sha256": "83428b3414eab8ec086d0e0efc67d997ae2c00ac4c611a13350a0d04c7f134ca",
          "sha1": "107e5b87b7fe9f3b6e47dfdf15f49feba06c26b9",
          "md5": "b9c23546ef32e4f57f7a24038cea0d76"
        }
      ]
    }
  ]
}
