{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-user-agent",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ingest-user-agent-1.0.0-beta1.jar",
          "url": "ingest-user-agent-1.0.0-beta1.jar",
          "size": 65799,
          "sha512": "490ce514d497606fdd4be7041b89b4743da19ceb039a41f829615cd272c9a0a0bd1ef48ce114bf1718b35a01384199a7a189393c792ed219d1fb0b55e515254f",
          "sha256": "8175fce5d49aac05ad026089c18e01ffc116be71c59cc01038e502a1ed58e6a3",
          "sha1": "d40d2675090ad3c30a1505fc31391871142fd9e5",
          "md5": "82fea2c0310bf4331b3cd3c8a6e84169"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ingest-user-agent-1.0.0-beta1.jar",
          "url": "ingest-user-agent-1.0.0-beta1.jar",
          "size": 65799,
          "sha512": "490ce514d497606fdd4be7041b89b4743da19ceb039a41f829615cd272c9a0a0bd1ef48ce114bf1718b35a01384199a7a189393c792ed219d1fb0b55e515254f",
          "sha256": "8175fce5d49aac05ad026089c18e01ffc116be71c59cc01038e502a1ed58e6a3",
          "sha1": "d40d2675090ad3c30a1505fc31391871142fd9e5",
          "md5": "82fea2c0310bf4331b3cd3c8a6e84169"
        }
      ]
    }
  ]
}
