{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-ssl-config",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-ssl-config-1.0.0-alpha2.jar",
          "url": "opensearch-ssl-config-1.0.0-alpha2.jar",
          "size": 67007,
          "sha512": "83c8ef29e95c1b957d2d01b833ca144770b8109d571a08f6b7aa7e6f0d5b9f735b8789a34bd2904eaaafbbbb65c9a82762feddba40958130c44601a22b84d961",
          "sha256": "490591ac71051f8807c73954797f54ba04ad58ee15c95041bdaf8449abdc9795",
          "sha1": "7ff1a681582880bd265752acb7124fefd87996eb",
          "md5": "d8090cb8a37bc65e7a39f0ff601d84d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-ssl-config-1.0.0-alpha2.jar",
          "url": "opensearch-ssl-config-1.0.0-alpha2.jar",
          "size": 67007,
          "sha512": "83c8ef29e95c1b957d2d01b833ca144770b8109d571a08f6b7aa7e6f0d5b9f735b8789a34bd2904eaaafbbbb65c9a82762feddba40958130c44601a22b84d961",
          "sha256": "490591ac71051f8807c73954797f54ba04ad58ee15c95041bdaf8449abdc9795",
          "sha1": "7ff1a681582880bd265752acb7124fefd87996eb",
          "md5": "d8090cb8a37bc65e7a39f0ff601d84d0"
        }
      ]
    }
  ]
}
