{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "repository-url",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "repository-url-1.0.0-alpha2.jar",
          "url": "repository-url-1.0.0-alpha2.jar",
          "size": 15010,
          "sha512": "9aa7f7c3dc27ee4616e057849b5c4b5b512431239f2c82d6d79e1787ccdebb6a31baa6b7b8dca3eedb0598388250ebf19709e5c4a1f29254b7796609af23ad57",
          "sha256": "314748535858873f9fd335c06ad9d8a569277a958a44a2d8b3dc17f0f4c3456d",
          "sha1": "ae4a29372da3b287862f980ab311e2ef368c5691",
          "md5": "5c9bb6dbf433541063d535f0e65f05c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "repository-url-1.0.0-alpha2.jar",
          "url": "repository-url-1.0.0-alpha2.jar",
          "size": 15010,
          "sha512": "9aa7f7c3dc27ee4616e057849b5c4b5b512431239f2c82d6d79e1787ccdebb6a31baa6b7b8dca3eedb0598388250ebf19709e5c4a1f29254b7796609af23ad57",
          "sha256": "314748535858873f9fd335c06ad9d8a569277a958a44a2d8b3dc17f0f4c3456d",
          "sha1": "ae4a29372da3b287862f980ab311e2ef368c5691",
          "md5": "5c9bb6dbf433541063d535f0e65f05c9"
        }
      ]
    }
  ]
}
