{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "discovery-azure-classic",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-svc-mgmt-compute",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-core",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-1.2-api",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.mail",
          "module": "mail",
          "version": {
            "requires": "1.4.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-client",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-core",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-json",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jettison",
          "module": "jettison",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.2.3-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-core-asl",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-mapper-asl",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-jaxrs",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-xc",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "discovery-azure-classic-1.0.0-alpha2.jar",
          "url": "discovery-azure-classic-1.0.0-alpha2.jar",
          "size": 23601,
          "sha512": "d9990e99ab3d3f5d1e4d9ba47691c5785ad3541c532c7d10708ec01575c7633d1262b55a6ab49f1f98932a396d5e97feadfc0fb5791bf1717fd8b9ffa52bff78",
          "sha256": "6aada79e5d09b31cf0db60c5e79f4641fe95189331a813e053ec0aa2db14724b",
          "sha1": "36a9462096e0cb98b99d44f99505a5ea84c51b87",
          "md5": "1be49bcce395a90f3b7be5302649d388"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-svc-mgmt-compute",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-core",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-1.2-api",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.mail",
          "module": "mail",
          "version": {
            "requires": "1.4.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-client",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-core",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.jersey",
          "module": "jersey-json",
          "version": {
            "requires": "1.13"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jettison",
          "module": "jettison",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.sun.xml.bind",
          "module": "jaxb-impl",
          "version": {
            "requires": "2.2.3-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-core-asl",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-mapper-asl",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-jaxrs",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.codehaus.jackson",
          "module": "jackson-xc",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "discovery-azure-classic-1.0.0-alpha2.jar",
          "url": "discovery-azure-classic-1.0.0-alpha2.jar",
          "size": 23601,
          "sha512": "d9990e99ab3d3f5d1e4d9ba47691c5785ad3541c532c7d10708ec01575c7633d1262b55a6ab49f1f98932a396d5e97feadfc0fb5791bf1717fd8b9ffa52bff78",
          "sha256": "6aada79e5d09b31cf0db60c5e79f4641fe95189331a813e053ec0aa2db14724b",
          "sha1": "36a9462096e0cb98b99d44f99505a5ea84c51b87",
          "md5": "1be49bcce395a90f3b7be5302649d388"
        }
      ]
    }
  ]
}
