receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      memory:
  prometheus:
    config:
      scrape_configs:
        - job_name: data-prepper
          metrics_path: /metrics/sys
          scrape_interval: 60s
          static_configs:
            - targets: ['data-prepper:4900']
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  otlp/metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
  otlphttp/metrics:
    metrics_endpoint: http://data-prepper:21891/opentelemetry.proto.collector.metrics.v1.MetricsService/Export
  logging:
processors:
  resourcedetection/env:
    detectors: [env]
    timeout: 2s
    override: false
service:
  pipelines:
    metrics:
      receivers: [otlp,hostmetrics,prometheus]
      processors: [resourcedetection/env]
      exporters: [logging, otlp/metrics]
