{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-kuromoji",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-kuromoji",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-kuromoji-1.0.0-alpha2.jar",
          "url": "analysis-kuromoji-1.0.0-alpha2.jar",
          "size": 17873,
          "sha512": "5d5d6a1f10549572fffa6c53de63a9b25c8c3a8926957084d280747b9e02ddd3fe241b7a62eefa93b0ae8dad1166a6f7de5cbecb3db353982e137815c42b4502",
          "sha256": "86d8256868a4e8eee687b4cca3f693ba83e3410606f0cc08e3dc2072994f3136",
          "sha1": "f1674120ca8a9f428267804289518656ce1e28dd",
          "md5": "a80daf0c5e4d5419b9d5247767b6000e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-kuromoji",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-kuromoji-1.0.0-alpha2.jar",
          "url": "analysis-kuromoji-1.0.0-alpha2.jar",
          "size": 17873,
          "sha512": "5d5d6a1f10549572fffa6c53de63a9b25c8c3a8926957084d280747b9e02ddd3fe241b7a62eefa93b0ae8dad1166a6f7de5cbecb3db353982e137815c42b4502",
          "sha256": "86d8256868a4e8eee687b4cca3f693ba83e3410606f0cc08e3dc2072994f3136",
          "sha1": "f1674120ca8a9f428267804289518656ce1e28dd",
          "md5": "a80daf0c5e4d5419b9d5247767b6000e"
        }
      ]
    }
  ]
}
