{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.gradle",
    "module": "build-tools",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "nebula-publishing-plugin",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-info-plugin",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.apache.rat",
          "module": "apache-rat",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "de.thetaphi",
          "module": "forbiddenapis",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.avast.gradle",
          "module": "gradle-docker-compose-plugin",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-beta1.jar",
          "url": "build-tools-1.0.0-beta1.jar",
          "size": 1056339,
          "sha512": "a90b7e62806e501f9907a8cc698d578f01ffec5ed83994c4c9cf96cfc64ff289a556545b1f183c06be1712f44cf473a8d440ac075e96373f99aaa495cba69b63",
          "sha256": "f04b3ece82a7eabd61694477b9412bf9ff4e57fca38f63478efab4d06730f9a6",
          "sha1": "61e9c0b6f2ecd1068f59f464303e543e2f98ee25",
          "md5": "726e96bfc78851e926ee640c2df46469"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "nebula-publishing-plugin",
          "version": {
            "requires": "4.4.4"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-info-plugin",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.apache.rat",
          "module": "apache-rat",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.jengelman.gradle.plugins",
          "module": "shadow",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "de.thetaphi",
          "module": "forbiddenapis",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.avast.gradle",
          "module": "gradle-docker-compose-plugin",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-beta1.jar",
          "url": "build-tools-1.0.0-beta1.jar",
          "size": 1056339,
          "sha512": "a90b7e62806e501f9907a8cc698d578f01ffec5ed83994c4c9cf96cfc64ff289a556545b1f183c06be1712f44cf473a8d440ac075e96373f99aaa495cba69b63",
          "sha256": "f04b3ece82a7eabd61694477b9412bf9ff4e57fca38f63478efab4d06730f9a6",
          "sha1": "61e9c0b6f2ecd1068f59f464303e543e2f98ee25",
          "md5": "726e96bfc78851e926ee640c2df46469"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.gradle",
          "module": "build-tools",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-beta1-test-fixtures.jar",
          "url": "build-tools-1.0.0-beta1-test-fixtures.jar",
          "size": 15952,
          "sha512": "b8129aa7eb2f0ca74837e7e00388e3a747ceab6ed02a411e95361e5123a1ce95c1cfe11f6fd6e38c3322cf356c627473151fff3db61faafbd43cdd6fee3b5b3f",
          "sha256": "e06928e262a24ccedbc291dda7d2290a08f50ca2a6ff7240b7e22f7dfba43deb",
          "sha1": "446ece03b1c4b8ddafa7fbcf0eac0c577b7884e4",
          "md5": "bba7879fc0d994fb171966d0817978ca"
        }
      ],
      "capabilities": [
        {
          "group": "org.opensearch.gradle",
          "name": "build-tools-test-fixtures",
          "version": "1.0.0-beta1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 10,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.gradle",
          "module": "build-tools",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "build-tools-1.0.0-beta1-test-fixtures.jar",
          "url": "build-tools-1.0.0-beta1-test-fixtures.jar",
          "size": 15952,
          "sha512": "b8129aa7eb2f0ca74837e7e00388e3a747ceab6ed02a411e95361e5123a1ce95c1cfe11f6fd6e38c3322cf356c627473151fff3db61faafbd43cdd6fee3b5b3f",
          "sha256": "e06928e262a24ccedbc291dda7d2290a08f50ca2a6ff7240b7e22f7dfba43deb",
          "sha1": "446ece03b1c4b8ddafa7fbcf0eac0c577b7884e4",
          "md5": "bba7879fc0d994fb171966d0817978ca"
        }
      ],
      "capabilities": [
        {
          "group": "org.opensearch.gradle",
          "name": "build-tools-test-fixtures",
          "version": "1.0.0-beta1"
        }
      ]
    }
  ]
}
