{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "transport-nio-client",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-nio",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-resolver",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "transport-nio-client-1.0.0-beta1.jar",
          "url": "transport-nio-client-1.0.0-beta1.jar",
          "size": 62215,
          "sha512": "0d21567b9247575d0b486f0cc0a42782f03069026ae8e2a88970dd9973db1beb0bca6be128c4749e71e548f3267328c6e985bfdba9d89170a421b44eb0f6477e",
          "sha256": "34187259019a09bd6f7455dab7d6b81e975610c2d5236bc3dde0cfce38e010bd",
          "sha1": "d704e8f49b37e221daff6cc5729b196d58e6ec74",
          "md5": "a5a12a5577c957a0441023fa3372c174"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-nio",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-resolver",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.49.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "transport-nio-client-1.0.0-beta1.jar",
          "url": "transport-nio-client-1.0.0-beta1.jar",
          "size": 62215,
          "sha512": "0d21567b9247575d0b486f0cc0a42782f03069026ae8e2a88970dd9973db1beb0bca6be128c4749e71e548f3267328c6e985bfdba9d89170a421b44eb0f6477e",
          "sha256": "34187259019a09bd6f7455dab7d6b81e975610c2d5236bc3dde0cfce38e010bd",
          "sha1": "d704e8f49b37e221daff6cc5729b196d58e6ec74",
          "md5": "a5a12a5577c957a0441023fa3372c174"
        }
      ]
    }
  ]
}
