{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-grok",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jruby.joni",
          "module": "joni",
          "version": {
            "requires": "2.1.29"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jruby.jcodings",
          "module": "jcodings",
          "version": {
            "requires": "1.0.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-grok-1.0.0-beta1.jar",
          "url": "opensearch-grok-1.0.0-beta1.jar",
          "size": 48252,
          "sha512": "174f826b00295cb676b5db8706db656dded5253b57b410762d862734a83e9a7f671cfe1bd5838abe8158db451857bf45aa430a964c69a514d0d2de496927ab13",
          "sha256": "30f35d0aa536da64e3da0a8caed8c9462ed7975ae2b46d77269ce2d7c46234e4",
          "sha1": "9c0dfd4754aeb73ea238cd159cb267da4558adf1",
          "md5": "22ea3919252da4852218eb4af4c27591"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jruby.joni",
          "module": "joni",
          "version": {
            "requires": "2.1.29"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jruby.jcodings",
          "module": "jcodings",
          "version": {
            "requires": "1.0.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-grok-1.0.0-beta1.jar",
          "url": "opensearch-grok-1.0.0-beta1.jar",
          "size": 48252,
          "sha512": "174f826b00295cb676b5db8706db656dded5253b57b410762d862734a83e9a7f671cfe1bd5838abe8158db451857bf45aa430a964c69a514d0d2de496927ab13",
          "sha256": "30f35d0aa536da64e3da0a8caed8c9462ed7975ae2b46d77269ce2d7c46234e4",
          "sha1": "9c0dfd4754aeb73ea238cd159cb267da4558adf1",
          "md5": "22ea3919252da4852218eb4af4c27591"
        }
      ]
    }
  ]
}
