{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "systemd",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "systemd-1.0.0-alpha1.jar",
          "url": "systemd-1.0.0-alpha1.jar",
          "size": 9269,
          "sha512": "2124c0204305705ec762d8bdb543ba4524226f43dda82be013d39ab816e006884e42390040779aa8b9cf7c4f78e34a59f485d02b31fe53701aceb4824f7f9088",
          "sha256": "40863da50bf2554344b7b8acfdf2f7bdb95071d16beb1ebdb514d69cda68c217",
          "sha1": "7f9a944853fbeb517f02a70ac5728d12ef579528",
          "md5": "a577b77a460c8e7307b7b4eb294b5187"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "systemd-1.0.0-alpha1.jar",
          "url": "systemd-1.0.0-alpha1.jar",
          "size": 9269,
          "sha512": "2124c0204305705ec762d8bdb543ba4524226f43dda82be013d39ab816e006884e42390040779aa8b9cf7c4f78e34a59f485d02b31fe53701aceb4824f7f9088",
          "sha256": "40863da50bf2554344b7b8acfdf2f7bdb95071d16beb1ebdb514d69cda68c217",
          "sha1": "7f9a944853fbeb517f02a70ac5728d12ef579528",
          "md5": "a577b77a460c8e7307b7b4eb294b5187"
        }
      ]
    }
  ]
}
