{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-cli",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-cli-1.0.0-beta1.jar",
          "url": "opensearch-cli-1.0.0-beta1.jar",
          "size": 17954,
          "sha512": "1eae3d587749224ecce90053f50eb71893ce25559336eccaf283bda2942c1eb9f03647a6d7536919c0d8ef1e87bd591a478ebd94670b301230c91d7fbf40df52",
          "sha256": "96236b711426e7b8968b9811a062b9ced4cc48e6d238407eff25f41eedc4cf9e",
          "sha1": "aacb2034e966119d03c513a86338a5b2e65782f0",
          "md5": "4f2a41bb7067080097c4df82f55773f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-cli-1.0.0-beta1.jar",
          "url": "opensearch-cli-1.0.0-beta1.jar",
          "size": 17954,
          "sha512": "1eae3d587749224ecce90053f50eb71893ce25559336eccaf283bda2942c1eb9f03647a6d7536919c0d8ef1e87bd591a478ebd94670b301230c91d7fbf40df52",
          "sha256": "96236b711426e7b8968b9811a062b9ced4cc48e6d238407eff25f41eedc4cf9e",
          "sha1": "aacb2034e966119d03c513a86338a5b2e65782f0",
          "md5": "4f2a41bb7067080097c4df82f55773f2"
        }
      ]
    }
  ]
}
