{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-size",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-size-1.0.0-alpha2.jar",
          "url": "mapper-size-1.0.0-alpha2.jar",
          "size": 10448,
          "sha512": "428bb879019f67bc552a8d21cdd9ce3fae778dabfa6c40e734536fbf2ae880aa34156578cf721cd1de0cd2a0907cf69187b0de48825f4ea28f794d766f79f379",
          "sha256": "0778227cb7cfe1ee2fba9400b4a7b755293f34ea8e7cbb71580ba1a9843ca352",
          "sha1": "dc743236bbc3a5db1c0e0d740d432ffd36e69298",
          "md5": "f8f28d374f643b46996d3d8dba47812b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-size-1.0.0-alpha2.jar",
          "url": "mapper-size-1.0.0-alpha2.jar",
          "size": 10448,
          "sha512": "428bb879019f67bc552a8d21cdd9ce3fae778dabfa6c40e734536fbf2ae880aa34156578cf721cd1de0cd2a0907cf69187b0de48825f4ea28f794d766f79f379",
          "sha256": "0778227cb7cfe1ee2fba9400b4a7b755293f34ea8e7cbb71580ba1a9843ca352",
          "sha1": "dc743236bbc3a5db1c0e0d740d432ffd36e69298",
          "md5": "f8f28d374f643b46996d3d8dba47812b"
        }
      ]
    }
  ]
}
