{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "store-smb",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "store-smb-1.0.0-alpha1.jar",
          "url": "store-smb-1.0.0-alpha1.jar",
          "size": 11393,
          "sha512": "2f586e65b2eaa5024620523aaf01d3f0e8b530b350908d0d6e805645034873966632974d730afa8447bc42a1e9489a0c0e1ac450c6c51840bb783a6c1919423a",
          "sha256": "4f05999ed13367546a6776d64468455620898b153f7e1a42fde7d49673ef922a",
          "sha1": "45497f17216d38504b271cf5047368ea721008b0",
          "md5": "b05e3c244beafc98ec4a6423760b46e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "store-smb-1.0.0-alpha1.jar",
          "url": "store-smb-1.0.0-alpha1.jar",
          "size": 11393,
          "sha512": "2f586e65b2eaa5024620523aaf01d3f0e8b530b350908d0d6e805645034873966632974d730afa8447bc42a1e9489a0c0e1ac450c6c51840bb783a6c1919423a",
          "sha256": "4f05999ed13367546a6776d64468455620898b153f7e1a42fde7d49673ef922a",
          "sha1": "45497f17216d38504b271cf5047368ea721008b0",
          "md5": "b05e3c244beafc98ec4a6423760b46e8"
        }
      ]
    }
  ]
}
