ssl: false
metricRegistries:
  - CloudWatch
source_coordination:
  partition_prefix: "neptune-04"
  store:
    dynamodb:
      table_name: "DataPrepperSourceCoordinationStore"
      region: "us-east-1"
      sts_role_arn: "arn:aws:iam::160718075058:role/OSPipelineRole"
      ttl: "P7D"
      skip_table_creation: true