{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.client",
    "module": "opensearch-rest-client-sniffer",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-rest-client-sniffer-1.0.0-alpha2.jar",
          "url": "opensearch-rest-client-sniffer-1.0.0-alpha2.jar",
          "size": 25314,
          "sha512": "7293884a521a77898c13a3c731f829f20be2da6eea1a0abf893848b0375c8603a5309327ff8234cc079017275e59f26095918f0dfd944bff429ed92b1c62a881",
          "sha256": "6cebf18998d43f353be6a2fd559cac7bc42276af30cea4c2ffd041e49f11fd64",
          "sha1": "9a1a15283ae561e73531b4cc8c845f20e56921fc",
          "md5": "acc92059c756930acf8aa3228a117351"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-rest-client-sniffer-1.0.0-alpha2.jar",
          "url": "opensearch-rest-client-sniffer-1.0.0-alpha2.jar",
          "size": 25314,
          "sha512": "7293884a521a77898c13a3c731f829f20be2da6eea1a0abf893848b0375c8603a5309327ff8234cc079017275e59f26095918f0dfd944bff429ed92b1c62a881",
          "sha256": "6cebf18998d43f353be6a2fd559cac7bc42276af30cea4c2ffd041e49f11fd64",
          "sha1": "9a1a15283ae561e73531b4cc8c845f20e56921fc",
          "md5": "acc92059c756930acf8aa3228a117351"
        }
      ]
    }
  ]
}
