{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "repository-azure",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-storage",
          "version": {
            "requires": "8.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-keyvault-core",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "repository-azure-1.0.0-alpha1.jar",
          "url": "repository-azure-1.0.0-alpha1.jar",
          "size": 43520,
          "sha512": "944c84aa1cb9bd867ab6927f8b9257dd845da4a8a9f89fa951d06fe2fefc39899594542427127c42125bf942b63f073aea6de2e73b2e63f26dc83f78453f845e",
          "sha256": "1edc48807fe871222d5e698a01d7514f7bfe75e0c621304fb9c9df26db25d531",
          "sha1": "b675a12c5c1d4333333171885aa637022526f5d0",
          "md5": "e3898971436c208c002651b8ee153520"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-storage",
          "version": {
            "requires": "8.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-keyvault-core",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "repository-azure-1.0.0-alpha1.jar",
          "url": "repository-azure-1.0.0-alpha1.jar",
          "size": 43520,
          "sha512": "944c84aa1cb9bd867ab6927f8b9257dd845da4a8a9f89fa951d06fe2fefc39899594542427127c42125bf942b63f073aea6de2e73b2e63f26dc83f78453f845e",
          "sha256": "1edc48807fe871222d5e698a01d7514f7bfe75e0c621304fb9c9df26db25d531",
          "sha1": "b675a12c5c1d4333333171885aa637022526f5d0",
          "md5": "e3898971436c208c002651b8ee153520"
        }
      ]
    }
  ]
}
