{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "repository-url",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "repository-url-1.0.0-alpha2.jar",
          "url": "repository-url-1.0.0-alpha2.jar",
          "size": 15010,
          "sha512": "37456f17267679199720364e7d7085f21546fef5196fa8e3cd9545b65efbca847f5455e15323dc5d9e91596d013acb753fceff0ca8dc1feff22a0132f2bf8775",
          "sha256": "5ea7ec538675dfb5f90cbfbd48c52c68e71a213037c61def47ae1a01d473408c",
          "sha1": "72517cbba3c804827871541e42de04442a2eb542",
          "md5": "a3962fb872b4a685ce9d034d8f53b36b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "repository-url-1.0.0-alpha2.jar",
          "url": "repository-url-1.0.0-alpha2.jar",
          "size": 15010,
          "sha512": "37456f17267679199720364e7d7085f21546fef5196fa8e3cd9545b65efbca847f5455e15323dc5d9e91596d013acb753fceff0ca8dc1feff22a0132f2bf8775",
          "sha256": "5ea7ec538675dfb5f90cbfbd48c52c68e71a213037c61def47ae1a01d473408c",
          "sha1": "72517cbba3c804827871541e42de04442a2eb542",
          "md5": "a3962fb872b4a685ce9d034d8f53b36b"
        }
      ]
    }
  ]
}
