{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-common",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-grok",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-dissect",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "ingest-common-1.0.0-beta1.jar",
          "url": "ingest-common-1.0.0-beta1.jar",
          "size": 118975,
          "sha512": "d8dcc87be0b45a452a01ec35c6927b123540a4ddbfefcd55e0a7f2a4862b70ea6da5ee3cc1c0960d57b8896e5fdd41b271d21111854eba4c6567de528f31d8be",
          "sha256": "1d84dcb024f7a05673945acdaa12f93630ef7d0f6fa76ac3d50bb8478148572a",
          "sha1": "9f0bbfef4fc11bc5346ed17f0288641fb10c244e",
          "md5": "c8d211fced2665a907fddde6d3ee54e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-grok",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-dissect",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "ingest-common-1.0.0-beta1.jar",
          "url": "ingest-common-1.0.0-beta1.jar",
          "size": 118975,
          "sha512": "d8dcc87be0b45a452a01ec35c6927b123540a4ddbfefcd55e0a7f2a4862b70ea6da5ee3cc1c0960d57b8896e5fdd41b271d21111854eba4c6567de528f31d8be",
          "sha256": "1d84dcb024f7a05673945acdaa12f93630ef7d0f6fa76ac3d50bb8478148572a",
          "sha1": "9f0bbfef4fc11bc5346ed17f0288641fb10c244e",
          "md5": "c8d211fced2665a907fddde6d3ee54e5"
        }
      ]
    }
  ]
}
