{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-murmur3",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-murmur3-1.0.0-alpha2.jar",
          "url": "mapper-murmur3-1.0.0-alpha2.jar",
          "size": 13016,
          "sha512": "86c82bb1a3d0e864603ceab114701637377c2a3e4fe752e6adc64203e21d3f526445ad81a8d417107a2562cba95e5f3dc57bafca8c9d7a96a02d279cd090f36b",
          "sha256": "e411466fadaf824b50e2aa8d2e544953d379f24858adcc46eb1c2dd2e85fd437",
          "sha1": "8dabdbbfc6ad4013ce397d7a22591e37d742dbaf",
          "md5": "33dbe414e7643281d6a87510e4bd1f32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-murmur3-1.0.0-alpha2.jar",
          "url": "mapper-murmur3-1.0.0-alpha2.jar",
          "size": 13016,
          "sha512": "86c82bb1a3d0e864603ceab114701637377c2a3e4fe752e6adc64203e21d3f526445ad81a8d417107a2562cba95e5f3dc57bafca8c9d7a96a02d279cd090f36b",
          "sha256": "e411466fadaf824b50e2aa8d2e544953d379f24858adcc46eb1c2dd2e85fd437",
          "sha1": "8dabdbbfc6ad4013ce397d7a22591e37d742dbaf",
          "md5": "33dbe414e7643281d6a87510e4bd1f32"
        }
      ]
    }
  ]
}
