{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-grok",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jruby.joni",
          "module": "joni",
          "version": {
            "requires": "2.1.29"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jruby.jcodings",
          "module": "jcodings",
          "version": {
            "requires": "1.0.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-grok-1.0.0-alpha2.jar",
          "url": "opensearch-grok-1.0.0-alpha2.jar",
          "size": 48253,
          "sha512": "f0e5ca759d854fab20e0e1d33099fd00f81a0c43746f333657252886b6263c904d901d662cb5ee7f49b3db64ef2c44f6d88404310fae2b40230c64c5a7ddf063",
          "sha256": "fd1e41e993e87cbff2e486d57cd35ea0be0f4c0271920f8908748ad0fe96f5ec",
          "sha1": "563196d227a065d655061661d678f5f8eb6d9ac1",
          "md5": "860cd9acc56602410320cfbefb140dd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jruby.joni",
          "module": "joni",
          "version": {
            "requires": "2.1.29"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jruby.jcodings",
          "module": "jcodings",
          "version": {
            "requires": "1.0.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-grok-1.0.0-alpha2.jar",
          "url": "opensearch-grok-1.0.0-alpha2.jar",
          "size": 48253,
          "sha512": "f0e5ca759d854fab20e0e1d33099fd00f81a0c43746f333657252886b6263c904d901d662cb5ee7f49b3db64ef2c44f6d88404310fae2b40230c64c5a7ddf063",
          "sha256": "fd1e41e993e87cbff2e486d57cd35ea0be0f4c0271920f8908748ad0fe96f5ec",
          "sha1": "563196d227a065d655061661d678f5f8eb6d9ac1",
          "md5": "860cd9acc56602410320cfbefb140dd3"
        }
      ]
    }
  ]
}
