{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-ukrainian",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-morfologik",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-stemming",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-fsa",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "ua.net.nlp",
          "module": "morfologik-ukrainian-search",
          "version": {
            "requires": "3.7.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-ukrainian-1.0.0-alpha1.jar",
          "url": "analysis-ukrainian-1.0.0-alpha1.jar",
          "size": 7756,
          "sha512": "82bec2d3cdaf9cdb00b8f00daf571b9a09bd52a112fbda4e1334b8aea6ae2dd941e7674399d582e27180108c934b9d95bbe8b4fa6d801f98c321007e8cf8efbc",
          "sha256": "0033a7ee4bfe7b2309b9d988596fc84f511659d16a4b2717419e873313cffd64",
          "sha1": "77c0dc37d1200029aeda14d951f9a462cc4fe14d",
          "md5": "1ffa032459fbd19301f26c6b4ac0d2a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-morfologik",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-stemming",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-fsa",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "ua.net.nlp",
          "module": "morfologik-ukrainian-search",
          "version": {
            "requires": "3.7.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-ukrainian-1.0.0-alpha1.jar",
          "url": "analysis-ukrainian-1.0.0-alpha1.jar",
          "size": 7756,
          "sha512": "82bec2d3cdaf9cdb00b8f00daf571b9a09bd52a112fbda4e1334b8aea6ae2dd941e7674399d582e27180108c934b9d95bbe8b4fa6d801f98c321007e8cf8efbc",
          "sha256": "0033a7ee4bfe7b2309b9d988596fc84f511659d16a4b2717419e873313cffd64",
          "sha1": "77c0dc37d1200029aeda14d951f9a462cc4fe14d",
          "md5": "1ffa032459fbd19301f26c6b4ac0d2a5"
        }
      ]
    }
  ]
}
