{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "store-smb",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "store-smb-1.0.0-beta1.jar",
          "url": "store-smb-1.0.0-beta1.jar",
          "size": 11387,
          "sha512": "6a010b373aec404c3d66eb3e8bad3dc4ecb4e39a77eb6b11e95e9228691dc332092f09e297aa7819a0b0f47d030f25aefa9f0c991103162cd7352295dd562849",
          "sha256": "3745008837d512f3ff98411d3feb7e61c95cc0a349c23b75d280eebb869f5605",
          "sha1": "adcfc5229086a4f099e32b57cfb4200ba76028b7",
          "md5": "f94e7a4534bebf423ce20112f3ce4796"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "store-smb-1.0.0-beta1.jar",
          "url": "store-smb-1.0.0-beta1.jar",
          "size": 11387,
          "sha512": "6a010b373aec404c3d66eb3e8bad3dc4ecb4e39a77eb6b11e95e9228691dc332092f09e297aa7819a0b0f47d030f25aefa9f0c991103162cd7352295dd562849",
          "sha256": "3745008837d512f3ff98411d3feb7e61c95cc0a349c23b75d280eebb869f5605",
          "sha1": "adcfc5229086a4f099e32b57cfb4200ba76028b7",
          "md5": "f94e7a4534bebf423ce20112f3ce4796"
        }
      ]
    }
  ]
}
