{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-plugin-cli",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-fips",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bc-fips",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-plugin-cli-1.0.0-beta1.jar",
          "url": "opensearch-plugin-cli-1.0.0-beta1.jar",
          "size": 34680,
          "sha512": "0e8a56f242fc58eaf85597652ac81a9098c34b24a1732408394977e6f9a580bf15bc424d4f58f5ce0332a16d3ce4d162e87e0a14537028cf1dda91dcd7bc8f55",
          "sha256": "e77a21f92f612eee68e589be132d280cb9c30ae7fb652d80134948d40d0987cf",
          "sha1": "f161d64f8f53f58cbadc92c4c632c90b3369f24a",
          "md5": "3c1ace480389813866f83d51546d1e43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-fips",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bc-fips",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-plugin-cli-1.0.0-beta1.jar",
          "url": "opensearch-plugin-cli-1.0.0-beta1.jar",
          "size": 34680,
          "sha512": "0e8a56f242fc58eaf85597652ac81a9098c34b24a1732408394977e6f9a580bf15bc424d4f58f5ce0332a16d3ce4d162e87e0a14537028cf1dda91dcd7bc8f55",
          "sha256": "e77a21f92f612eee68e589be132d280cb9c30ae7fb652d80134948d40d0987cf",
          "sha1": "f161d64f8f53f58cbadc92c4c632c90b3369f24a",
          "md5": "3c1ace480389813866f83d51546d1e43"
        }
      ]
    }
  ]
}
