{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "aggs-matrix-stats-client",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aggs-matrix-stats-client-1.0.0-alpha1.jar",
          "url": "aggs-matrix-stats-client-1.0.0-alpha1.jar",
          "size": 57847,
          "sha512": "b400b0e59fce2cc520b580e3681ae6979014c6d46770ead49e415fe0117db45a72d4d3eff00ad45b05e941f603b284640000aa553295af801dffd28ce6a11f64",
          "sha256": "d1582dbdce98c83fb7fd56b3c20e594ce428f2ea4fd64b6d30bf76a13ac6d8d6",
          "sha1": "7aa894c028a252074e4477f39db211a226a5807c",
          "md5": "4b3eea1edd97620204049b5795eb3522"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aggs-matrix-stats-client-1.0.0-alpha1.jar",
          "url": "aggs-matrix-stats-client-1.0.0-alpha1.jar",
          "size": 57847,
          "sha512": "b400b0e59fce2cc520b580e3681ae6979014c6d46770ead49e415fe0117db45a72d4d3eff00ad45b05e941f603b284640000aa553295af801dffd28ce6a11f64",
          "sha256": "d1582dbdce98c83fb7fd56b3c20e594ce428f2ea4fd64b6d30bf76a13ac6d8d6",
          "sha1": "7aa894c028a252074e4477f39db211a226a5807c",
          "md5": "4b3eea1edd97620204049b5795eb3522"
        }
      ]
    }
  ]
}
