routing-pipeline:
  workers: 4
  delay: 10
  source:
    in_memory:
      testing_key: ConditionalRoutingIT
  buffer:
    bounded_blocking:
      # Use a small batch size to help ensure that multiple threads
      # are picking up the different routes.
      batch_size: 10
  route:
    - alpha: '/value == "a"'
    - beta: '/value == "b"'
    - gamma: '/value == "g"'
  sink:
    - in_memory:
        testing_key: ConditionalRoutingIT_alpha
        routes:
          - alpha
    - in_memory:
        testing_key: ConditionalRoutingIT_beta
        routes:
          - beta
    - in_memory:
        testing_key: ConditionalRoutingIT_alpha_default
        routes:
          - alpha
          - _default
    - in_memory:
        testing_key: ConditionalRoutingIT_alpha_beta_gamma
        routes:
          - alpha
          - beta
          - gamma
    - in_memory:
        testing_key: ConditionalRoutingIT_default
        routes:
          - _default
    - in_memory:
        testing_key: ConditionalRoutingIT_all
