{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "keystore-cli",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "keystore-cli-1.0.0-beta1.jar",
          "url": "keystore-cli-1.0.0-beta1.jar",
          "size": 16229,
          "sha512": "1fdd012730077a3f201926c9bf813e9333a618dc670430595e4c60f7c17fcbf0aac24aec8e70fde18bbd3ca36c2e2ea2cdf17683bf4bf6bd9deb10889791e59b",
          "sha256": "47d4381746b904e72dbb97f0a2f2e8d11a73088b0e999a8e0b1042a3483d626a",
          "sha1": "c83efd4b8a40979aad5a17e51b2f9151e171ed1e",
          "md5": "2b250a6d81025f7c6422d745c0814916"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "keystore-cli-1.0.0-beta1.jar",
          "url": "keystore-cli-1.0.0-beta1.jar",
          "size": 16229,
          "sha512": "1fdd012730077a3f201926c9bf813e9333a618dc670430595e4c60f7c17fcbf0aac24aec8e70fde18bbd3ca36c2e2ea2cdf17683bf4bf6bd9deb10889791e59b",
          "sha256": "47d4381746b904e72dbb97f0a2f2e8d11a73088b0e999a8e0b1042a3483d626a",
          "sha1": "c83efd4b8a40979aad5a17e51b2f9151e171ed1e",
          "md5": "2b250a6d81025f7c6422d745c0814916"
        }
      ]
    }
  ]
}
