{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-annotated-text",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-annotated-text-1.0.0-alpha2.jar",
          "url": "mapper-annotated-text-1.0.0-alpha2.jar",
          "size": 32816,
          "sha512": "08d3c676ffaf327f140816fb9aad530e346215be5739135eaf8cf6628d7786d46a07818ad1882466eabe934dc4856a5abfac150b37cd24eee7c9cf4bcb2d8beb",
          "sha256": "b84601044824fa252046740c8abf106c7b90bd7b23577fe1e523c3a6708a6339",
          "sha1": "78d9e080ed021c9f02af9c53b2641185f19b957f",
          "md5": "8281e837932406367f98cd6a1e49deb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-annotated-text-1.0.0-alpha2.jar",
          "url": "mapper-annotated-text-1.0.0-alpha2.jar",
          "size": 32816,
          "sha512": "08d3c676ffaf327f140816fb9aad530e346215be5739135eaf8cf6628d7786d46a07818ad1882466eabe934dc4856a5abfac150b37cd24eee7c9cf4bcb2d8beb",
          "sha256": "b84601044824fa252046740c8abf106c7b90bd7b23577fe1e523c3a6708a6339",
          "sha1": "78d9e080ed021c9f02af9c53b2641185f19b957f",
          "md5": "8281e837932406367f98cd6a1e49deb4"
        }
      ]
    }
  ]
}
