{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "keystore-cli",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "keystore-cli-1.0.0-alpha1.jar",
          "url": "keystore-cli-1.0.0-alpha1.jar",
          "size": 16233,
          "sha512": "136a8adc3fcd7136301e3d1405740cb9fa01190d5cb220c4b124159c4ccb65713154187f5da2c95f13643425d1d50f0d716537b1f4e9a7f5a30f7c9e10cacb3d",
          "sha256": "db2cd1aaa06196f52a20426a930cf3cf59b76ffe094a14856f4bbbcaf6f8b7f4",
          "sha1": "9ac1e66f2e231e57d21e3c3cbc03827c6abd015b",
          "md5": "c859a04bb381533dc58de459e8d2ed63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "keystore-cli-1.0.0-alpha1.jar",
          "url": "keystore-cli-1.0.0-alpha1.jar",
          "size": 16233,
          "sha512": "136a8adc3fcd7136301e3d1405740cb9fa01190d5cb220c4b124159c4ccb65713154187f5da2c95f13643425d1d50f0d716537b1f4e9a7f5a30f7c9e10cacb3d",
          "sha256": "db2cd1aaa06196f52a20426a930cf3cf59b76ffe094a14856f4bbbcaf6f8b7f4",
          "sha1": "9ac1e66f2e231e57d21e3c3cbc03827c6abd015b",
          "md5": "c859a04bb381533dc58de459e8d2ed63"
        }
      ]
    }
  ]
}
