{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-icu-client",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-icu",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "62.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-icu-client-1.0.0-alpha2.jar",
          "url": "analysis-icu-client-1.0.0-alpha2.jar",
          "size": 42462,
          "sha512": "ead8c1f1d018d5ef22a5586277f966669e9d165531bef34d8bd48f299de541bff9c2b55e528f3807edbccc9dcb4e6c2b123838d1cc3a571f718f2eec798a5eef",
          "sha256": "abe0ef16f51efe5a498995167cd1ceac116e94ec7d4d0a259b7af29fcf70725c",
          "sha1": "c2204ff80726146e533b5d9db3fcbbc625e744ec",
          "md5": "73ba91545290ce51486c465fe4f1db43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-icu",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "62.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-icu-client-1.0.0-alpha2.jar",
          "url": "analysis-icu-client-1.0.0-alpha2.jar",
          "size": 42462,
          "sha512": "ead8c1f1d018d5ef22a5586277f966669e9d165531bef34d8bd48f299de541bff9c2b55e528f3807edbccc9dcb4e6c2b123838d1cc3a571f718f2eec798a5eef",
          "sha256": "abe0ef16f51efe5a498995167cd1ceac116e94ec7d4d0a259b7af29fcf70725c",
          "sha1": "c2204ff80726146e533b5d9db3fcbbc625e744ec",
          "md5": "73ba91545290ce51486c465fe4f1db43"
        }
      ]
    }
  ]
}
