{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "repository-azure",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-storage",
          "version": {
            "requires": "8.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-keyvault-core",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "repository-azure-1.0.0-beta1.jar",
          "url": "repository-azure-1.0.0-beta1.jar",
          "size": 43513,
          "sha512": "a92385cce52900ed12727717fb990da4a570f197d3abde80e0f4bae829fdf0f9acb4222e8015495ff91f3f9de319a7e271b336f3e786358dbbf61f011b17eae3",
          "sha256": "7d8412607b2ff1ffbf097324bb798e7fe1ad5775ee6353a308e7dea2c04089c9",
          "sha1": "06c190adda090477515041bb1c8337512225d1f8",
          "md5": "9e276b8e1c243c2dd334d0186bf7ebf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-storage",
          "version": {
            "requires": "8.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-keyvault-core",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "repository-azure-1.0.0-beta1.jar",
          "url": "repository-azure-1.0.0-beta1.jar",
          "size": 43513,
          "sha512": "a92385cce52900ed12727717fb990da4a570f197d3abde80e0f4bae829fdf0f9acb4222e8015495ff91f3f9de319a7e271b336f3e786358dbbf61f011b17eae3",
          "sha256": "7d8412607b2ff1ffbf097324bb798e7fe1ad5775ee6353a308e7dea2c04089c9",
          "sha1": "06c190adda090477515041bb1c8337512225d1f8",
          "md5": "9e276b8e1c243c2dd334d0186bf7ebf8"
        }
      ]
    }
  ]
}
