{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-dissect",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-dissect-1.0.0-beta1.jar",
          "url": "opensearch-dissect-1.0.0-beta1.jar",
          "size": 24583,
          "sha512": "169402babbce28cbe3a4a2a1a8ef284f0bfafb756da90f898e3c7a795a1924d4e94fc84dd396ed22d2513b483b04dbe763699b27f1ef63bd8b896a9a538a7f60",
          "sha256": "b4547e5d4e7e8c97273a4daaf9736731b63ae99a68b30d2f9b532cc604dd8986",
          "sha1": "dbc00638923e9019a83e97c53d6fe25aeab0ebfa",
          "md5": "040866fd2e510b0a668db1c449a8c76a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-dissect-1.0.0-beta1.jar",
          "url": "opensearch-dissect-1.0.0-beta1.jar",
          "size": 24583,
          "sha512": "169402babbce28cbe3a4a2a1a8ef284f0bfafb756da90f898e3c7a795a1924d4e94fc84dd396ed22d2513b483b04dbe763699b27f1ef63bd8b896a9a538a7f60",
          "sha256": "b4547e5d4e7e8c97273a4daaf9736731b63ae99a68b30d2f9b532cc604dd8986",
          "sha1": "dbc00638923e9019a83e97c53d6fe25aeab0ebfa",
          "md5": "040866fd2e510b0a668db1c449a8c76a"
        }
      ]
    }
  ]
}
