{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-cli",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-cli-1.0.0-alpha2.jar",
          "url": "opensearch-cli-1.0.0-alpha2.jar",
          "size": 17954,
          "sha512": "60b7a11f3df80ea9d8d1f8e897bfd8ba2320d0d5961182bcc6cb982415bae631f105096c8ab210dc5c6016f1fc5b6b43979cd0cf42b822678f1550ba16977973",
          "sha256": "bace98a7c58a5d6e2887266d8c25ed4464fd5ec932482cf5217673c0e2e4ecc0",
          "sha1": "2fdb56f475cd1430fe691c2381f0a07148acc6fe",
          "md5": "badeb3cf6d39bc42cfabbe79af5ad228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "opensearch-cli-1.0.0-alpha2.jar",
          "url": "opensearch-cli-1.0.0-alpha2.jar",
          "size": 17954,
          "sha512": "60b7a11f3df80ea9d8d1f8e897bfd8ba2320d0d5961182bcc6cb982415bae631f105096c8ab210dc5c6016f1fc5b6b43979cd0cf42b822678f1550ba16977973",
          "sha256": "bace98a7c58a5d6e2887266d8c25ed4464fd5ec932482cf5217673c0e2e4ecc0",
          "sha1": "2fdb56f475cd1430fe691c2381f0a07148acc6fe",
          "md5": "badeb3cf6d39bc42cfabbe79af5ad228"
        }
      ]
    }
  ]
}
