{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "die-with-dignity",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "die-with-dignity-1.0.0-alpha2.jar",
          "url": "die-with-dignity-1.0.0-alpha2.jar",
          "size": 7118,
          "sha512": "b2bd4fb3c4cb32e379a0f539cf13aefe9449a7d644d2b5dc87c1943fa06fddacbd0875127d76149013eab88537af99d7781239fc977c3ac66b674b227e05cbe5",
          "sha256": "ee2dffeb252e91a42d3d7a4633fb58a84b25681bb5ab87078cac97b91e3c7734",
          "sha1": "25c7ea4fefcb89a5a17c1cb800a0b7e0e687dee3",
          "md5": "56eb82c2ce85ec3e10989702e8423b99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "die-with-dignity-1.0.0-alpha2.jar",
          "url": "die-with-dignity-1.0.0-alpha2.jar",
          "size": 7118,
          "sha512": "b2bd4fb3c4cb32e379a0f539cf13aefe9449a7d644d2b5dc87c1943fa06fddacbd0875127d76149013eab88537af99d7781239fc977c3ac66b674b227e05cbe5",
          "sha256": "ee2dffeb252e91a42d3d7a4633fb58a84b25681bb5ab87078cac97b91e3c7734",
          "sha1": "25c7ea4fefcb89a5a17c1cb800a0b7e0e687dee3",
          "md5": "56eb82c2ce85ec3e10989702e8423b99"
        }
      ]
    }
  ]
}
