{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "custom-settings",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "custom-settings-1.0.0-alpha2.jar",
          "url": "custom-settings-1.0.0-alpha2.jar",
          "size": 9888,
          "sha512": "92fbe14b512084bd4a84e0018b15c706bda0175e67193d8028ff16342f6484f8a9c1235e64752046f31bfe52ad27df554248a534234ec43e6f0461defc9f8c1f",
          "sha256": "ffd7ade44771d5f4d94bf168f2295af3577da74770794bb479e9c87bb5abd28f",
          "sha1": "c5b21d493c3e893f98f6f91502d88142a479f7f8",
          "md5": "9d994232991e20c11304c1650d12eaa7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-settings-1.0.0-alpha2.jar",
          "url": "custom-settings-1.0.0-alpha2.jar",
          "size": 9888,
          "sha512": "92fbe14b512084bd4a84e0018b15c706bda0175e67193d8028ff16342f6484f8a9c1235e64752046f31bfe52ad27df554248a534234ec43e6f0461defc9f8c1f",
          "sha256": "ffd7ade44771d5f4d94bf168f2295af3577da74770794bb479e9c87bb5abd28f",
          "sha1": "c5b21d493c3e893f98f6f91502d88142a479f7f8",
          "md5": "9d994232991e20c11304c1650d12eaa7"
        }
      ]
    }
  ]
}
