{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.test",
    "module": "framework",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client-sniffer",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-nio",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-cli",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-test-framework",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-codecs",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch",
          "module": "securemock",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch",
          "module": "mocksocket",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "framework-1.0.0-alpha2.jar",
          "url": "framework-1.0.0-alpha2.jar",
          "size": 1350768,
          "sha512": "da1c10677e219517432281f455e3ee9680a1884ed223be559c318cfae4117e04abfa49efe92bd955f094eee8e4404660269f4edbcd208049e378d401c1a25a27",
          "sha256": "b2068908d36a4bfe1f96be53b844ee782d724eb7702cf60d7648a6ab3c1a6cf3",
          "sha1": "f1602a513ec585c2a1ef327ae2380e563453c167",
          "md5": "fc83151429e2655b1262a86f2af647a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch.client",
          "module": "opensearch-rest-client-sniffer",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-nio",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-cli",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-test-framework",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-codecs",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch",
          "module": "securemock",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch",
          "module": "mocksocket",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "framework-1.0.0-alpha2.jar",
          "url": "framework-1.0.0-alpha2.jar",
          "size": 1350768,
          "sha512": "da1c10677e219517432281f455e3ee9680a1884ed223be559c318cfae4117e04abfa49efe92bd955f094eee8e4404660269f4edbcd208049e378d401c1a25a27",
          "sha256": "b2068908d36a4bfe1f96be53b844ee782d724eb7702cf60d7648a6ab3c1a6cf3",
          "sha1": "f1602a513ec585c2a1ef327ae2380e563453c167",
          "md5": "fc83151429e2655b1262a86f2af647a6"
        }
      ]
    }
  ]
}
