/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 */

package org.opensearch.dataprepper.plugin.osgi;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DataPrepperApiVersionTest {

    @Test
    void resolveVersion_returns_non_null() {
        final String version = DataPrepperApiVersion.resolveVersion();
        assertThat(version, is(notNullValue()));
        assertFalse(version.isEmpty());
    }

    @Test
    void resolveVersion_returns_valid_osgi_format() {
        final String version = DataPrepperApiVersion.resolveVersion();
        // OSGi version: major.minor.micro[.qualifier]
        assertTrue(version.matches("\\d+\\.\\d+\\.\\d+(\\.\\w+)?"),
                "Version '" + version + "' is not in valid OSGi format");
    }

    @Test
    void resolveVersion_does_not_contain_snapshot() {
        final String version = DataPrepperApiVersion.resolveVersion();
        assertFalse(version.contains("SNAPSHOT"),
                "OSGi version should not contain SNAPSHOT: " + version);
        assertFalse(version.contains("-"),
                "OSGi version should not contain hyphens: " + version);
    }

    @ParameterizedTest
    @CsvSource({
            "2.15.0, 2.15.0",
            "2.15.0-SNAPSHOT, 2.15.0",
            "2.16.0-SNAPSHOT, 2.16.0",
            "3.0.0-SNAPSHOT, 3.0.0",
            "2.15, 2.15.0",
            "1.0.0, 1.0.0",
            "2.15.1-beta1, 2.15.1.beta1",
            "2.15.0-RC1, 2.15.0.RC1",
            "2.15.0-rc.2, 2.15.0.rc2"
    })
    void toOsgiVersion_converts_correctly(final String input, final String expected) {
        assertThat(DataPrepperApiVersion.toOsgiVersion(input), is(expected));
    }

    @ParameterizedTest
    @CsvSource({
            "'', 2.15.0",
            "invalid, 2.15.0",
            "abc.def.ghi, 2.15.0"
    })
    void toOsgiVersion_returns_fallback_for_invalid_input(final String input, final String expected) {
        assertThat(DataPrepperApiVersion.toOsgiVersion(input), is(expected));
    }

    @Test
    void toOsgiVersion_returns_fallback_for_null() {
        assertThat(DataPrepperApiVersion.toOsgiVersion(null), is(DataPrepperApiVersion.FALLBACK_VERSION));
    }

    @ParameterizedTest
    @CsvSource({
            "2.15.0, '[2.15.0,3.0.0)'",
            "2.16.0, '[2.16.0,3.0.0)'",
            "3.0.0, '[3.0.0,4.0.0)'",
            "1.5.2, '[1.5.2,2.0.0)'"
    })
    void computeImportRange_generates_correct_range(final String version, final String expectedRange) {
        assertThat(DataPrepperApiVersion.computeImportRange(version), is(expectedRange));
    }

    @Test
    void computeImportRange_handles_invalid_version() {
        final String range = DataPrepperApiVersion.computeImportRange("invalid");
        // Should use fallback version to compute range
        assertThat(range, is("[2.15.0,3.0.0)"));
    }

    @Test
    void readManifestVersion_handles_missing_class_gracefully() {
        // In test environment, the Event class may or may not have an Implementation-Version
        // but the method should not throw
        final String version = DataPrepperApiVersion.readManifestVersion();
        // May return null if manifest doesn't have Implementation-Version — that's OK
        if (version != null) {
            assertFalse(version.isEmpty());
        }
    }

    @Test
    void readResourceVersion_returns_version_when_resource_present() {
        // In the test environment with generated resources, this should find the version
        final String version = DataPrepperApiVersion.readResourceVersion();
        // The resource should be generated by the gradle build
        if (version != null) {
            assertFalse(version.isEmpty());
            assertTrue(version.matches("\\d+\\.\\d+\\.\\d+.*"),
                    "Resource version should be a valid version string: " + version);
        }
    }

    @Test
    void fallback_version_is_valid_osgi_format() {
        assertTrue(DataPrepperApiVersion.FALLBACK_VERSION.matches("\\d+\\.\\d+\\.\\d+"),
                "Fallback version must be in valid OSGi format");
    }
}
