{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.client.test",
    "module": "test",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-1.0.0-alpha2.jar",
          "url": "test-1.0.0-alpha2.jar",
          "size": 9534,
          "sha512": "ed9c6572bd40ecee17bb56dfaeebe47b54939dff36b8b517dd64087f2127ad3d5b3a2161cf412421ca27b34875bd2e40b7a214847a4a9ebfa922c65aab3bfa16",
          "sha256": "3c1890203d162f37f4e4e84185c54f79545719a6687075001489872ffc2e67cd",
          "sha1": "3cc30d452e189279409830f77950d74ac0df0a56",
          "md5": "e02c798a1acc0221ae85ea8edd3f2bc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.carrotsearch.randomizedtesting",
          "module": "randomizedtesting-runner",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-1.0.0-alpha2.jar",
          "url": "test-1.0.0-alpha2.jar",
          "size": 9534,
          "sha512": "ed9c6572bd40ecee17bb56dfaeebe47b54939dff36b8b517dd64087f2127ad3d5b3a2161cf412421ca27b34875bd2e40b7a214847a4a9ebfa922c65aab3bfa16",
          "sha256": "3c1890203d162f37f4e4e84185c54f79545719a6687075001489872ffc2e67cd",
          "sha1": "3cc30d452e189279409830f77950d74ac0df0a56",
          "md5": "e02c798a1acc0221ae85ea8edd3f2bc1"
        }
      ]
    }
  ]
}
