{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "parent-join-client",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parent-join-client-1.0.0-alpha2.jar",
          "url": "parent-join-client-1.0.0-alpha2.jar",
          "size": 87351,
          "sha512": "b8b56de93579067725e432f991f514cbfd553e40c18ad8db74a62445a099771134d00259ed7646ef27780d070f53824e9713ec86e518710a19a21eea94a9d64c",
          "sha256": "6f0970b373e1507883380c151df8bf457a94603f7248b22b01cb85e655a3bb01",
          "sha1": "686a254f660a4c16490ed2324d15840f0810b7d5",
          "md5": "97b72e0f2f9250f427c86252f14c6c80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-join-client-1.0.0-alpha2.jar",
          "url": "parent-join-client-1.0.0-alpha2.jar",
          "size": 87351,
          "sha512": "b8b56de93579067725e432f991f514cbfd553e40c18ad8db74a62445a099771134d00259ed7646ef27780d070f53824e9713ec86e518710a19a21eea94a9d64c",
          "sha256": "6f0970b373e1507883380c151df8bf457a94603f7248b22b01cb85e655a3bb01",
          "sha1": "686a254f660a4c16490ed2324d15840f0810b7d5",
          "md5": "97b72e0f2f9250f427c86252f14c6c80"
        }
      ]
    }
  ]
}
