/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package org.opensearch.dataprepper.plugins.processor.obfuscation.action;

import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;

import jakarta.validation.constraints.Pattern;


public class OneWayHashActionConfig {


    @JsonProperty("salt")
    @JsonPropertyDescription("Salt value to use when generating hash. If not specified, salt will be randomly generated by the processor.")
    private byte[] salt;

    @JsonProperty("format")
    @Pattern(regexp = "SHA-512", message = "Valid values: SHA-512")
    @JsonPropertyDescription("Format of one way hash to generate. Default to SHA-512.")
    private String hashFormat = "SHA-512";

    @JsonProperty("salt_key")
    @JsonPropertyDescription("A key to compute salt based on a value provided as part of a record." + 
        "If key or value was not found in the record(s), a salt defined in the pipeline configuration will be used instead.")
    private String saltKey;

    public OneWayHashActionConfig() {        
        this.salt = generateSalt();   
    }

    public OneWayHashActionConfig(String hashFormat, String salt, String saltKey) {

        this.hashFormat = hashFormat;
        this.saltKey = saltKey;

        if (salt == null || salt.isEmpty() ) {
            this.salt = generateSalt();
        } else {
            this.salt = salt.getBytes(StandardCharsets.UTF_8);
        }
    }

    public OneWayHashActionConfig(String salt) {
        this.salt = salt.getBytes(StandardCharsets.UTF_8);
    }

    public byte [] getSalt (){
        return salt;
    }

    public String getHashFormat(){
        return hashFormat;
    }

    public String getSaltKey(){
        return saltKey;
    }

    private byte[] generateSalt(){
        byte [] saltBytes = new byte[64];
        SecureRandom secureRandom = new SecureRandom();
        secureRandom.nextBytes(saltBytes);        
        return saltBytes;
    }
}

