{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-icu-client",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-icu",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "62.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-icu-client-1.0.0-alpha1.jar",
          "url": "analysis-icu-client-1.0.0-alpha1.jar",
          "size": 42465,
          "sha512": "edfce9118007bdc6782cbbdf5df200b6ab17ff8956e234d6e5a48d2e5aa75c7c48ec608e7cd8197f730de2ee7715ad7f9819211ccc0cfc78d457848efc970573",
          "sha256": "be525bfd29adeb76771a9a8d7c1a9c9205ceba5335749589db8839ea6e869a26",
          "sha1": "5eaaef338c9bb5c636cd800e568386104be6799d",
          "md5": "3d52b8a3a4ca55da95cb24bfcb8c0ad3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-icu",
          "version": {
            "requires": "8.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "62.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-icu-client-1.0.0-alpha1.jar",
          "url": "analysis-icu-client-1.0.0-alpha1.jar",
          "size": 42465,
          "sha512": "edfce9118007bdc6782cbbdf5df200b6ab17ff8956e234d6e5a48d2e5aa75c7c48ec608e7cd8197f730de2ee7715ad7f9819211ccc0cfc78d457848efc970573",
          "sha256": "be525bfd29adeb76771a9a8d7c1a9c9205ceba5335749589db8839ea6e869a26",
          "sha1": "5eaaef338c9bb5c636cd800e568386104be6799d",
          "md5": "3d52b8a3a4ca55da95cb24bfcb8c0ad3"
        }
      ]
    }
  ]
}
