{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "custom-significance-heuristic",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "custom-significance-heuristic-1.0.0-alpha1.jar",
          "url": "custom-significance-heuristic-1.0.0-alpha1.jar",
          "size": 7938,
          "sha512": "5f331870583903cae1e86dde85c5835c855d4e5bf1689a784e97e83d86718aae1612c60836921f1c42cfd8b9e468db321abb72e92ea343ed382a67bf862e4286",
          "sha256": "24c33180fecdd9aeedcff866a1c336f734bfebd3f804acdb46dd49dc5bbe060d",
          "sha1": "c7e587b579371db955053131fa7d712299b5ec26",
          "md5": "45960d869a7062df4fa9195b27fe6ca7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-significance-heuristic-1.0.0-alpha1.jar",
          "url": "custom-significance-heuristic-1.0.0-alpha1.jar",
          "size": 7938,
          "sha512": "5f331870583903cae1e86dde85c5835c855d4e5bf1689a784e97e83d86718aae1612c60836921f1c42cfd8b9e468db321abb72e92ea343ed382a67bf862e4286",
          "sha256": "24c33180fecdd9aeedcff866a1c336f734bfebd3f804acdb46dd49dc5bbe060d",
          "sha1": "c7e587b579371db955053131fa7d712299b5ec26",
          "md5": "45960d869a7062df4fa9195b27fe6ca7"
        }
      ]
    }
  ]
}
