{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-ukrainian",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-morfologik",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-stemming",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-fsa",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "ua.net.nlp",
          "module": "morfologik-ukrainian-search",
          "version": {
            "requires": "3.7.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-ukrainian-1.0.0-alpha2.jar",
          "url": "analysis-ukrainian-1.0.0-alpha2.jar",
          "size": 7752,
          "sha512": "2b86256f7c42a5d77049639fdb8aa687dc8acb925a0cecc24c5f60c68e636d8b53cecc54d009a459496bdc8533ed1bf823ab307a460fdcb8c085522886f78737",
          "sha256": "756450c150df94540454bc5eca43af8ea08112e1c0053dd07cd3dab47de5d4a0",
          "sha1": "ed4480b7a31ed021c64e9fa8a13e010bd1d13a36",
          "md5": "df7b6b7db949e6fe43b6fe1f11246029"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-morfologik",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-stemming",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.carrot2",
          "module": "morfologik-fsa",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "ua.net.nlp",
          "module": "morfologik-ukrainian-search",
          "version": {
            "requires": "3.7.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-ukrainian-1.0.0-alpha2.jar",
          "url": "analysis-ukrainian-1.0.0-alpha2.jar",
          "size": 7752,
          "sha512": "2b86256f7c42a5d77049639fdb8aa687dc8acb925a0cecc24c5f60c68e636d8b53cecc54d009a459496bdc8533ed1bf823ab307a460fdcb8c085522886f78737",
          "sha256": "756450c150df94540454bc5eca43af8ea08112e1c0053dd07cd3dab47de5d4a0",
          "sha1": "ed4480b7a31ed021c64e9fa8a13e010bd1d13a36",
          "md5": "df7b6b7db949e6fe43b6fe1f11246029"
        }
      ]
    }
  ]
}
