{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-icu-client",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-icu",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "62.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-icu-client-1.0.0-beta1.jar",
          "url": "analysis-icu-client-1.0.0-beta1.jar",
          "size": 42464,
          "sha512": "3302e0a233d79516a29a060ebe3ba1f009d0f24d971a144fcbcd7441b836afd71f5b7b20e32d6f456df4d630b322f1bc90e5bc244395128250ddc2e0c24a150e",
          "sha256": "f1d40f5baebc13c2e23713d6a9752e077a1348e5c11502d3b129b516fef89c0e",
          "sha1": "a64d177ff1b5e0f8003909f6139e474d41f60343",
          "md5": "1efb96a357cb128329e18a4ff2cdbee0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-icu",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "62.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-icu-client-1.0.0-beta1.jar",
          "url": "analysis-icu-client-1.0.0-beta1.jar",
          "size": 42464,
          "sha512": "3302e0a233d79516a29a060ebe3ba1f009d0f24d971a144fcbcd7441b836afd71f5b7b20e32d6f456df4d630b322f1bc90e5bc244395128250ddc2e0c24a150e",
          "sha256": "f1d40f5baebc13c2e23713d6a9752e077a1348e5c11502d3b129b516fef89c0e",
          "sha1": "a64d177ff1b5e0f8003909f6139e474d41f60343",
          "md5": "1efb96a357cb128329e18a4ff2cdbee0"
        }
      ]
    }
  ]
}
