{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-geoip",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.maxmind.geoip2",
          "module": "geoip2",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.maxmind.db",
          "module": "maxmind-db",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ingest-geoip-1.0.0-alpha2.jar",
          "url": "ingest-geoip-1.0.0-alpha2.jar",
          "size": 27520,
          "sha512": "0a77a6583a9ef3d342627f5ce21f212ed22302f727bfca51c101ae853049d3cdfcd3f951e9f5130d1c7a53a4967026cf012e4e79e90ee56eeef4cd1371f676fc",
          "sha256": "b74f12fab29a793dc99b7ce5cecfa14293e9bc405318ea314355d5929ccfcd22",
          "sha1": "68f2bbdc5f709ff4bc8ab92a5e1ce5657a983b38",
          "md5": "6e1018164deb9fce4f243481508ef6ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.maxmind.geoip2",
          "module": "geoip2",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.maxmind.db",
          "module": "maxmind-db",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ingest-geoip-1.0.0-alpha2.jar",
          "url": "ingest-geoip-1.0.0-alpha2.jar",
          "size": 27520,
          "sha512": "0a77a6583a9ef3d342627f5ce21f212ed22302f727bfca51c101ae853049d3cdfcd3f951e9f5130d1c7a53a4967026cf012e4e79e90ee56eeef4cd1371f676fc",
          "sha256": "b74f12fab29a793dc99b7ce5cecfa14293e9bc405318ea314355d5929ccfcd22",
          "sha1": "68f2bbdc5f709ff4bc8ab92a5e1ce5657a983b38",
          "md5": "6e1018164deb9fce4f243481508ef6ab"
        }
      ]
    }
  ]
}
