{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-murmur3",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-murmur3-1.0.0-beta1.jar",
          "url": "mapper-murmur3-1.0.0-beta1.jar",
          "size": 13016,
          "sha512": "0d51f3f5d3b5593652a41b44aaecb03c772bc371bd8c1416894345031720b336fc3c42d29108b68d45224ffeff1b8d89fc0fd6b62a22ad5630c6a556adaaa63c",
          "sha256": "97a34914e3100c2b297883d3d70c894ef650ebcc4dac7cb79a8e6947975d5d17",
          "sha1": "03f28a08b70eb3adec4aa5589db24fb4b5d521f8",
          "md5": "617a11276d8d15ff10d2c1762e3d0736"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-murmur3-1.0.0-beta1.jar",
          "url": "mapper-murmur3-1.0.0-beta1.jar",
          "size": 13016,
          "sha512": "0d51f3f5d3b5593652a41b44aaecb03c772bc371bd8c1416894345031720b336fc3c42d29108b68d45224ffeff1b8d89fc0fd6b62a22ad5630c6a556adaaa63c",
          "sha256": "97a34914e3100c2b297883d3d70c894ef650ebcc4dac7cb79a8e6947975d5d17",
          "sha1": "03f28a08b70eb3adec4aa5589db24fb4b5d521f8",
          "md5": "617a11276d8d15ff10d2c1762e3d0736"
        }
      ]
    }
  ]
}
