# https://github.com/bitnami/containers/blob/6e283cd75537c087b3deac9092fe13bfaab53106/bitnami/kafka/docker-compose.yml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  kafka:
    image: docker.io/bitnami/kafka:${KAFKA_VERSION}
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=SASL_SCRAM://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SCRAM://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_SCRAM:SASL_PLAINTEXT
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN,SCRAM-SHA-512
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SCRAM
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-512
      - KAFKA_INTER_BROKER_USER=admin
      - KAFKA_INTER_BROKER_PASSWORD=admin
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CONTROLLER_USER=kcu
      - KAFKA_CONTROLLER_PASSWORD=kcu
    command:
      - /bin/bash
      - -c
      # The server.properties must be altered in this way bc there are no equivalent env vars
      - |
        # We need a new line before the next lines to prevent errors
        echo "" >> /opt/bitnami/kafka/config/server.properties
        echo "authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer" \
          >> /opt/bitnami/kafka/config/server.properties
        echo "super.users=User:admin;User:kcu" >> /opt/bitnami/kafka/config/server.properties
        /opt/bitnami/scripts/kafka/run.sh
