{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "custom-suggester",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "custom-suggester-1.0.0-alpha2.jar",
          "url": "custom-suggester-1.0.0-alpha2.jar",
          "size": 17862,
          "sha512": "4f8e289368c4251eff1298f5480ca8b082140ac7125258220726151e2d21602bd6e695e2f3158a05f0f4ef5e8e353b889656a9248a9536c4b38d8e0bb2d47ce5",
          "sha256": "5208602c4bbb3b3e93049352b1053cf139c117783ffb24c6ae28b88c24250701",
          "sha1": "7cf1691db9c79b10dfb7a77dcdcd99698ca6826e",
          "md5": "c8056d2777d9ac795d992dbb6cdd7797"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-suggester-1.0.0-alpha2.jar",
          "url": "custom-suggester-1.0.0-alpha2.jar",
          "size": 17862,
          "sha512": "4f8e289368c4251eff1298f5480ca8b082140ac7125258220726151e2d21602bd6e695e2f3158a05f0f4ef5e8e353b889656a9248a9536c4b38d8e0bb2d47ce5",
          "sha256": "5208602c4bbb3b3e93049352b1053cf139c117783ffb24c6ae28b88c24250701",
          "sha1": "7cf1691db9c79b10dfb7a77dcdcd99698ca6826e",
          "md5": "c8056d2777d9ac795d992dbb6cdd7797"
        }
      ]
    }
  ]
}
