{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-common",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-grok",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-dissect",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "ingest-common-1.0.0-alpha2.jar",
          "url": "ingest-common-1.0.0-alpha2.jar",
          "size": 118974,
          "sha512": "1d46508b43ea142bd2bea97422fb09417fb2d25589de8dd62367d7b5de6ad9a42466b40f91298f287a82c2c3059ad8cca323eead4014210d9a1050733e9fd3d5",
          "sha256": "bcc6dce116ec7a5100f323b64a0d046277b9d7d9fe8efde72bf84eff383f5e11",
          "sha1": "2c6ebf6b165467ae3d59b583c82b60bde2c300f3",
          "md5": "5bd8162830d647a68ada07a8741c8d64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-grok",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-dissect",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        }
      ],
      "files": [
        {
          "name": "ingest-common-1.0.0-alpha2.jar",
          "url": "ingest-common-1.0.0-alpha2.jar",
          "size": 118974,
          "sha512": "1d46508b43ea142bd2bea97422fb09417fb2d25589de8dd62367d7b5de6ad9a42466b40f91298f287a82c2c3059ad8cca323eead4014210d9a1050733e9fd3d5",
          "sha256": "bcc6dce116ec7a5100f323b64a0d046277b9d7d9fe8efde72bf84eff383f5e11",
          "sha1": "2c6ebf6b165467ae3d59b583c82b60bde2c300f3",
          "md5": "5bd8162830d647a68ada07a8741c8d64"
        }
      ]
    }
  ]
}
