{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "ingest-user-agent",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ingest-user-agent-1.0.0-alpha1.jar",
          "url": "ingest-user-agent-1.0.0-alpha1.jar",
          "size": 65816,
          "sha512": "b2ae9ba880d3346da12391c209b3de22d05e5572cadec064968680e777cbf85c136b6eefeedcaaedc24b17cd81a9f367c703ad8543db2df6546b93805fd228f9",
          "sha256": "2e2995e3fa90e1ad58a58c7f83b3b0908e03ad26a99cec5ceb676feb0334f18e",
          "sha1": "64cff3189f62f0ee61e87cf54c4c3f49cab2d774",
          "md5": "8c794c75a8b85b2308069ca7a02ef97d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ingest-user-agent-1.0.0-alpha1.jar",
          "url": "ingest-user-agent-1.0.0-alpha1.jar",
          "size": 65816,
          "sha512": "b2ae9ba880d3346da12391c209b3de22d05e5572cadec064968680e777cbf85c136b6eefeedcaaedc24b17cd81a9f367c703ad8543db2df6546b93805fd228f9",
          "sha256": "2e2995e3fa90e1ad58a58c7f83b3b0908e03ad26a99cec5ceb676feb0334f18e",
          "sha1": "64cff3189f62f0ee61e87cf54c4c3f49cab2d774",
          "md5": "8c794c75a8b85b2308069ca7a02ef97d"
        }
      ]
    }
  ]
}
