{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "rest-api-spec",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rest-api-spec-1.0.0-beta1.jar",
          "url": "rest-api-spec-1.0.0-beta1.jar",
          "size": 404963,
          "sha512": "c4758d137ef7ee21d735bdb4f5869ba3125a4e69da3f99313f143eb6c83b952fe9271a0b8499644aecbfb91e51870c44369b27983856800fd77301ea369d07ca",
          "sha256": "23de1c4f77795083a0e31384ff1915c490e260d4682b1c77919806f21109f99a",
          "sha1": "0890ae9c5d21fb8da48b9f9ca60a8ca05235052e",
          "md5": "74ec0e82c99028da9a1d52aff8883d7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rest-api-spec-1.0.0-beta1.jar",
          "url": "rest-api-spec-1.0.0-beta1.jar",
          "size": 404963,
          "sha512": "c4758d137ef7ee21d735bdb4f5869ba3125a4e69da3f99313f143eb6c83b952fe9271a0b8499644aecbfb91e51870c44369b27983856800fd77301ea369d07ca",
          "sha256": "23de1c4f77795083a0e31384ff1915c490e260d4682b1c77919806f21109f99a",
          "sha1": "0890ae9c5d21fb8da48b9f9ca60a8ca05235052e",
          "md5": "74ec0e82c99028da9a1d52aff8883d7d"
        }
      ]
    }
  ]
}
