{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-extras-client",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-extras-client-1.0.0-alpha2.jar",
          "url": "mapper-extras-client-1.0.0-alpha2.jar",
          "size": 84245,
          "sha512": "c1d3047da47e755d18baa0321eaf3c3f738a30b468bc2d5c5239cd0ebc71016492635f5ac0bbc410dc12e0c518e37d9d99e23edfa7c25bb057f9475c54ccc64c",
          "sha256": "299881b7edc3d5de953ea427048bfe81c4b6afb089f5cff52a9adfa6bc5fda8e",
          "sha1": "6aaf891d641ed5f2891fff66b6d121706e0a959a",
          "md5": "3088d33e4ec24aa130f50ca4cfde996b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-extras-client-1.0.0-alpha2.jar",
          "url": "mapper-extras-client-1.0.0-alpha2.jar",
          "size": 84245,
          "sha512": "c1d3047da47e755d18baa0321eaf3c3f738a30b468bc2d5c5239cd0ebc71016492635f5ac0bbc410dc12e0c518e37d9d99e23edfa7c25bb057f9475c54ccc64c",
          "sha256": "299881b7edc3d5de953ea427048bfe81c4b6afb089f5cff52a9adfa6bc5fda8e",
          "sha1": "6aaf891d641ed5f2891fff66b6d121706e0a959a",
          "md5": "3088d33e4ec24aa130f50ca4cfde996b"
        }
      ]
    }
  ]
}
