{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-secure-sm",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-secure-sm-1.0.0-beta1.jar",
          "url": "opensearch-secure-sm-1.0.0-beta1.jar",
          "size": 10942,
          "sha512": "cd6566b52cbfd962e67970eb00c4839758c2410238c36f73ec12d1a20c33041c90d193601be98d81252b8f7e1a67c71f334579ed425c8fee89d5d282238ca32e",
          "sha256": "46d6f52d80183cb476b4c8348bd645f98552f741619319e274f16b6b98bcec1e",
          "sha1": "efbad5b82db9f09b8d3ccbed44524953cb0d4808",
          "md5": "5aa04a9e47abce9bb14ea29b566de8fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-secure-sm-1.0.0-beta1.jar",
          "url": "opensearch-secure-sm-1.0.0-beta1.jar",
          "size": 10942,
          "sha512": "cd6566b52cbfd962e67970eb00c4839758c2410238c36f73ec12d1a20c33041c90d193601be98d81252b8f7e1a67c71f334579ed425c8fee89d5d282238ca32e",
          "sha256": "46d6f52d80183cb476b4c8348bd645f98552f741619319e274f16b6b98bcec1e",
          "sha1": "efbad5b82db9f09b8d3ccbed44524953cb0d4808",
          "md5": "5aa04a9e47abce9bb14ea29b566de8fb"
        }
      ]
    }
  ]
}
