{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-murmur3",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-murmur3-1.0.0-alpha1.jar",
          "url": "mapper-murmur3-1.0.0-alpha1.jar",
          "size": 13017,
          "sha512": "79c34b46a03bdc517dfd2a1ffe7964ec4902983a1fd82f710ad0def2cbbff259877e1db88ffaca15ba293c09247bb71bc09efdbfa87203ffb69f261b4cd5bb1f",
          "sha256": "d7fdae4117f174b600880c9d85d8e4ab310379d011cf45507fbebe08c17804f1",
          "sha1": "205f385f5e16c38786f1d2f5483c8217a647c16f",
          "md5": "6dc9bff902df7276ace55a37733b350c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-murmur3-1.0.0-alpha1.jar",
          "url": "mapper-murmur3-1.0.0-alpha1.jar",
          "size": 13017,
          "sha512": "79c34b46a03bdc517dfd2a1ffe7964ec4902983a1fd82f710ad0def2cbbff259877e1db88ffaca15ba293c09247bb71bc09efdbfa87203ffb69f261b4cd5bb1f",
          "sha256": "d7fdae4117f174b600880c9d85d8e4ab310379d011cf45507fbebe08c17804f1",
          "sha1": "205f385f5e16c38786f1d2f5483c8217a647c16f",
          "md5": "6dc9bff902df7276ace55a37733b350c"
        }
      ]
    }
  ]
}
