{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "mapper-size",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "63e7upzp3nclfogys7cwpkr4wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapper-size-1.0.0-beta1.jar",
          "url": "mapper-size-1.0.0-beta1.jar",
          "size": 10448,
          "sha512": "1122f2faa9398db9ebd5e8ae1decbc5e09df0d2c7453fc63979cc2c9adb5d9bbfb5e5143dc41c571163646ad491222cd64383d3b92c82a86167e7d8dcd531a25",
          "sha256": "9e8c0e9344722d10127d80dd346793042c860490663423f09abedfc9c36cb5bb",
          "sha1": "0858b4e7dbfa0814d2ed8403ec86080d4aec0b04",
          "md5": "c09aab18fdaf8331d77243d0d51de278"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapper-size-1.0.0-beta1.jar",
          "url": "mapper-size-1.0.0-beta1.jar",
          "size": 10448,
          "sha512": "1122f2faa9398db9ebd5e8ae1decbc5e09df0d2c7453fc63979cc2c9adb5d9bbfb5e5143dc41c571163646ad491222cd64383d3b92c82a86167e7d8dcd531a25",
          "sha256": "9e8c0e9344722d10127d80dd346793042c860490663423f09abedfc9c36cb5bb",
          "sha1": "0858b4e7dbfa0814d2ed8403ec86080d4aec0b04",
          "md5": "c09aab18fdaf8331d77243d0d51de278"
        }
      ]
    }
  ]
}
