{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-dissect",
    "version": "1.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "lqsgjlfglvgibowtuxgrjfbk5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opensearch-dissect-1.0.0-alpha1.jar",
          "url": "opensearch-dissect-1.0.0-alpha1.jar",
          "size": 24585,
          "sha512": "54331c71dc84a7a5fb7e51b0fbb41c2b90ca1ab84216a5f5a0c1d2a5ea4ecded90d60941dc3da887054828b7df77ca3dc8321b9c9c93e947e59c93c1a34cf4d0",
          "sha256": "57fcf33e9512047238aeabd8b1ce02ebf592b6ff02df3b830ba6ee25a590e6bd",
          "sha1": "4a4ab4c471d2f0c41d16a8e81dba25108396d95d",
          "md5": "7b30f5dfeb83ea0f813af73d55a9cd5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opensearch-dissect-1.0.0-alpha1.jar",
          "url": "opensearch-dissect-1.0.0-alpha1.jar",
          "size": 24585,
          "sha512": "54331c71dc84a7a5fb7e51b0fbb41c2b90ca1ab84216a5f5a0c1d2a5ea4ecded90d60941dc3da887054828b7df77ca3dc8321b9c9c93e947e59c93c1a34cf4d0",
          "sha256": "57fcf33e9512047238aeabd8b1ce02ebf592b6ff02df3b830ba6ee25a590e6bd",
          "sha1": "4a4ab4c471d2f0c41d16a8e81dba25108396d95d",
          "md5": "7b30f5dfeb83ea0f813af73d55a9cd5d"
        }
      ]
    }
  ]
}
