{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "systemd",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "systemd-1.0.0-alpha2.jar",
          "url": "systemd-1.0.0-alpha2.jar",
          "size": 9265,
          "sha512": "7ad0dbd802d6ac9ff44469cce0907623f6247eb88472e22120b75fa63e42b4bfafc1d5e30a9c7940769348f577245272eee9f35f0e267d200caa2b0c78e33084",
          "sha256": "9b20f0b3141b29ccf7a86f7b61866ac4c07e0d5f9dbeb1020fd24dbf43605ff9",
          "sha1": "cc296f9941696280624b244e3aba15fd7cd304c1",
          "md5": "bee68ad2a281fefc4ff61a55a4eb94ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "systemd-1.0.0-alpha2.jar",
          "url": "systemd-1.0.0-alpha2.jar",
          "size": 9265,
          "sha512": "7ad0dbd802d6ac9ff44469cce0907623f6247eb88472e22120b75fa63e42b4bfafc1d5e30a9c7940769348f577245272eee9f35f0e267d200caa2b0c78e33084",
          "sha256": "9b20f0b3141b29ccf7a86f7b61866ac4c07e0d5f9dbeb1020fd24dbf43605ff9",
          "sha1": "cc296f9941696280624b244e3aba15fd7cd304c1",
          "md5": "bee68ad2a281fefc4ff61a55a4eb94ca"
        }
      ]
    }
  ]
}
