{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-x-content",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-x-content-1.0.0-alpha2.jar",
          "url": "opensearch-x-content-1.0.0-alpha2.jar",
          "size": 142146,
          "sha512": "d82ca2dc013a12ab81a89c7896399b80b10d4174db1ebfb4b2185a031783a356110cfbac2f1a0eb328789e7277a356717ba1630c441e8c06cedefc1d1e5b2406",
          "sha256": "c840144ee6d45eabbfc3338385169d3f3414363c7f86d805c38dd28bc3747e3a",
          "sha1": "78613f966c01e54e7ce74dd10361bff1e74413d5",
          "md5": "ef3a1bc4017d80c47251752c79a98b3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-alpha2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-x-content-1.0.0-alpha2.jar",
          "url": "opensearch-x-content-1.0.0-alpha2.jar",
          "size": 142146,
          "sha512": "d82ca2dc013a12ab81a89c7896399b80b10d4174db1ebfb4b2185a031783a356110cfbac2f1a0eb328789e7277a356717ba1630c441e8c06cedefc1d1e5b2406",
          "sha256": "c840144ee6d45eabbfc3338385169d3f3414363c7f86d805c38dd28bc3747e3a",
          "sha1": "78613f966c01e54e7ce74dd10361bff1e74413d5",
          "md5": "ef3a1bc4017d80c47251752c79a98b3c"
        }
      ]
    }
  ]
}
