{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "analysis-kuromoji",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "5khnq5icy5dr5l756fhku3yqpm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-kuromoji",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-kuromoji-1.0.0-alpha2.jar",
          "url": "analysis-kuromoji-1.0.0-alpha2.jar",
          "size": 17869,
          "sha512": "64b3ccd92a11dd39ebb6adb052ce10811a04adef74e6a1e5caf371c2cb6302bb44bc6adc6b7cb0b6a769cb8a94610a672d975ec38d886286114269a66a300f71",
          "sha256": "b44d63f9627ce2fb38f8ade48fe8292a400a18c1a271550fca4c0f012c08f270",
          "sha1": "49e060b8d607c4488ef30867f9f5ab3fd8e1a803",
          "md5": "9a1e121f722a67d64e0946be9579e438"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-kuromoji",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "analysis-kuromoji-1.0.0-alpha2.jar",
          "url": "analysis-kuromoji-1.0.0-alpha2.jar",
          "size": 17869,
          "sha512": "64b3ccd92a11dd39ebb6adb052ce10811a04adef74e6a1e5caf371c2cb6302bb44bc6adc6b7cb0b6a769cb8a94610a672d975ec38d886286114269a66a300f71",
          "sha256": "b44d63f9627ce2fb38f8ade48fe8292a400a18c1a271550fca4c0f012c08f270",
          "sha1": "49e060b8d607c4488ef30867f9f5ab3fd8e1a803",
          "md5": "9a1e121f722a67d64e0946be9579e438"
        }
      ]
    }
  ]
}
