#!/usr/bin/env bash

# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.

# =============================================================================
# heap-circuit-breaker.sh
#
# Automated runner for docs/manual-tests/heap-circuit-breaker.md.
#
# Runs Data Prepper nodes in Docker containers next to a single-node OpenSearch
# on a private Docker network, drives load with telemetrygen, and asserts that
# the heap circuit breaker opens, rejects requests at the layers hardened by
# the change (P1 decorator, P2 gRPC pre-parse check, P3 hysteresis, P4 peer
# forwarder), and closes again.
#
# Usage:
#   ./heap-circuit-breaker.sh [--source trace|logs|metrics] [--nodes 1|3]
#       [--scenario isolated|load-wave] [--tls] [--skip-build]
#       [--keep-running] [--cleanup] [--help]
#
# One node (default):
#   Floods the chosen OTel source until the breaker opens. Asserts the trip,
#   the P1 decorator rejection (HTTP 429, or gRPC RESOURCE_EXHAUSTED with retry
#   info) on a parallel probe (HTTP/JSON for trace
#   and logs, raw gRPC for metrics), the P2 check (logs and metrics), the
#   health check, hysteresis (P3) and recovery.
#
# Three nodes (--nodes 3, trace source only):
#   dp1, dp2 and dp3 forward to each other through the peer forwarder
#   (discovery_mode: static). Each node needs its own container: the peer
#   forwarder server listens on all interfaces and a node forwards to the port
#   from its own configuration. Only dp3 is meant to trip its breaker.
#   isolated   (default) Low traffic to dp1 only. dp3's thresholds are
#              calibrated just above its own heap so its breaker opens and
#              closes by itself. Asserts that every failed forward from dp1 is
#              a P4 rejection (HTTP 429) by dp3, that nothing is dropped, and that
#              dp3's gRPC health check answers RESOURCE_EXHAUSTED while open.
#   load-wave  Steady traffic to dp1 plus a flood on dp3. Observational; only
#              the breaker trip is asserted.
#
# Flags:
#   --source NAME    trace (default), logs or metrics.
#   --nodes N        1 (default) or 3.
#   --scenario NAME  isolated (default) or load-wave; only with --nodes 3.
#   --tls            Enable TLS on the OTel source, the peer forwarder and the admin
#                    server, with a test CA generated by openssl. OpenSearch stays
#                    plain HTTP (TLS there needs the security plugin).
#   --skip-build     Don't run the Gradle install task (assume DP is built).
#   --keep-running   Leave the containers running after the run.
#   --cleanup        Remove containers and network from a previous run and exit.
#   -h, --help       Show this help.
#
# Tunables (env vars):
#   One node:   LOAD_RATE (5000), LOAD_WORKERS (100), LOAD_DURATION (30),
#               DP_HEAP (256m), USAGE (200mb), CLOSE_USAGE (150mb)
#   Three nodes: STEADY_RATE (100 isolated, 200 load-wave), STEADY_SECS (90/75),
#               FLOOD_RATE (5000, load-wave), CALIBRATION_SECS (30),
#               DP3_USAGE / DP3_CLOSE (calibrated in isolated; 200mb/120mb in load-wave),
#               PF_BUFFER_SIZE (2048), PF_FORWARDING_BATCH_SIZE (500),
#               PF_FORWARDING_BATCH_TIMEOUT (500ms)
#   Both:       NET_PREFIX (172.28.0), JRE_IMAGE (eclipse-temurin:17-jre),
#               OUT_DIR (/tmp/cb-test-<source>-n<nodes>[-<scenario>])
#
# Output (OUT_DIR): samples.tsv (every 0.5 s), events.tsv (timed log events),
#   one log per node, and the generated node configuration under nodes/.
#
# Exit code: 0 if every assertion PASSED, 1 if any FAILED, >1 on setup error.
# =============================================================================

set -euo pipefail
export LC_ALL=C

# ---------- Flags ----------
SOURCE="trace"
NODE_COUNT=1
SCENARIO="isolated"
SKIP_BUILD=false
KEEP_RUNNING=false
CLEANUP_ONLY=false
TLS=false

usage() { sed -n '3,72p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --source)       SOURCE="${2:-}"; shift ;;
        --nodes)        NODE_COUNT="${2:-}"; shift ;;
        --scenario)     SCENARIO="${2:-}"; shift ;;
        --skip-build)   SKIP_BUILD=true ;;
        --keep-running) KEEP_RUNNING=true ;;
        --cleanup)      CLEANUP_ONLY=true ;;
        --tls)          TLS=true ;;
        -h|--help)      usage; exit 0 ;;
        *) echo "Unknown flag: $1 (see --help)" >&2; exit 2 ;;
    esac
    shift
done

# ---------- Source table ----------
# plugin | container port | telemetrygen signal | pipeline | processor | extra source config | probe | probe path | P2 service
case "$SOURCE" in
    trace)
        PLUGIN=otlp_traces; SRC_PORT=21890; SIGNAL=traces; PIPELINE=traces-pipeline; PROCESSOR=otel_traces
        SOURCE_EXTRA=""; PROBE=http-json
        PROBE_PATH="/opentelemetry.proto.collector.trace.v1.TraceService/Export"; P2_SERVICE="" ;;
    logs)
        PLUGIN=otlp_logs; SRC_PORT=21892; SIGNAL=logs; PIPELINE=logs-pipeline; PROCESSOR=""
        SOURCE_EXTRA="      http_path: /v1/logs"; PROBE=http-json
        PROBE_PATH="/v1/logs"; P2_SERVICE=OTelLogsGrpcService ;;
    metrics)
        PLUGIN=otlp_metrics; SRC_PORT=21891; SIGNAL=metrics; PIPELINE=metrics-pipeline; PROCESSOR=otel_metrics
        SOURCE_EXTRA=""; PROBE=grpc
        PROBE_PATH="/opentelemetry.proto.collector.metrics.v1.MetricsService/Export"; P2_SERVICE=OTelMetricsGrpcService ;;
    *) echo "Unknown source: $SOURCE" >&2; exit 2 ;;
esac
[[ "$NODE_COUNT" == 1 || "$NODE_COUNT" == 3 ]] || { echo "--nodes must be 1 or 3" >&2; exit 2; }
[[ "$SCENARIO" == isolated || "$SCENARIO" == load-wave ]] || { echo "Unknown scenario: $SCENARIO" >&2; exit 2; }
if (( NODE_COUNT == 3 )) && [[ "$SOURCE" != trace ]]; then
    echo "--nodes 3 needs --source trace: only otel_traces uses the peer forwarder here." >&2; exit 2
fi
readonly SOURCE NODE_COUNT SCENARIO PLUGIN SRC_PORT SIGNAL PIPELINE PROCESSOR SOURCE_EXTRA PROBE PROBE_PATH P2_SERVICE

# ---------- Tunables ----------
LOAD_RATE="${LOAD_RATE:-5000}"; LOAD_WORKERS="${LOAD_WORKERS:-100}"; LOAD_DURATION="${LOAD_DURATION:-30}"
DP_HEAP="${DP_HEAP:-256m}"; USAGE="${USAGE:-200mb}"; CLOSE_USAGE="${CLOSE_USAGE:-150mb}"
if [[ "$SCENARIO" == isolated ]]; then
    STEADY_RATE="${STEADY_RATE:-100}"; STEADY_SECS="${STEADY_SECS:-90}"; FLOOD_RATE=0
else
    STEADY_RATE="${STEADY_RATE:-200}"; STEADY_SECS="${STEADY_SECS:-75}"; FLOOD_RATE="${FLOOD_RATE:-5000}"
    DP3_USAGE="${DP3_USAGE:-200mb}"; DP3_CLOSE="${DP3_CLOSE:-120mb}"
fi
CALIBRATION_SECS="${CALIBRATION_SECS:-30}"
PF_BUFFER_SIZE="${PF_BUFFER_SIZE:-2048}"
PF_FORWARDING_BATCH_SIZE="${PF_FORWARDING_BATCH_SIZE:-500}"
PF_FORWARDING_BATCH_TIMEOUT="${PF_FORWARDING_BATCH_TIMEOUT:-500ms}"
NET_PREFIX="${NET_PREFIX:-172.28.0}"
JRE_IMAGE="${JRE_IMAGE:-eclipse-temurin:17-jre}"
if (( NODE_COUNT == 1 )); then
    OUT_DIR="${OUT_DIR:-/tmp/cb-test-${SOURCE}-n1$($TLS && echo -tls || true)}"
else
    OUT_DIR="${OUT_DIR:-/tmp/cb-test-${SOURCE}-n3-${SCENARIO}$($TLS && echo -tls || true)}"
fi

# ---------- Constants ----------
readonly OS_IMAGE="opensearchproject/opensearch:2"
readonly OS_CONTAINER="cb-test-os"
readonly NET_NAME="cb-test-net"
readonly OS_IP="${NET_PREFIX}.10"
readonly ALL_NODES=(dp1 dp2 dp3)
readonly NODE_IPS=("${NET_PREFIX}.11" "${NET_PREFIX}.12" "${NET_PREFIX}.13")
readonly ADMIN_HOST_PORTS=(4901 4902 4903)
if (( NODE_COUNT == 1 )); then
    readonly SOURCE_HOST_PORTS=("$SRC_PORT")
else
    readonly SOURCE_HOST_PORTS=(21890 21892 21893)
fi
readonly GRPC_HEALTH_PATH="/grpc.health.v1.Health/Check"
readonly CERT_DIR="$OUT_DIR/certs"
readonly KEY_STORE_PASSWORD="changeit"
if $TLS; then
    readonly SCHEME=https H2=(--http2) CURL_TLS=(--cacert "$CERT_DIR/ca.crt") TG_TLS=(--ca-cert "$CERT_DIR/ca.crt")
else
    readonly SCHEME=http H2=(--http2-prior-knowledge) CURL_TLS=() TG_TLS=(--otlp-insecure)
fi
NODES=("${ALL_NODES[@]:0:$NODE_COUNT}")

# ---------- Repo root + arch ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
readonly SCRIPT_DIR REPO_ROOT
case "$(uname -m)" in
    x86_64)            ARCH=x64 ;;
    aarch64|arm64)     ARCH=arm64 ;;
    *) echo "Unsupported architecture: $(uname -m)" >&2; exit 2 ;;
esac
readonly ARCH
readonly INSTALL_TASK="installLinux${ARCH}Dist"

# ---------- Pretty output ----------
if [[ -t 1 ]]; then
    C_RESET=$'\e[0m'; C_DIM=$'\e[2m'
    C_RED=$'\e[31m'; C_GRN=$'\e[32m'; C_YEL=$'\e[33m'; C_CYN=$'\e[36m'; C_BLD=$'\e[1m'
else
    C_RESET=""; C_DIM=""; C_RED=""; C_GRN=""; C_YEL=""; C_CYN=""; C_BLD=""
fi

FAILURES=0
WARNINGS=0
log()     { printf '%s[%s]%s %s\n' "$C_CYN" "$(date +%H:%M:%S)" "$C_RESET" "$*"; }
section() { printf '\n%s=== %s ===%s\n' "$C_BLD$C_YEL" "$*" "$C_RESET"; }
pass()    { printf '%s✅ PASS%s %s\n' "$C_GRN" "$C_RESET" "$*"; }
fail()    { printf '%s❌ FAIL%s %s\n' "$C_RED" "$C_RESET" "$*"; FAILURES=$((FAILURES + 1)); }
warn()    { printf '%s⚠  WARN%s %s\n' "$C_YEL" "$C_RESET" "$*"; WARNINGS=$((WARNINGS + 1)); }
die()     { printf '%sERROR%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; exit 2; }

# ---------- Cleanup ----------
container() { printf 'cb-test-%s' "$1"; }

remove_everything() {
    touch "$OUT_DIR/stop" 2>/dev/null || true
    local n
    for n in "${ALL_NODES[@]}"; do docker rm -f "$(container "$n")" >/dev/null 2>&1 || true; done
    docker rm -f "$OS_CONTAINER" >/dev/null 2>&1 || true
    docker network rm "$NET_NAME" >/dev/null 2>&1 || true
}

cleanup() {
    local rc=$?
    set +e
    trap - EXIT INT TERM
    touch "$OUT_DIR/stop" 2>/dev/null
    if $KEEP_RUNNING; then
        log "Leaving containers running. Cleanup later with: $0 --cleanup"
    else
        log "Removing containers and network..."
        remove_everything
    fi
    exit "$rc"
}

# =============================================================================
# Helpers
# =============================================================================

scrape() { curl -s "${CURL_TLS[@]}" --max-time 2 "${SCHEME}://localhost:$1/metrics/prometheus" 2>/dev/null || true; }
pick()   { printf '%s\n' "$1" | awk -v r="$2" '$1 ~ r { print $2; exit }' || true; }
metric() { pick "$(scrape "$1")" "$2"; }
mib()    { awk -v b="${1:-0}" 'BEGIN { printf "%d", b / 1048576 }'; }
bytes()  { awk -v v="$1" 'BEGIN { sub(/mb$/, "", v); printf "%d", v * 1048576 }'; }
since()  { awk -v a="$(date +%s.%N)" -v b="$1" 'BEGIN { printf "%.2f", a - b }'; }
count_in() { grep -cE "$2" "$1" 2>/dev/null || true; }

# Column index of header $2 in TSV file $1.
col() { head -1 "$1" | tr '\t' '\n' | grep -nx "$2" | cut -d: -f1; }

# Raw gRPC health check against a host port. Echoes "<http status>/<grpc-status>".
grpc_health() {
    printf '\x00\x00\x00\x00\x00' | curl -s "${H2[@]}" "${CURL_TLS[@]}" --max-time 2 -o /dev/null -D - -X POST \
        -H 'content-type: application/grpc' -H 'te: trailers' --data-binary @- \
        "${SCHEME}://localhost:$1${GRPC_HEALTH_PATH}" 2>/dev/null | tr -d '\r' \
        | awk '/^HTTP\//{s=$2} /^grpc-status:/{g=$2} END{printf "%s/%s", (s?s:"000"), (g==""?"-":g)}' || true
}

# One request to the source's export endpoint on host port $1. Echoes:
#   ok      accepted
#   p1      rejected by the circuit-breaker decorator (P1): HTTP 429, or gRPC
#           RESOURCE_EXHAUSTED with the decorator's message
#   p2      RESOURCE_EXHAUSTED "Circuit breaker is open." (P2, gRPC probe only)
#   buffer  RESOURCE_EXHAUSTED from CircuitBreakingBuffer (gRPC probe only)
#   other   anything else
probe_once() {
    if [[ "$PROBE" == http-json ]]; then
        local code
        code="$(curl -s "${CURL_TLS[@]}" -o /dev/null -w '%{http_code}' --max-time 3 -X POST -H 'Content-Type: application/json' \
            -d '{}' "${SCHEME}://localhost:$1${PROBE_PATH}" 2>/dev/null || true)"
        case "$code" in 200) echo ok ;; 429) echo p1 ;; *) echo other ;; esac
    else
        printf '\x00\x00\x00\x00\x00' | curl -s "${H2[@]}" "${CURL_TLS[@]}" --max-time 3 -o /dev/null -D - -X POST \
            -H 'content-type: application/grpc' -H 'te: trailers' --data-binary @- \
            "${SCHEME}://localhost:$1${PROBE_PATH}" 2>/dev/null | tr -d '\r' | awk '
            /^HTTP\// { status = $2 }
            /^grpc-status:/ { grpc = $2 }
            /^grpc-message:/ { sub(/^grpc-message: /, ""); message = $0 }
            END {
                if (grpc == "0") print "ok"
                else if (grpc == "8" && message ~ /before(%20| )reading/) print "p1"
                else if (grpc == "8" && message ~ /Unable/) print "buffer"
                else if (grpc == "8" && message ~ /^Circuit(%20| )breaker(%20| )is(%20| )open\.$/) print "p2"
                else print "other"
            }' || true
    fi
}

# =============================================================================
# Setup phases
# =============================================================================

phase_check_prereqs() {
    section "Checking prerequisites"
    local missing=0 cmd
    for cmd in docker curl awk grep sed timeout $($TLS && echo openssl || true); do
        command -v "$cmd" >/dev/null 2>&1 || { printf '%s missing: %s%s\n' "$C_RED" "$cmd" "$C_RESET" >&2; missing=$((missing + 1)); }
    done
    if ! command -v telemetrygen >/dev/null 2>&1; then
        printf '%s missing: telemetrygen%s\n' "$C_RED" "$C_RESET" >&2
        printf '   install: %sgo install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest%s\n' "$C_DIM" "$C_RESET" >&2
        missing=$((missing + 1))
    fi
    (( missing == 0 )) || die "$missing prerequisite(s) missing"
    docker info >/dev/null 2>&1 || die "Docker daemon not reachable"
    if docker network ls --format '{{.Name}}' | grep -qx "$NET_NAME"; then
        die "Network $NET_NAME already exists (previous run?). Run: $0 --cleanup"
    fi
    log "Source: $SOURCE ($PLUGIN), nodes: $NODE_COUNT$( (( NODE_COUNT == 3 )) && echo ", scenario: $SCENARIO"). Output: $OUT_DIR"
}

phase_build() {
    section "Building Data Prepper (${INSTALL_TASK})"
    ( cd "$REPO_ROOT" && ./gradlew ":release:archives:linux:${INSTALL_TASK}" )
}

phase_locate_dp_home() {
    local version
    version="$(grep '^version=' "$REPO_ROOT/gradle.properties" | cut -d= -f2)"
    DP_HOME="$REPO_ROOT/release/archives/linux/build/install/opensearch-data-prepper-${version}-linux-${ARCH}"
    readonly DP_HOME
    [[ -d "$DP_HOME/lib" ]] || die "DP_HOME not found: $DP_HOME (run without --skip-build first)"
    log "DP_HOME=$DP_HOME"
}

phase_start_opensearch() {
    section "Starting network and single-node OpenSearch"
    rm -rf "$OUT_DIR"; mkdir -p "$OUT_DIR"
    docker network create --subnet "${NET_PREFIX}.0/24" "$NET_NAME" >/dev/null
    docker run -d --name "$OS_CONTAINER" --network "$NET_NAME" --ip "$OS_IP" \
        -e discovery.type=single-node -e DISABLE_SECURITY_PLUGIN=true \
        -e "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" "$OS_IMAGE" >/dev/null
    docker pull -q "$JRE_IMAGE" >/dev/null
    local i
    for i in $(seq 1 90); do
        docker exec "$OS_CONTAINER" curl -fs localhost:9200 >/dev/null 2>&1 && break
        sleep 2
    done
    docker exec "$OS_CONTAINER" curl -fs localhost:9200 >/dev/null 2>&1 || die "OpenSearch did not come up"
    log "OpenSearch is up at $OS_IP."
}

pf_ssl_yaml() {
    if $TLS; then
        printf '  ssl: true\n  ssl_certificate_file: /dp/certs/node-chain.crt\n  ssl_key_file: /dp/certs/node.key'
    else
        printf '  ssl: false'
    fi
}

# One test CA and one node certificate that is valid for every node IP and for
# localhost, so the same files serve the sources, the peer forwarder (server
# and client trust) and the admin server.
phase_generate_certs() {
    $TLS || return 0
    section "Generating test certificates"
    mkdir -p "$CERT_DIR"
    (
        cd "$CERT_DIR"
        openssl req -x509 -newkey rsa:2048 -nodes -keyout ca.key -out ca.crt -days 2 -subj "/CN=cb-test-ca" 2>/dev/null
        openssl req -newkey rsa:2048 -nodes -keyout node.key -out node.csr -subj "/CN=cb-test-node" 2>/dev/null
        printf 'subjectAltName=DNS:localhost,IP:127.0.0.1,IP:%s,IP:%s,IP:%s\nextendedKeyUsage=serverAuth,clientAuth\n' \
            "${NODE_IPS[0]}" "${NODE_IPS[1]}" "${NODE_IPS[2]}" > node.ext
        openssl x509 -req -in node.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out node.crt -days 2 -extfile node.ext 2>/dev/null
        cat node.crt ca.crt > node-chain.crt
        openssl pkcs12 -export -in node.crt -inkey node.key -certfile ca.crt -out admin.p12 \
            -passout "pass:${KEY_STORE_PASSWORD}" 2>/dev/null
        chmod a+r ./*
    )
    log "CA and node certificate in $CERT_DIR (SAN: localhost, 127.0.0.1, ${NODE_IPS[*]})."
}

# $1 node, $2 usage, $3 close_usage
write_node_config() {
    local dir="$OUT_DIR/nodes/$1"
    mkdir -p "$dir/config" "$dir/pipelines"
    {
        if $TLS; then
            printf 'ssl: true\nkey_store_file_path: /dp/certs/admin.p12\nkey_store_password: %s\nprivate_key_password: %s\n' \
                "$KEY_STORE_PASSWORD" "$KEY_STORE_PASSWORD"
        else
            printf 'ssl: false\n'
        fi
        cat <<YAML
metric_registries: [Prometheus]
circuit_breakers:
  heap:
    usage: $2
    close_usage: $3
    reset: 2s
    check_interval: 500ms
YAML
        if (( NODE_COUNT == 3 )); then
            cat <<YAML
peer_forwarder:
  discovery_mode: static
  static_endpoints: ["${NODE_IPS[0]}", "${NODE_IPS[1]}", "${NODE_IPS[2]}"]
$(pf_ssl_yaml)
  buffer_size: ${PF_BUFFER_SIZE}
  forwarding_batch_size: ${PF_FORWARDING_BATCH_SIZE}
  forwarding_batch_timeout: ${PF_FORWARDING_BATCH_TIMEOUT}
YAML
        else
            # otel_traces always starts the peer forwarder server; give it the
            # test certificate or disable TLS, the default certificate from
            # config/ is not mounted.
            printf 'peer_forwarder:\n%s\n' "$(pf_ssl_yaml)"
        fi
    } > "$dir/config/data-prepper-config.yaml"
    {
        printf '%s:\n  source:\n    %s:\n' "$PIPELINE" "$PLUGIN"
        if $TLS; then
            printf '      ssl: true\n      sslKeyCertChainFile: /dp/certs/node-chain.crt\n      sslKeyFile: /dp/certs/node.key\n'
        else
            printf '      ssl: false\n'
        fi
        printf '      health_check_service: true\n'
        [[ -n "$SOURCE_EXTRA" ]] && printf '%s\n' "$SOURCE_EXTRA"
        [[ -n "$PROCESSOR" ]] && printf '  processor:\n    - %s:\n' "$PROCESSOR"
        printf '  sink:\n    - opensearch:\n        hosts: [ "http://%s:9200" ]\n        insecure: true\n        index: otel-%s\n' "$OS_IP" "$SIGNAL"
    } > "$dir/pipelines/pipelines.yaml"
    cat > "$dir/config/log4j2-rolling.properties" <<'PROPS'
status = error
dest = err
name = PropertiesConfig
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} [%t] %-5p %40C - %m%n
rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = STDOUT
logger.breaker.name = org.opensearch.dataprepper.core.breaker
logger.breaker.level = info
logger.plugins.name = org.opensearch.dataprepper.plugins
logger.plugins.level = info
logger.pfservice.name = org.opensearch.dataprepper.core.peerforwarder.server
logger.pfservice.level = debug
PROPS
}

# $1 index into NODES, $2 heap
start_node() {
    local n="${NODES[$1]}" dir="$OUT_DIR/nodes/${NODES[$1]}"
    docker run -d --name "$(container "$n")" --network "$NET_NAME" --ip "${NODE_IPS[$1]}" \
        -p "${SOURCE_HOST_PORTS[$1]}:${SRC_PORT}" -p "${ADMIN_HOST_PORTS[$1]}:4900" -w /tmp \
        -v "$DP_HOME/bin:/dp/bin:ro" -v "$DP_HOME/lib:/dp/lib:ro" \
        -v "$dir/config:/dp/config:ro" -v "$dir/pipelines:/dp/pipelines:ro" \
        $($TLS && echo "-v $CERT_DIR:/dp/certs:ro" || true) \
        -e JAVA_OPTS="-Xms$2 -Xmx$2" "$JRE_IMAGE" /dp/bin/data-prepper >/dev/null
}

# $1 index into NODES
wait_for_node() {
    local i n="${NODES[$1]}"
    for i in $(seq 1 120); do
        if [[ "$(grpc_health "${SOURCE_HOST_PORTS[$1]}")" == "200/0" ]]; then
            log "$n is ready (source and health check up)."
            return 0
        fi
        docker ps --format '{{.Names}}' | grep -qx "$(container "$n")" \
            || { docker logs "$(container "$n")" 2>&1 | tail -30 >&2; die "$n exited during startup"; }
        sleep 1
    done
    die "$n did not become ready"
}

phase_start_nodes() {
    section "Starting Data Prepper node(s)"
    if (( NODE_COUNT == 1 )); then
        write_node_config dp1 "$USAGE" "$CLOSE_USAGE"
        start_node 0 "$DP_HEAP"
        wait_for_node 0
        return
    fi
    local u3="${DP3_USAGE:-240mb}" c3="${DP3_CLOSE:-220mb}"
    [[ -z "${DP3_USAGE:-}" ]] && log "dp3 starts with high thresholds ($u3/$c3) for calibration."
    write_node_config dp1 400mb 300mb
    write_node_config dp2 400mb 300mb
    write_node_config dp3 "$u3" "$c3"
    start_node 0 512m; start_node 1 512m; start_node 2 256m
    wait_for_node 0; wait_for_node 1; wait_for_node 2
}

phase_calibrate_dp3() {
    (( NODE_COUNT == 3 )) || return 0
    if [[ -n "${DP3_USAGE:-}" ]]; then
        [[ -n "${DP3_CLOSE:-}" ]] || die "DP3_CLOSE must be set together with DP3_USAGE"
        log "Using DP3_USAGE=$DP3_USAGE DP3_CLOSE=$DP3_CLOSE (no calibration)."
        return 0
    fi
    section "Calibrating dp3's breaker (${CALIBRATION_SECS}s at ${STEADY_RATE} traces/s)"
    telemetrygen traces --otlp-endpoint "localhost:${SOURCE_HOST_PORTS[0]}" "${TG_TLS[@]}" \
        --workers 2 --rate "$STEADY_RATE" --duration "${CALIBRATION_SECS}s" > "$OUT_DIR/telem-calibration.log" 2>&1 &
    local tg=$! peak=0 h i
    for i in $(seq 1 $((CALIBRATION_SECS * 2))); do
        h="$(mib "$(metric "${ADMIN_HOST_PORTS[2]}" '^core_circuitBreakers_heap_memoryUsage')")"
        if (( h > peak )); then peak=$h; fi
        sleep 0.5
    done
    wait "$tg" 2>/dev/null || true
    (( peak > 0 )) || die "Could not read dp3's heap during calibration"
    DP3_USAGE="$(( peak * 85 / 100 ))mb"
    DP3_CLOSE="$(( peak * 70 / 100 ))mb"
    log "dp3 heap peaked at ${peak} MB -> usage=$DP3_USAGE close_usage=$DP3_CLOSE. Restarting dp3..."
    docker rm -f "$(container dp3)" >/dev/null
    write_node_config dp3 "$DP3_USAGE" "$DP3_CLOSE"
    start_node 2 256m
    wait_for_node 2
    sleep 5
}

phase_check_startup() {
    section "Startup checks"
    local n line logs
    for n in "${NODES[@]}"; do
        logs="$(docker logs "$(container "$n")" 2>&1)"
        line="$(printf '%s\n' "$logs" | grep -oE 'Circuit breaker heap open threshold is [0-9.]+ MiB \([0-9]+ bytes\), close threshold is [0-9.]+ MiB \([0-9]+ bytes\)' | tail -1 || true)"
        if [[ -n "$line" ]]; then pass "$n: $line"; else fail "$n: breaker thresholds missing from the startup log."; fi
        if printf '%s\n' "$logs" | grep -q 'Installing circuit-breaker HTTP decorator'; then
            pass "$n installed the circuit-breaker HTTP decorator."
        else
            fail "$n did not log 'Installing circuit-breaker HTTP decorator'."
        fi
    done
    if [[ "$SOURCE" == logs ]]; then
        if docker logs "$(container dp1)" 2>&1 | grep -q 'Configuring HTTP service under /v1/logs'; then
            pass "Additional HTTP service registered under /v1/logs."
        else
            fail "No 'Configuring HTTP service under /v1/logs' in the log: http_path was ignored."
        fi
    fi
}

# =============================================================================
# Measurement
# =============================================================================

sampler() {
    set +e
    local t0=$1 i h n bodies=()
    printf 't'
    for n in "${NODES[@]}"; do printf '\t%s_heap\t%s_open' "$n" "$n"; done
    printf '\tfwd_ok\tfwd_failed\tfwd_req_failed\tprobe\thealth'
    for n in "${NODES[@]}"; do printf '\t%s_rb' "$n"; done
    printf '\n'
    local health_port="${SOURCE_HOST_PORTS[$((NODE_COUNT - 1))]}"
    while [[ ! -f "$OUT_DIR/stop" ]]; do
        bodies=()
        for i in "${!NODES[@]}"; do bodies+=("$(scrape "${ADMIN_HOST_PORTS[$i]}")"); done
        printf '%s' "$(since "$t0")"
        for i in "${!NODES[@]}"; do
            printf '\t%s\t%s' "$(pick "${bodies[$i]}" '^core_circuitBreakers_heap_memoryUsage')" "$(pick "${bodies[$i]}" '^core_circuitBreakers_heap_open')"
        done
        printf '\t%s\t%s\t%s' "$(pick "${bodies[0]}" 'recordsSuccessfullyForwarded_total')" \
            "$(pick "${bodies[0]}" 'recordsFailedForwarding_total')" "$(pick "${bodies[0]}" 'core_peerForwarder_requestsFailed_total')"
        if (( NODE_COUNT == 1 )); then printf '\t%s' "$(probe_once "${SOURCE_HOST_PORTS[0]}")"; else printf '\t-'; fi
        printf '\t%s' "$(grpc_health "$health_port")"
        for i in "${!NODES[@]}"; do printf '\t%s' "$(pick "${bodies[$i]}" 'peerForwarder_.*_bufferUsage')"; done
        printf '\n'
        sleep 0.5
    done
}

start_sampler() {
    rm -f "$OUT_DIR/stop"
    T0="$(date +%s.%N)"; echo "$T0" > "$OUT_DIR/t0"
    SINCE="$(date -u +%Y-%m-%dT%H:%M:%S)"
    sampler "$T0" > "$OUT_DIR/samples.tsv" &
    SAMPLER_PID=$!
}

stop_sampler() {
    touch "$OUT_DIR/stop"; wait "$SAMPLER_PID" 2>/dev/null || true
    local n
    for n in "${NODES[@]}"; do docker logs --since "$SINCE" "$(container "$n")" > "$OUT_DIR/$n.log" 2>&1 || true; done
}

# Gauge value of node index $1 (default 0).
open_gauge() { metric "${ADMIN_HOST_PORTS[${1:-0}]}" '^core_circuitBreakers_heap_open'; }
is_open() { awk -v v="${1:-0}" 'BEGIN { exit (v + 0 == 1) ? 0 : 1 }'; }

phase_baseline_single() {
    section "Baseline: breaker closed, endpoint accepting"
    timeout --foreground --kill-after=5s 25s telemetrygen "$SIGNAL" --otlp-endpoint "localhost:${SOURCE_HOST_PORTS[0]}" "${TG_TLS[@]}" \
        --duration 5s --rate 10 --workers 1 > "$OUT_DIR/telem-baseline.log" 2>&1 || true
    local v p
    v="$(open_gauge)"
    if is_open "$v"; then fail "core_circuitBreakers_heap_open=$v before any load; raise USAGE."; else pass "Breaker closed at baseline (gauge=${v:-?})."; fi
    p="$(probe_once "${SOURCE_HOST_PORTS[0]}")"
    if [[ "$p" == ok ]]; then pass "Probe to ${PROBE_PATH} accepted."; else fail "Probe to ${PROBE_PATH} answered '$p' while the breaker is closed."; fi
}

phase_trip_single() {
    section "Tripping the breaker (${LOAD_WORKERS} workers, ${LOAD_RATE}/s, ${LOAD_DURATION}s of ${SIGNAL})"
    BASE_TIMEOUTS="$(metric "${ADMIN_HOST_PORTS[0]}" "^${PIPELINE//-/_}_.*_requestTimeouts_total")"
    start_sampler
    timeout --foreground --kill-after=10s "$((LOAD_DURATION + 30))s" telemetrygen "$SIGNAL" \
        --otlp-endpoint "localhost:${SOURCE_HOST_PORTS[0]}" "${TG_TLS[@]}" \
        --workers "$LOAD_WORKERS" --rate "$LOAD_RATE" --duration "${LOAD_DURATION}s" > "$OUT_DIR/telem-load.log" 2>&1 || true
}

phase_settle_single() {
    section "Hysteresis (P3): waiting for the breaker to settle closed"
    local stable=0 i v=""
    for i in $(seq 1 90); do
        v="$(open_gauge)"
        if [[ -n "$v" ]] && ! is_open "$v"; then stable=$((stable + 1)); (( stable >= 3 )) && break; else stable=0; fi
        sleep 1
    done
    if (( stable >= 3 )); then pass "Breaker settled closed (gauge=$v for ${stable}s)."; else fail "Breaker did not settle closed within 90s."; fi

    section "Recovery: low traffic must not reopen the breaker"
    timeout --foreground --kill-after=5s 25s telemetrygen "$SIGNAL" --otlp-endpoint "localhost:${SOURCE_HOST_PORTS[0]}" "${TG_TLS[@]}" \
        --duration 10s --rate 20 --workers 2 > "$OUT_DIR/telem-recovery.log" 2>&1 || true
    sleep 2
    local v1 v2 p
    v1="$(open_gauge)"; sleep 3; v2="$(open_gauge)"
    if [[ -n "$v1" && -n "$v2" ]] && ! is_open "$v1" && ! is_open "$v2"; then
        pass "Breaker stayed closed under recovery traffic (gauge=$v1 → $v2)."
    else
        fail "Breaker reopened under recovery traffic (gauge=$v1 → $v2)."
    fi
    p="$(probe_once "${SOURCE_HOST_PORTS[0]}")"
    if [[ "$p" == ok ]]; then pass "Probe accepted again after recovery."; else fail "Probe answered '$p' after recovery."; fi
    stop_sampler
}

phase_measure_multi() {
    section "Measuring (${STEADY_RATE} traces/s to dp1 for ${STEADY_SECS}s$( (( FLOOD_RATE > 0 )) && echo ", flood ${FLOOD_RATE}/s on dp3 from 15s"))"
    BASE_REQ_FAILED="$(metric "${ADMIN_HOST_PORTS[0]}" 'core_peerForwarder_requestsFailed_total')"
    BASE_FAILED="$(metric "${ADMIN_HOST_PORTS[0]}" 'recordsFailedForwarding_total')"
    BASE_OK="$(metric "${ADMIN_HOST_PORTS[0]}" 'recordsSuccessfullyForwarded_total')"
    start_sampler
    telemetrygen traces --otlp-endpoint "localhost:${SOURCE_HOST_PORTS[0]}" "${TG_TLS[@]}" \
        --workers 2 --rate "$STEADY_RATE" --duration "${STEADY_SECS}s" > "$OUT_DIR/telem-steady.log" 2>&1 &
    local steady=$!
    if (( FLOOD_RATE > 0 )); then
        sleep 15
        timeout --foreground --kill-after=10s 90s telemetrygen traces --otlp-endpoint "localhost:${SOURCE_HOST_PORTS[2]}" "${TG_TLS[@]}" \
            --workers 100 --rate "$FLOOD_RATE" --duration 25s > "$OUT_DIR/telem-flood.log" 2>&1 || true
    fi
    wait "$steady" 2>/dev/null || true
    log "Load finished. Sampling 15 s more so forwarding can settle..."
    sleep 15
    stop_sampler
}

phase_extract_events() {
    local f label re
    : > "$OUT_DIR/events.tsv"
    while IFS='|' read -r f label re; do
        [[ -f "$OUT_DIR/$f" ]] || continue
        { grep -E "$re" "$OUT_DIR/$f" 2>/dev/null || true; } | while IFS= read -r line; do
            local ts e
            ts="$(echo "$line" | cut -c1-23 | tr ',' '.')"
            e="$(date -u -d "${ts/T/ } UTC" +%s.%N 2>/dev/null)" || continue
            printf '%s\t%s\t%s\n' "$(awk -v a="$e" -v b="$T0" 'BEGIN{printf "%.2f", a-b}')" "$label" \
                "$(echo "$line" | grep -oE 'Failed to add [0-9]+ records|Dropping [0-9]+ records|MiB \([0-9]+ bytes\) used' | grep -oE '[0-9]+' | head -1 || true)"
        done
    done <<EOF >> "$OUT_DIR/events.tsv"
${NODES[$((NODE_COUNT - 1))]}.log|open|tripped and open
${NODES[$((NODE_COUNT - 1))]}.log|closed|Circuit breaker closed
${NODES[$((NODE_COUNT - 1))]}.log|p4_reject|Rejecting peer forwarder request
dp1.log|queue_full|Failed to add [0-9]+ records to the batching queue
dp1.log|send_error|Unable to (send|submit) request
dp1.log|drop|Dropping [0-9]+ records
EOF
    sort -n -o "$OUT_DIR/events.tsv" "$OUT_DIR/events.tsv"
}

# =============================================================================
# Evaluation
# =============================================================================

phase_evaluate_single() {
    section "Results"
    local s="$OUT_DIR/samples.tsv" ev="$OUT_DIR/events.tsv"
    local open_bytes close_bytes trips first_trip last_close oc pc hc
    open_bytes="$(bytes "$USAGE")"; close_bytes="$(bytes "$CLOSE_USAGE")"
    trips="$(awk -F'\t' '$2=="open"' "$ev" | wc -l)"
    first_trip="$(awk -F'\t' '$2=="open"{print $3; exit}' "$ev")"
    last_close="$(awk -F'\t' '$2=="closed"{v=$3} END{print v}' "$ev")"
    oc="$(col "$s" dp1_open)"; pc="$(col "$s" probe)"; hc="$(col "$s" health)"

    if (( trips > 0 )) && (( ${first_trip:-0} > open_bytes )); then
        pass "Breaker tripped $trips time(s); first at $first_trip bytes (> $open_bytes)."
    else
        fail "Breaker did not trip above $open_bytes bytes (trips: $trips). Raise LOAD_RATE or lower USAGE."
    fi
    local open_samples p1 p2_probe other
    read -r open_samples p1 p2_probe other < <(awk -F'\t' -v o="$oc" -v p="$pc" 'NR>1 { if ($o+0==1) n++; if ($p=="p1") a++; if ($p=="p2") b++; if ($p=="other") c++ } END { printf "%d %d %d %d\n", n, a, b, c }' "$s")
    if (( open_samples > 0 )); then pass "Gauge core_circuitBreakers_heap_open=1 in $open_samples samples."; else warn "No sample caught the gauge at 1."; fi
    if (( p1 > 0 )); then
        pass "P1: probe to ${PROBE_PATH} was rejected $p1 time(s) by the decorator ($( [[ "$PROBE" == grpc ]] && echo "RESOURCE_EXHAUSTED" || echo "HTTP 429"))."
    else
        fail "P1: probe was never rejected by the decorator while the breaker was open."
    fi
    (( other == 0 )) || warn "$other probe answer(s) were neither OK nor a decorator rejection (connection resets under load are usually harmless)."

    if [[ -n "$P2_SERVICE" ]]; then
        local after delta buffer_timeouts timed_out inferred
        after="$(metric "${ADMIN_HOST_PORTS[0]}" "^${PIPELINE//-/_}_.*_requestTimeouts_total")"
        delta="$(awk -v a="${after:-0}" -v b="${BASE_TIMEOUTS:-0}" 'BEGIN{printf "%d", a-b}')"
        buffer_timeouts="$({ grep -A1 "${P2_SERVICE} - Failed to write the request" "$OUT_DIR/dp1.log" || true; } | grep -c 'TimeoutException' || true)"
        timed_out="$(count_in "$OUT_DIR/dp1.log" 'timed out')"
        inferred=$(( delta - ${buffer_timeouts:-0} ))
        log "P2 inputs: requestTimeouts +$delta, buffer-level TimeoutExceptions $buffer_timeouts, 'timed out' lines $timed_out, probe answers 'p2': $p2_probe"
        if (( p2_probe > 0 )); then
            pass "P2: probe received 'Circuit breaker is open.' $p2_probe time(s)."
        elif (( inferred > 0 && ${timed_out:-0} == 0 )); then
            pass "P2: $inferred request(s) rejected with a timeout status without a buffer-level log line."
        else
            warn "P2 not observed in this run (it only covers a short race window); covered by ${P2_SERVICE}Test."
        fi
    else
        log "P2: not applicable to the trace source (OTelTraceGrpcService has no pre-parse check)."
    fi

    local h_open h_open_rejected
    read -r h_open h_open_rejected < <(awk -F'\t' -v o="$oc" -v h="$hc" 'NR>1 && $o+0==1 { n++; if ($h ~ /\/8$/) a++ } END { printf "%d %d\n", n, a }' "$s")
    if (( h_open_rejected > 0 )); then pass "gRPC health check answered RESOURCE_EXHAUSTED in $h_open_rejected of $h_open open samples."; else warn "No sample caught the health check while open."; fi

    if [[ -n "$last_close" ]] && (( last_close <= close_bytes )); then
        pass "P3: last close at $last_close bytes (<= close threshold $close_bytes)."
    else
        fail "P3: last close at '${last_close:-none}' bytes (expected <= $close_bytes)."
    fi
}

phase_evaluate_multi() {
    section "Results"
    local s="$OUT_DIR/samples.tsv" ev="$OUT_DIR/events.tsv"
    local trips p4 req_failed failed ok queue drop drop_n local_after inbound=0 n c
    trips="$(awk -F'\t' '$2=="open"' "$ev" | wc -l)"
    p4="$(awk -F'\t' '$2=="p4_reject"' "$ev" | wc -l)"
    req_failed="$(awk -v a="$(metric "${ADMIN_HOST_PORTS[0]}" 'core_peerForwarder_requestsFailed_total')" -v b="${BASE_REQ_FAILED:-0}" 'BEGIN{printf "%d", a-b}')"
    failed="$(awk -v a="$(metric "${ADMIN_HOST_PORTS[0]}" 'recordsFailedForwarding_total')" -v b="${BASE_FAILED:-0}" 'BEGIN{printf "%d", a-b}')"
    ok="$(awk -v a="$(metric "${ADMIN_HOST_PORTS[0]}" 'recordsSuccessfullyForwarded_total')" -v b="${BASE_OK:-0}" 'BEGIN{printf "%d", a-b}')"
    queue="$(awk -F'\t' '$2=="queue_full"{s+=$3} END{printf "%d", s}' "$ev")"
    drop="$(awk -F'\t' '$2=="drop"{s+=$3} END{printf "%d", s}' "$ev")"
    drop_n="$(awk -F'\t' '$2=="drop"' "$ev" | wc -l)"
    local_after=$(( failed - queue - drop )); if (( local_after < 0 )); then local_after=0; fi
    for n in "${NODES[@]}"; do
        c="$(count_in "$OUT_DIR/$n.log" 'PeerForwarderHttpService - Failed to write')"; inbound=$(( inbound + ${c:-0} ))
    done

    log "dp3 thresholds: usage=${DP3_USAGE} close_usage=${DP3_CLOSE}"
    log "dp3 breaker trips: $trips, P4 rejections by dp3: $p4, failed requests at dp1: $req_failed"
    log "dp1 events for other nodes: forwarded=$ok, local after failed request=$local_after, local because queue full=$queue, dropped=$drop ($drop_n batches)"
    log "inbound write failures on all receivers: $inbound"

    if (( trips > 0 )); then
        pass "dp3's breaker tripped $trips time(s)."
    else
        fail "dp3's breaker never tripped. Set DP3_USAGE/DP3_CLOSE closer to dp3's heap, or raise STEADY_RATE."
    fi
    if [[ "$SCENARIO" == load-wave ]]; then
        log "load-wave is observational: forwarding numbers above are reported, not asserted."
        return 0
    fi
    if (( p4 == req_failed )); then
        pass "Every failed forward from dp1 is a P4 rejection by dp3 ($p4 = $req_failed)."
    else
        fail "P4 rejections ($p4) != failed requests at dp1 ($req_failed): another failure source is present."
    fi
    (( p4 > 0 )) || warn "No forwarding request hit an open window of dp3 (P4 not exercised). Raise STEADY_SECS."
    if (( drop == 0 )); then pass "Nothing was dropped."; else fail "dp1 dropped $drop records in $drop_n batches."; fi
    if (( queue == 0 && inbound == 0 )); then
        pass "No full batching queue and no inbound write failures: the test is isolated."
    else
        fail "Other failure sources present (queue full: $queue records, inbound write failures: $inbound). Lower STEADY_RATE."
    fi
    local oc hc h_open h_open_rejected h_closed h_closed_ok
    oc="$(col "$s" dp3_open)"; hc="$(col "$s" health)"
    read -r h_open h_open_rejected h_closed h_closed_ok < <(awk -F'\t' -v o="$oc" -v h="$hc" 'NR>1 { if ($o+0==1) { n++; if ($h ~ /\/8$/) a++ } else if ($o!="") { c++; if ($h=="200/0") b++ } } END { printf "%d %d %d %d\n", n, a, c, b }' "$s")
    if (( h_open_rejected > 0 )); then
        pass "dp3's gRPC health check answered RESOURCE_EXHAUSTED in $h_open_rejected of $h_open samples while open."
    else
        warn "No sample caught dp3's health check during an open window ($h_open open samples)."
    fi
    if (( h_closed > 0 && h_closed_ok * 100 / h_closed >= 90 )); then
        pass "dp3's gRPC health check answered OK in $h_closed_ok of $h_closed samples while closed."
    else
        fail "dp3's gRPC health check answered OK in only $h_closed_ok of $h_closed closed samples."
    fi
}

# =============================================================================
# Main
# =============================================================================

main() {
    if $CLEANUP_ONLY; then
        section "Cleanup only"
        remove_everything
        log "Removed test containers and network $NET_NAME (if present)."
        exit 0
    fi
    phase_check_prereqs
    trap cleanup EXIT INT TERM
    $SKIP_BUILD || phase_build
    phase_locate_dp_home
    phase_start_opensearch
    phase_generate_certs
    phase_start_nodes
    phase_calibrate_dp3
    phase_check_startup
    if (( NODE_COUNT == 1 )); then
        phase_baseline_single
        phase_trip_single
        phase_settle_single
        phase_extract_events
        phase_evaluate_single
    else
        phase_measure_multi
        phase_extract_events
        phase_evaluate_multi
    fi
    log "Samples: $OUT_DIR/samples.tsv  Events: $OUT_DIR/events.tsv"

    section "Summary"
    if (( FAILURES == 0 )); then
        if (( WARNINGS == 0 )); then
            printf '%s🎉 All assertions PASSED%s\n' "$C_GRN$C_BLD" "$C_RESET"
        else
            printf '%s🎉 All assertions PASSED%s (%d warning(s) — see above)\n' "$C_GRN$C_BLD" "$C_RESET" "$WARNINGS"
        fi
        exit 0
    fi
    printf '%s❌ %d assertion(s) FAILED%s — see %s\n' "$C_RED$C_BLD" "$FAILURES" "$C_RESET" "$OUT_DIR"
    exit 1
}

main "$@"
