{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "repository-azure",
    "version": "1.0.0-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zu7ad2fiujgafhgplvfl47asva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-storage",
          "version": {
            "requires": "8.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-keyvault-core",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "repository-azure-1.0.0-alpha2.jar",
          "url": "repository-azure-1.0.0-alpha2.jar",
          "size": 43516,
          "sha512": "85e7af7c992000e7ca9a17d7c178c26eb75b3098bf36d3ca8e5dd748caa5f99cd2d643a8b9b8a15defbd390c5663efcd9666d1fb29d2fdfeed2563b66f2fe93a",
          "sha256": "10462416c3ca8771cfe340516fd53c492b19ba61ae8844427fa444403d43acc9",
          "sha1": "0fbd160e6d893055249d90965ae46d39281ef3f8",
          "md5": "657b8c459af6edc745737a3bdd965ebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.microsoft.azure",
          "module": "azure-storage",
          "version": {
            "requires": "8.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.microsoft.azure",
          "module": "azure-keyvault-core",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "20.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "repository-azure-1.0.0-alpha2.jar",
          "url": "repository-azure-1.0.0-alpha2.jar",
          "size": 43516,
          "sha512": "85e7af7c992000e7ca9a17d7c178c26eb75b3098bf36d3ca8e5dd748caa5f99cd2d643a8b9b8a15defbd390c5663efcd9666d1fb29d2fdfeed2563b66f2fe93a",
          "sha256": "10462416c3ca8771cfe340516fd53c492b19ba61ae8844427fa444403d43acc9",
          "sha1": "0fbd160e6d893055249d90965ae46d39281ef3f8",
          "md5": "657b8c459af6edc745737a3bdd965ebf"
        }
      ]
    }
  ]
}
