name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@1901dc7d52169e70c27a8da37aef0d423e2867a2 # v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 22958780

      - name: Backport
        uses: VachaShah/backport@28c49d91ceec57d7c9f625f1031c1a4d637251f5 # v1.1.4
        with:
          github_token: ${{ steps.github_app_token.outputs.token }}
          branch_name: backport/backport-${{ github.event.number }}