name: DP Live Debugger

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: "data prepper pipeline configuration"
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  issues: write

jobs:
  dplive:
    runs-on: ubuntu-latest

    steps:
      - name: Run DataPrepper docker
        run: |
          echo "test input line" > input-file
          echo "sample-pipeline:\n\tsource:\n\t\tfile:\n\t\t\tpath:"./input-file"\n\tsink:\n\t\tfile:\n\t\t\tpath:"./output-file" >pipeline-config.yaml
          echo "ssl: false" > data-prepper-config.yaml
          docker pull opensearch-data-prepper:latest
          docker run --name data-prepper --network host  -v pipeline-config.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml  -v ./data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml opensearch-data-prepper:latest
          sleep 90
