name: kinesis-source-integration-tests

on:
  push:
    paths:
      - 'data-prepper-plugins/kinesis-source/**'
      - '*gradle*'
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'data-prepper-plugins/kinesis-source/**'
      - '*gradle*'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:

      - name: Git clone the repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
        with:
          role-to-assume: ${{ secrets.TEST_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.TEST_REGION }}
          output-credentials: true

      - name: Configure AWS Credentials file
        run: |
          aws configure set default.region ${{ secrets.TEST_REGION }}
          aws configure set default.aws_access_key_id ${{ steps.creds.outputs.aws-access-key-id }}
          aws configure set default.aws_secret_access_key ${{ steps.creds.outputs.aws-secret-access-key }}
          aws configure set default.aws_session_token ${{ steps.creds.outputs.aws-session-token }}
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Checkout Data Prepper
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          add-job-summary: on-failure

      - name: Run Kinesis Source integration tests
        run: |
          ./gradlew data-prepper-plugins:kinesis-source:integrationTest \
            -Dtests.kinesis.source.aws.region=${{ secrets.TEST_REGION }} --tests KinesisSourceIT
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: data-prepper-kinesis-source-integration-tests-java-${{ matrix.java }}
          path: '**/test-results/**/*.xml'

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          path: test-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@b9f6c61d965bcaa18acc02d6daf706373a448f02 # v1
        with:
          files: "test-results/**/*.xml"