name: Testing Resources CDK App Check

on:
  push:
    branches: [ main ]
    paths:
      - 'testing/aws-testing-cdk/**'
  pull_request:
    paths:
      - 'testing/aws-testing-cdk/**'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./testing/aws-testing-cdk
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '18'

    - name: Checkout Data Prepper
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Install NPM Dependencies
      run: npm install
    - name: Test
      run: npm run test
    - name: Lint
      run: npm run lint
